#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="EPRTRweb")]
	public partial class DataClassesWasteTransferDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesWasteTransferDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWasteTransferDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWasteTransferDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWasteTransferDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WASTETRANSFER> WASTETRANSFERs
		{
			get
			{
				return this.GetTable<WASTETRANSFER>();
			}
		}
		
		public System.Data.Linq.Table<WASTETRANSFER_TREATMENT> WASTETRANSFER_TREATMENTs
		{
			get
			{
				return this.GetTable<WASTETRANSFER_TREATMENT>();
			}
		}
		
		public System.Data.Linq.Table<WASTETRANSFER_HAZARDOUSTREATER> WASTETRANSFER_HAZARDOUSTREATERs
		{
			get
			{
				return this.GetTable<WASTETRANSFER_HAZARDOUSTREATER>();
			}
		}
		
		public System.Data.Linq.Table<WASTETRANSFER_CONFIDENTIAL> WASTETRANSFER_CONFIDENTIALs
		{
			get
			{
				return this.GetTable<WASTETRANSFER_CONFIDENTIAL>();
			}
		}
		
		public System.Data.Linq.Table<WASTETRANSFER_RECEIVINGCOUNTRY> WASTETRANSFER_RECEIVINGCOUNTRies
		{
			get
			{
				return this.GetTable<WASTETRANSFER_RECEIVINGCOUNTRY>();
			}
		}
	}
	
	[Table(Name="dbo.WASTETRANSFER")]
	public partial class WASTETRANSFER
	{
		
		private int _FacilityReportID;
		
		private string _FacilityName;
		
		private int _FacilityID;
		
		private int _ReportingYear;
		
		private System.Nullable<double> _QuantityRecoveryNONHW;
		
		private System.Nullable<double> _QuantityDisposalNONHW;
		
		private System.Nullable<double> _QuantityUnspecNONHW;
		
		private System.Nullable<double> _QuantityTotalNONHW;
		
		private string _UnitCodeNONHW;
		
		private System.Nullable<double> _QuantityRecoveryHWIC;
		
		private System.Nullable<double> _QuantityDisposalHWIC;
		
		private System.Nullable<double> _QuantityUnspecHWIC;
		
		private System.Nullable<double> _QuantityTotalHWIC;
		
		private string _UnitCodeHWIC;
		
		private System.Nullable<double> _QuantityRecoveryHWOC;
		
		private System.Nullable<double> _QuantityDisposalHWOC;
		
		private System.Nullable<double> _QuantityUnspecHWOC;
		
		private System.Nullable<double> _QuantityTotalHWOC;
		
		private string _UnitCodeHWOC;
		
		private string _CountryCode;
		
		private int _LOV_CountryID;
		
		private string _RiverBasinDistrictCode;
		
		private int _LOV_RiverBasinDistrictID;
		
		private string _NUTSLevel2RegionCode;
		
		private System.Nullable<int> _LOV_NUTSRLevel1ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel2ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel3ID;
		
		private string _IASectorCode;
		
		private string _IAActivityCode;
		
		private string _IASubActivityCode;
		
		private string _IPPCSectorCode;
		
		private string _IPPCActivityCode;
		
		private string _IPPCSubActivityCode;
		
		private System.Nullable<int> _LOV_IASectorID;
		
		private System.Nullable<int> _LOV_IAActivityID;
		
		private System.Nullable<int> _LOV_IASubActivityID;
		
		private string _NACESectorCode;
		
		private string _NACEActivityCode;
		
		private string _NACESubActivityCode;
		
		private System.Nullable<int> _LOV_NACESectorID;
		
		private System.Nullable<int> _LOV_NACEActivityID;
		
		private System.Nullable<int> _LOV_NACESubActivityID;
		
		private bool _HasReportedRecovery;
		
		private bool _HasReportedDisposal;
		
		private bool _HasReportedUnspecified;
		
		private System.Nullable<bool> _ConfidentialIndicatorNONHW;
		
		private System.Nullable<bool> _ConfidentialIndicatorHWOC;
		
		private System.Nullable<bool> _ConfidentialIndicatorHWIC;
		
		private bool _ConfidentialIndicatorWaste;
		
		private bool _ConfidentialIndicatorFacility;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWIC_Recovery;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWIC_Disposal;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWIC_Unspec;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWOC_Recovery;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWOC_Disposal;
		
		private System.Nullable<bool> _ConfidentialIndicator_HWOC_Unspec;
		
		private System.Nullable<bool> _ConfidentialIndicator_NONHW_Recovery;
		
		private System.Nullable<bool> _ConfidentialIndicator_NONHW_Disposal;
		
		private System.Nullable<bool> _ConfidentialIndicator_NONHW_Unspec;
		
		public WASTETRANSFER()
		{
		}
		
		[Column(Storage="_FacilityReportID", DbType="Int NOT NULL")]
		public int FacilityReportID
		{
			get
			{
				return this._FacilityReportID;
			}
			set
			{
				if ((this._FacilityReportID != value))
				{
					this._FacilityReportID = value;
				}
			}
		}
		
		[Column(Storage="_FacilityName", DbType="NVarChar(255)")]
		public string FacilityName
		{
			get
			{
				return this._FacilityName;
			}
			set
			{
				if ((this._FacilityName != value))
				{
					this._FacilityName = value;
				}
			}
		}
		
		[Column(Storage="_FacilityID", DbType="Int NOT NULL")]
		public int FacilityID
		{
			get
			{
				return this._FacilityID;
			}
			set
			{
				if ((this._FacilityID != value))
				{
					this._FacilityID = value;
				}
			}
		}
		
		[Column(Storage="_ReportingYear", DbType="Int NOT NULL")]
		public int ReportingYear
		{
			get
			{
				return this._ReportingYear;
			}
			set
			{
				if ((this._ReportingYear != value))
				{
					this._ReportingYear = value;
				}
			}
		}
		
		[Column(Storage="_QuantityRecoveryNONHW", DbType="Float")]
		public System.Nullable<double> QuantityRecoveryNONHW
		{
			get
			{
				return this._QuantityRecoveryNONHW;
			}
			set
			{
				if ((this._QuantityRecoveryNONHW != value))
				{
					this._QuantityRecoveryNONHW = value;
				}
			}
		}
		
		[Column(Storage="_QuantityDisposalNONHW", DbType="Float")]
		public System.Nullable<double> QuantityDisposalNONHW
		{
			get
			{
				return this._QuantityDisposalNONHW;
			}
			set
			{
				if ((this._QuantityDisposalNONHW != value))
				{
					this._QuantityDisposalNONHW = value;
				}
			}
		}
		
		[Column(Storage="_QuantityUnspecNONHW", DbType="Float")]
		public System.Nullable<double> QuantityUnspecNONHW
		{
			get
			{
				return this._QuantityUnspecNONHW;
			}
			set
			{
				if ((this._QuantityUnspecNONHW != value))
				{
					this._QuantityUnspecNONHW = value;
				}
			}
		}
		
		[Column(Storage="_QuantityTotalNONHW", DbType="Float")]
		public System.Nullable<double> QuantityTotalNONHW
		{
			get
			{
				return this._QuantityTotalNONHW;
			}
			set
			{
				if ((this._QuantityTotalNONHW != value))
				{
					this._QuantityTotalNONHW = value;
				}
			}
		}
		
		[Column(Storage="_UnitCodeNONHW", DbType="NVarChar(255)")]
		public string UnitCodeNONHW
		{
			get
			{
				return this._UnitCodeNONHW;
			}
			set
			{
				if ((this._UnitCodeNONHW != value))
				{
					this._UnitCodeNONHW = value;
				}
			}
		}
		
		[Column(Storage="_QuantityRecoveryHWIC", DbType="Float")]
		public System.Nullable<double> QuantityRecoveryHWIC
		{
			get
			{
				return this._QuantityRecoveryHWIC;
			}
			set
			{
				if ((this._QuantityRecoveryHWIC != value))
				{
					this._QuantityRecoveryHWIC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityDisposalHWIC", DbType="Float")]
		public System.Nullable<double> QuantityDisposalHWIC
		{
			get
			{
				return this._QuantityDisposalHWIC;
			}
			set
			{
				if ((this._QuantityDisposalHWIC != value))
				{
					this._QuantityDisposalHWIC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityUnspecHWIC", DbType="Float")]
		public System.Nullable<double> QuantityUnspecHWIC
		{
			get
			{
				return this._QuantityUnspecHWIC;
			}
			set
			{
				if ((this._QuantityUnspecHWIC != value))
				{
					this._QuantityUnspecHWIC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityTotalHWIC", DbType="Float")]
		public System.Nullable<double> QuantityTotalHWIC
		{
			get
			{
				return this._QuantityTotalHWIC;
			}
			set
			{
				if ((this._QuantityTotalHWIC != value))
				{
					this._QuantityTotalHWIC = value;
				}
			}
		}
		
		[Column(Storage="_UnitCodeHWIC", DbType="NVarChar(255)")]
		public string UnitCodeHWIC
		{
			get
			{
				return this._UnitCodeHWIC;
			}
			set
			{
				if ((this._UnitCodeHWIC != value))
				{
					this._UnitCodeHWIC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityRecoveryHWOC", DbType="Float")]
		public System.Nullable<double> QuantityRecoveryHWOC
		{
			get
			{
				return this._QuantityRecoveryHWOC;
			}
			set
			{
				if ((this._QuantityRecoveryHWOC != value))
				{
					this._QuantityRecoveryHWOC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityDisposalHWOC", DbType="Float")]
		public System.Nullable<double> QuantityDisposalHWOC
		{
			get
			{
				return this._QuantityDisposalHWOC;
			}
			set
			{
				if ((this._QuantityDisposalHWOC != value))
				{
					this._QuantityDisposalHWOC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityUnspecHWOC", DbType="Float")]
		public System.Nullable<double> QuantityUnspecHWOC
		{
			get
			{
				return this._QuantityUnspecHWOC;
			}
			set
			{
				if ((this._QuantityUnspecHWOC != value))
				{
					this._QuantityUnspecHWOC = value;
				}
			}
		}
		
		[Column(Storage="_QuantityTotalHWOC", DbType="Float")]
		public System.Nullable<double> QuantityTotalHWOC
		{
			get
			{
				return this._QuantityTotalHWOC;
			}
			set
			{
				if ((this._QuantityTotalHWOC != value))
				{
					this._QuantityTotalHWOC = value;
				}
			}
		}
		
		[Column(Storage="_UnitCodeHWOC", DbType="NVarChar(255)")]
		public string UnitCodeHWOC
		{
			get
			{
				return this._UnitCodeHWOC;
			}
			set
			{
				if ((this._UnitCodeHWOC != value))
				{
					this._UnitCodeHWOC = value;
				}
			}
		}
		
		[Column(Storage="_CountryCode", DbType="NVarChar(255)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_CountryID", DbType="Int NOT NULL")]
		public int LOV_CountryID
		{
			get
			{
				return this._LOV_CountryID;
			}
			set
			{
				if ((this._LOV_CountryID != value))
				{
					this._LOV_CountryID = value;
				}
			}
		}
		
		[Column(Storage="_RiverBasinDistrictCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string RiverBasinDistrictCode
		{
			get
			{
				return this._RiverBasinDistrictCode;
			}
			set
			{
				if ((this._RiverBasinDistrictCode != value))
				{
					this._RiverBasinDistrictCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_RiverBasinDistrictID", DbType="Int NOT NULL")]
		public int LOV_RiverBasinDistrictID
		{
			get
			{
				return this._LOV_RiverBasinDistrictID;
			}
			set
			{
				if ((this._LOV_RiverBasinDistrictID != value))
				{
					this._LOV_RiverBasinDistrictID = value;
				}
			}
		}
		
		[Column(Storage="_NUTSLevel2RegionCode", DbType="NVarChar(255)")]
		public string NUTSLevel2RegionCode
		{
			get
			{
				return this._NUTSLevel2RegionCode;
			}
			set
			{
				if ((this._NUTSLevel2RegionCode != value))
				{
					this._NUTSLevel2RegionCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel1ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel1ID
		{
			get
			{
				return this._LOV_NUTSRLevel1ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel1ID != value))
				{
					this._LOV_NUTSRLevel1ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel2ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel2ID
		{
			get
			{
				return this._LOV_NUTSRLevel2ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel2ID != value))
				{
					this._LOV_NUTSRLevel2ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel3ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel3ID
		{
			get
			{
				return this._LOV_NUTSRLevel3ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel3ID != value))
				{
					this._LOV_NUTSRLevel3ID = value;
				}
			}
		}
		
		[Column(Storage="_IASectorCode", DbType="NVarChar(255)")]
		public string IASectorCode
		{
			get
			{
				return this._IASectorCode;
			}
			set
			{
				if ((this._IASectorCode != value))
				{
					this._IASectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IAActivityCode", DbType="NVarChar(255)")]
		public string IAActivityCode
		{
			get
			{
				return this._IAActivityCode;
			}
			set
			{
				if ((this._IAActivityCode != value))
				{
					this._IAActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IASubActivityCode", DbType="NVarChar(255)")]
		public string IASubActivityCode
		{
			get
			{
				return this._IASubActivityCode;
			}
			set
			{
				if ((this._IASubActivityCode != value))
				{
					this._IASubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSectorCode", DbType="NVarChar(255)")]
		public string IPPCSectorCode
		{
			get
			{
				return this._IPPCSectorCode;
			}
			set
			{
				if ((this._IPPCSectorCode != value))
				{
					this._IPPCSectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCActivityCode", DbType="NVarChar(255)")]
		public string IPPCActivityCode
		{
			get
			{
				return this._IPPCActivityCode;
			}
			set
			{
				if ((this._IPPCActivityCode != value))
				{
					this._IPPCActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSubActivityCode", DbType="NVarChar(255)")]
		public string IPPCSubActivityCode
		{
			get
			{
				return this._IPPCSubActivityCode;
			}
			set
			{
				if ((this._IPPCSubActivityCode != value))
				{
					this._IPPCSubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASectorID", DbType="Int")]
		public System.Nullable<int> LOV_IASectorID
		{
			get
			{
				return this._LOV_IASectorID;
			}
			set
			{
				if ((this._LOV_IASectorID != value))
				{
					this._LOV_IASectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IAActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IAActivityID
		{
			get
			{
				return this._LOV_IAActivityID;
			}
			set
			{
				if ((this._LOV_IAActivityID != value))
				{
					this._LOV_IAActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IASubActivityID
		{
			get
			{
				return this._LOV_IASubActivityID;
			}
			set
			{
				if ((this._LOV_IASubActivityID != value))
				{
					this._LOV_IASubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_NACESectorCode", DbType="NVarChar(255)")]
		public string NACESectorCode
		{
			get
			{
				return this._NACESectorCode;
			}
			set
			{
				if ((this._NACESectorCode != value))
				{
					this._NACESectorCode = value;
				}
			}
		}
		
		[Column(Storage="_NACEActivityCode", DbType="NVarChar(255)")]
		public string NACEActivityCode
		{
			get
			{
				return this._NACEActivityCode;
			}
			set
			{
				if ((this._NACEActivityCode != value))
				{
					this._NACEActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_NACESubActivityCode", DbType="NVarChar(255)")]
		public string NACESubActivityCode
		{
			get
			{
				return this._NACESubActivityCode;
			}
			set
			{
				if ((this._NACESubActivityCode != value))
				{
					this._NACESubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESectorID", DbType="Int")]
		public System.Nullable<int> LOV_NACESectorID
		{
			get
			{
				return this._LOV_NACESectorID;
			}
			set
			{
				if ((this._LOV_NACESectorID != value))
				{
					this._LOV_NACESectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACEActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACEActivityID
		{
			get
			{
				return this._LOV_NACEActivityID;
			}
			set
			{
				if ((this._LOV_NACEActivityID != value))
				{
					this._LOV_NACEActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACESubActivityID
		{
			get
			{
				return this._LOV_NACESubActivityID;
			}
			set
			{
				if ((this._LOV_NACESubActivityID != value))
				{
					this._LOV_NACESubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedRecovery", DbType="Bit NOT NULL")]
		public bool HasReportedRecovery
		{
			get
			{
				return this._HasReportedRecovery;
			}
			set
			{
				if ((this._HasReportedRecovery != value))
				{
					this._HasReportedRecovery = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedDisposal", DbType="Bit NOT NULL")]
		public bool HasReportedDisposal
		{
			get
			{
				return this._HasReportedDisposal;
			}
			set
			{
				if ((this._HasReportedDisposal != value))
				{
					this._HasReportedDisposal = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedUnspecified", DbType="Bit NOT NULL")]
		public bool HasReportedUnspecified
		{
			get
			{
				return this._HasReportedUnspecified;
			}
			set
			{
				if ((this._HasReportedUnspecified != value))
				{
					this._HasReportedUnspecified = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorNONHW", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorNONHW
		{
			get
			{
				return this._ConfidentialIndicatorNONHW;
			}
			set
			{
				if ((this._ConfidentialIndicatorNONHW != value))
				{
					this._ConfidentialIndicatorNONHW = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorHWOC", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorHWOC
		{
			get
			{
				return this._ConfidentialIndicatorHWOC;
			}
			set
			{
				if ((this._ConfidentialIndicatorHWOC != value))
				{
					this._ConfidentialIndicatorHWOC = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorHWIC", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorHWIC
		{
			get
			{
				return this._ConfidentialIndicatorHWIC;
			}
			set
			{
				if ((this._ConfidentialIndicatorHWIC != value))
				{
					this._ConfidentialIndicatorHWIC = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorWaste", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicatorWaste
		{
			get
			{
				return this._ConfidentialIndicatorWaste;
			}
			set
			{
				if ((this._ConfidentialIndicatorWaste != value))
				{
					this._ConfidentialIndicatorWaste = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorFacility", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicatorFacility
		{
			get
			{
				return this._ConfidentialIndicatorFacility;
			}
			set
			{
				if ((this._ConfidentialIndicatorFacility != value))
				{
					this._ConfidentialIndicatorFacility = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWIC_Recovery", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWIC_Recovery
		{
			get
			{
				return this._ConfidentialIndicator_HWIC_Recovery;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWIC_Recovery != value))
				{
					this._ConfidentialIndicator_HWIC_Recovery = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWIC_Disposal", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWIC_Disposal
		{
			get
			{
				return this._ConfidentialIndicator_HWIC_Disposal;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWIC_Disposal != value))
				{
					this._ConfidentialIndicator_HWIC_Disposal = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWIC_Unspec", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWIC_Unspec
		{
			get
			{
				return this._ConfidentialIndicator_HWIC_Unspec;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWIC_Unspec != value))
				{
					this._ConfidentialIndicator_HWIC_Unspec = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWOC_Recovery", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWOC_Recovery
		{
			get
			{
				return this._ConfidentialIndicator_HWOC_Recovery;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWOC_Recovery != value))
				{
					this._ConfidentialIndicator_HWOC_Recovery = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWOC_Disposal", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWOC_Disposal
		{
			get
			{
				return this._ConfidentialIndicator_HWOC_Disposal;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWOC_Disposal != value))
				{
					this._ConfidentialIndicator_HWOC_Disposal = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_HWOC_Unspec", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_HWOC_Unspec
		{
			get
			{
				return this._ConfidentialIndicator_HWOC_Unspec;
			}
			set
			{
				if ((this._ConfidentialIndicator_HWOC_Unspec != value))
				{
					this._ConfidentialIndicator_HWOC_Unspec = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_NONHW_Recovery", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_NONHW_Recovery
		{
			get
			{
				return this._ConfidentialIndicator_NONHW_Recovery;
			}
			set
			{
				if ((this._ConfidentialIndicator_NONHW_Recovery != value))
				{
					this._ConfidentialIndicator_NONHW_Recovery = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_NONHW_Disposal", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_NONHW_Disposal
		{
			get
			{
				return this._ConfidentialIndicator_NONHW_Disposal;
			}
			set
			{
				if ((this._ConfidentialIndicator_NONHW_Disposal != value))
				{
					this._ConfidentialIndicator_NONHW_Disposal = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator_NONHW_Unspec", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicator_NONHW_Unspec
		{
			get
			{
				return this._ConfidentialIndicator_NONHW_Unspec;
			}
			set
			{
				if ((this._ConfidentialIndicator_NONHW_Unspec != value))
				{
					this._ConfidentialIndicator_NONHW_Unspec = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.WASTETRANSFER_TREATMENT")]
	public partial class WASTETRANSFER_TREATMENT
	{
		
		private int _FacilityReportID;
		
		private string _WasteTypeCode;
		
		private string _FacilityName;
		
		private int _FacilityID;
		
		private int _ReportingYear;
		
		private System.Nullable<double> _QuantityRecovery;
		
		private System.Nullable<double> _QuantityDisposal;
		
		private System.Nullable<double> _QuantityUnspec;
		
		private System.Nullable<double> _QuantityTotal;
		
		private string _UnitCode;
		
		private string _CountryCode;
		
		private int _LOV_CountryID;
		
		private string _RiverBasinDistrictCode;
		
		private int _LOV_RiverBasinDistrictID;
		
		private string _NUTSLevel2RegionCode;
		
		private System.Nullable<int> _LOV_NUTSRLevel1ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel2ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel3ID;
		
		private string _IASectorCode;
		
		private string _IAActivityCode;
		
		private string _IASubActivityCode;
		
		private string _IPPCSectorCode;
		
		private string _IPPCActivityCode;
		
		private string _IPPCSubActivityCode;
		
		private System.Nullable<int> _LOV_IASectorID;
		
		private System.Nullable<int> _LOV_IAActivityID;
		
		private System.Nullable<int> _LOV_IASubActivityID;
		
		private string _NACESectorCode;
		
		private string _NACEActivityCode;
		
		private string _NACESubActivityCode;
		
		private System.Nullable<int> _LOV_NACESectorID;
		
		private System.Nullable<int> _LOV_NACEActivityID;
		
		private System.Nullable<int> _LOV_NACESubActivityID;
		
		private bool _HasReportedRecovery;
		
		private bool _HasReportedDisposal;
		
		private bool _HasReportedUnspecified;
		
		private bool _ConfidentialIndicatorFacility;
		
		private System.Nullable<bool> _ConfidentialIndicatorRecovery;
		
		private System.Nullable<bool> _ConfidentialIndicatorDisposal;
		
		private System.Nullable<bool> _ConfidentialIndicatorUnspec;
		
		public WASTETRANSFER_TREATMENT()
		{
		}
		
		[Column(Storage="_FacilityReportID", DbType="Int NOT NULL")]
		public int FacilityReportID
		{
			get
			{
				return this._FacilityReportID;
			}
			set
			{
				if ((this._FacilityReportID != value))
				{
					this._FacilityReportID = value;
				}
			}
		}
		
		[Column(Storage="_WasteTypeCode", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string WasteTypeCode
		{
			get
			{
				return this._WasteTypeCode;
			}
			set
			{
				if ((this._WasteTypeCode != value))
				{
					this._WasteTypeCode = value;
				}
			}
		}
		
		[Column(Storage="_FacilityName", DbType="NVarChar(255)")]
		public string FacilityName
		{
			get
			{
				return this._FacilityName;
			}
			set
			{
				if ((this._FacilityName != value))
				{
					this._FacilityName = value;
				}
			}
		}
		
		[Column(Storage="_FacilityID", DbType="Int NOT NULL")]
		public int FacilityID
		{
			get
			{
				return this._FacilityID;
			}
			set
			{
				if ((this._FacilityID != value))
				{
					this._FacilityID = value;
				}
			}
		}
		
		[Column(Storage="_ReportingYear", DbType="Int NOT NULL")]
		public int ReportingYear
		{
			get
			{
				return this._ReportingYear;
			}
			set
			{
				if ((this._ReportingYear != value))
				{
					this._ReportingYear = value;
				}
			}
		}
		
		[Column(Storage="_QuantityRecovery", DbType="Float")]
		public System.Nullable<double> QuantityRecovery
		{
			get
			{
				return this._QuantityRecovery;
			}
			set
			{
				if ((this._QuantityRecovery != value))
				{
					this._QuantityRecovery = value;
				}
			}
		}
		
		[Column(Storage="_QuantityDisposal", DbType="Float")]
		public System.Nullable<double> QuantityDisposal
		{
			get
			{
				return this._QuantityDisposal;
			}
			set
			{
				if ((this._QuantityDisposal != value))
				{
					this._QuantityDisposal = value;
				}
			}
		}
		
		[Column(Storage="_QuantityUnspec", DbType="Float")]
		public System.Nullable<double> QuantityUnspec
		{
			get
			{
				return this._QuantityUnspec;
			}
			set
			{
				if ((this._QuantityUnspec != value))
				{
					this._QuantityUnspec = value;
				}
			}
		}
		
		[Column(Storage="_QuantityTotal", DbType="Float")]
		public System.Nullable<double> QuantityTotal
		{
			get
			{
				return this._QuantityTotal;
			}
			set
			{
				if ((this._QuantityTotal != value))
				{
					this._QuantityTotal = value;
				}
			}
		}
		
		[Column(Storage="_UnitCode", DbType="NVarChar(255)")]
		public string UnitCode
		{
			get
			{
				return this._UnitCode;
			}
			set
			{
				if ((this._UnitCode != value))
				{
					this._UnitCode = value;
				}
			}
		}
		
		[Column(Storage="_CountryCode", DbType="NVarChar(255)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_CountryID", DbType="Int NOT NULL")]
		public int LOV_CountryID
		{
			get
			{
				return this._LOV_CountryID;
			}
			set
			{
				if ((this._LOV_CountryID != value))
				{
					this._LOV_CountryID = value;
				}
			}
		}
		
		[Column(Storage="_RiverBasinDistrictCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string RiverBasinDistrictCode
		{
			get
			{
				return this._RiverBasinDistrictCode;
			}
			set
			{
				if ((this._RiverBasinDistrictCode != value))
				{
					this._RiverBasinDistrictCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_RiverBasinDistrictID", DbType="Int NOT NULL")]
		public int LOV_RiverBasinDistrictID
		{
			get
			{
				return this._LOV_RiverBasinDistrictID;
			}
			set
			{
				if ((this._LOV_RiverBasinDistrictID != value))
				{
					this._LOV_RiverBasinDistrictID = value;
				}
			}
		}
		
		[Column(Storage="_NUTSLevel2RegionCode", DbType="NVarChar(255)")]
		public string NUTSLevel2RegionCode
		{
			get
			{
				return this._NUTSLevel2RegionCode;
			}
			set
			{
				if ((this._NUTSLevel2RegionCode != value))
				{
					this._NUTSLevel2RegionCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel1ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel1ID
		{
			get
			{
				return this._LOV_NUTSRLevel1ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel1ID != value))
				{
					this._LOV_NUTSRLevel1ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel2ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel2ID
		{
			get
			{
				return this._LOV_NUTSRLevel2ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel2ID != value))
				{
					this._LOV_NUTSRLevel2ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel3ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel3ID
		{
			get
			{
				return this._LOV_NUTSRLevel3ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel3ID != value))
				{
					this._LOV_NUTSRLevel3ID = value;
				}
			}
		}
		
		[Column(Storage="_IASectorCode", DbType="NVarChar(255)")]
		public string IASectorCode
		{
			get
			{
				return this._IASectorCode;
			}
			set
			{
				if ((this._IASectorCode != value))
				{
					this._IASectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IAActivityCode", DbType="NVarChar(255)")]
		public string IAActivityCode
		{
			get
			{
				return this._IAActivityCode;
			}
			set
			{
				if ((this._IAActivityCode != value))
				{
					this._IAActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IASubActivityCode", DbType="NVarChar(255)")]
		public string IASubActivityCode
		{
			get
			{
				return this._IASubActivityCode;
			}
			set
			{
				if ((this._IASubActivityCode != value))
				{
					this._IASubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSectorCode", DbType="NVarChar(255)")]
		public string IPPCSectorCode
		{
			get
			{
				return this._IPPCSectorCode;
			}
			set
			{
				if ((this._IPPCSectorCode != value))
				{
					this._IPPCSectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCActivityCode", DbType="NVarChar(255)")]
		public string IPPCActivityCode
		{
			get
			{
				return this._IPPCActivityCode;
			}
			set
			{
				if ((this._IPPCActivityCode != value))
				{
					this._IPPCActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSubActivityCode", DbType="NVarChar(255)")]
		public string IPPCSubActivityCode
		{
			get
			{
				return this._IPPCSubActivityCode;
			}
			set
			{
				if ((this._IPPCSubActivityCode != value))
				{
					this._IPPCSubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASectorID", DbType="Int")]
		public System.Nullable<int> LOV_IASectorID
		{
			get
			{
				return this._LOV_IASectorID;
			}
			set
			{
				if ((this._LOV_IASectorID != value))
				{
					this._LOV_IASectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IAActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IAActivityID
		{
			get
			{
				return this._LOV_IAActivityID;
			}
			set
			{
				if ((this._LOV_IAActivityID != value))
				{
					this._LOV_IAActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IASubActivityID
		{
			get
			{
				return this._LOV_IASubActivityID;
			}
			set
			{
				if ((this._LOV_IASubActivityID != value))
				{
					this._LOV_IASubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_NACESectorCode", DbType="NVarChar(255)")]
		public string NACESectorCode
		{
			get
			{
				return this._NACESectorCode;
			}
			set
			{
				if ((this._NACESectorCode != value))
				{
					this._NACESectorCode = value;
				}
			}
		}
		
		[Column(Storage="_NACEActivityCode", DbType="NVarChar(255)")]
		public string NACEActivityCode
		{
			get
			{
				return this._NACEActivityCode;
			}
			set
			{
				if ((this._NACEActivityCode != value))
				{
					this._NACEActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_NACESubActivityCode", DbType="NVarChar(255)")]
		public string NACESubActivityCode
		{
			get
			{
				return this._NACESubActivityCode;
			}
			set
			{
				if ((this._NACESubActivityCode != value))
				{
					this._NACESubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESectorID", DbType="Int")]
		public System.Nullable<int> LOV_NACESectorID
		{
			get
			{
				return this._LOV_NACESectorID;
			}
			set
			{
				if ((this._LOV_NACESectorID != value))
				{
					this._LOV_NACESectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACEActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACEActivityID
		{
			get
			{
				return this._LOV_NACEActivityID;
			}
			set
			{
				if ((this._LOV_NACEActivityID != value))
				{
					this._LOV_NACEActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACESubActivityID
		{
			get
			{
				return this._LOV_NACESubActivityID;
			}
			set
			{
				if ((this._LOV_NACESubActivityID != value))
				{
					this._LOV_NACESubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedRecovery", DbType="Bit NOT NULL")]
		public bool HasReportedRecovery
		{
			get
			{
				return this._HasReportedRecovery;
			}
			set
			{
				if ((this._HasReportedRecovery != value))
				{
					this._HasReportedRecovery = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedDisposal", DbType="Bit NOT NULL")]
		public bool HasReportedDisposal
		{
			get
			{
				return this._HasReportedDisposal;
			}
			set
			{
				if ((this._HasReportedDisposal != value))
				{
					this._HasReportedDisposal = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedUnspecified", DbType="Bit NOT NULL")]
		public bool HasReportedUnspecified
		{
			get
			{
				return this._HasReportedUnspecified;
			}
			set
			{
				if ((this._HasReportedUnspecified != value))
				{
					this._HasReportedUnspecified = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorFacility", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicatorFacility
		{
			get
			{
				return this._ConfidentialIndicatorFacility;
			}
			set
			{
				if ((this._ConfidentialIndicatorFacility != value))
				{
					this._ConfidentialIndicatorFacility = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorRecovery", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorRecovery
		{
			get
			{
				return this._ConfidentialIndicatorRecovery;
			}
			set
			{
				if ((this._ConfidentialIndicatorRecovery != value))
				{
					this._ConfidentialIndicatorRecovery = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorDisposal", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorDisposal
		{
			get
			{
				return this._ConfidentialIndicatorDisposal;
			}
			set
			{
				if ((this._ConfidentialIndicatorDisposal != value))
				{
					this._ConfidentialIndicatorDisposal = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorUnspec", DbType="Bit")]
		public System.Nullable<bool> ConfidentialIndicatorUnspec
		{
			get
			{
				return this._ConfidentialIndicatorUnspec;
			}
			set
			{
				if ((this._ConfidentialIndicatorUnspec != value))
				{
					this._ConfidentialIndicatorUnspec = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.WASTETRANSFER_HAZARDOUSTREATERS")]
	public partial class WASTETRANSFER_HAZARDOUSTREATER
	{
		
		private int _FacilityReportID;
		
		private string _FacilityName;
		
		private int _FacilityID;
		
		private int _ReportingYear;
		
		private string _WHPName;
		
		private string _WHPAddress;
		
		private string _WHPCity;
		
		private string _WHPPostalCode;
		
		private string _WHPCountryCode;
		
		private string _WHPSiteAddress;
		
		private string _WHPSiteCity;
		
		private string _WHPSitePostalCode;
		
		private string _WHPSiteCountryCode;
		
		private System.Nullable<double> _Quantity;
		
		private string _UnitCode;
		
		private string _WasteTreatmentCode;
		
		private System.Nullable<int> _NumberOfReports;
		
		private string _CountryCode;
		
		private int _LOV_CountryID;
		
		private string _RiverBasinDistrictCode;
		
		private int _LOV_RiverBasinDistrictID;
		
		private string _NUTSLevel2RegionCode;
		
		private System.Nullable<int> _LOV_NUTSRLevel1ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel2ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel3ID;
		
		private string _IASectorCode;
		
		private string _IAActivityCode;
		
		private string _IASubActivityCode;
		
		private string _IPPCSectorCode;
		
		private string _IPPCActivityCode;
		
		private string _IPPCSubActivityCode;
		
		private System.Nullable<int> _LOV_IASectorID;
		
		private System.Nullable<int> _LOV_IAActivityID;
		
		private System.Nullable<int> _LOV_IASubActivityID;
		
		private string _NACESectorCode;
		
		private string _NACEActivityCode;
		
		private string _NACESubActivityCode;
		
		private System.Nullable<int> _LOV_NACESectorID;
		
		private System.Nullable<int> _LOV_NACEActivityID;
		
		private System.Nullable<int> _LOV_NACESubActivityID;
		
		private string _ConfidentialCode;
		
		private System.Nullable<int> _LOV_ConfidentialityID;
		
		private bool _ConfidentialIndicator;
		
		private bool _ConfidentialIndicatorFacility;
		
		public WASTETRANSFER_HAZARDOUSTREATER()
		{
		}
		
		[Column(Storage="_FacilityReportID", DbType="Int NOT NULL")]
		public int FacilityReportID
		{
			get
			{
				return this._FacilityReportID;
			}
			set
			{
				if ((this._FacilityReportID != value))
				{
					this._FacilityReportID = value;
				}
			}
		}
		
		[Column(Storage="_FacilityName", DbType="NVarChar(255)")]
		public string FacilityName
		{
			get
			{
				return this._FacilityName;
			}
			set
			{
				if ((this._FacilityName != value))
				{
					this._FacilityName = value;
				}
			}
		}
		
		[Column(Storage="_FacilityID", DbType="Int NOT NULL")]
		public int FacilityID
		{
			get
			{
				return this._FacilityID;
			}
			set
			{
				if ((this._FacilityID != value))
				{
					this._FacilityID = value;
				}
			}
		}
		
		[Column(Storage="_ReportingYear", DbType="Int NOT NULL")]
		public int ReportingYear
		{
			get
			{
				return this._ReportingYear;
			}
			set
			{
				if ((this._ReportingYear != value))
				{
					this._ReportingYear = value;
				}
			}
		}
		
		[Column(Storage="_WHPName", DbType="NVarChar(255)")]
		public string WHPName
		{
			get
			{
				return this._WHPName;
			}
			set
			{
				if ((this._WHPName != value))
				{
					this._WHPName = value;
				}
			}
		}
		
		[Column(Storage="_WHPAddress", DbType="NVarChar(511)")]
		public string WHPAddress
		{
			get
			{
				return this._WHPAddress;
			}
			set
			{
				if ((this._WHPAddress != value))
				{
					this._WHPAddress = value;
				}
			}
		}
		
		[Column(Storage="_WHPCity", DbType="NVarChar(255)")]
		public string WHPCity
		{
			get
			{
				return this._WHPCity;
			}
			set
			{
				if ((this._WHPCity != value))
				{
					this._WHPCity = value;
				}
			}
		}
		
		[Column(Storage="_WHPPostalCode", DbType="NVarChar(50)")]
		public string WHPPostalCode
		{
			get
			{
				return this._WHPPostalCode;
			}
			set
			{
				if ((this._WHPPostalCode != value))
				{
					this._WHPPostalCode = value;
				}
			}
		}
		
		[Column(Storage="_WHPCountryCode", DbType="NVarChar(255)")]
		public string WHPCountryCode
		{
			get
			{
				return this._WHPCountryCode;
			}
			set
			{
				if ((this._WHPCountryCode != value))
				{
					this._WHPCountryCode = value;
				}
			}
		}
		
		[Column(Storage="_WHPSiteAddress", DbType="NVarChar(511)")]
		public string WHPSiteAddress
		{
			get
			{
				return this._WHPSiteAddress;
			}
			set
			{
				if ((this._WHPSiteAddress != value))
				{
					this._WHPSiteAddress = value;
				}
			}
		}
		
		[Column(Storage="_WHPSiteCity", DbType="NVarChar(255)")]
		public string WHPSiteCity
		{
			get
			{
				return this._WHPSiteCity;
			}
			set
			{
				if ((this._WHPSiteCity != value))
				{
					this._WHPSiteCity = value;
				}
			}
		}
		
		[Column(Storage="_WHPSitePostalCode", DbType="NVarChar(50)")]
		public string WHPSitePostalCode
		{
			get
			{
				return this._WHPSitePostalCode;
			}
			set
			{
				if ((this._WHPSitePostalCode != value))
				{
					this._WHPSitePostalCode = value;
				}
			}
		}
		
		[Column(Storage="_WHPSiteCountryCode", DbType="NVarChar(255)")]
		public string WHPSiteCountryCode
		{
			get
			{
				return this._WHPSiteCountryCode;
			}
			set
			{
				if ((this._WHPSiteCountryCode != value))
				{
					this._WHPSiteCountryCode = value;
				}
			}
		}
		
		[Column(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[Column(Storage="_UnitCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UnitCode
		{
			get
			{
				return this._UnitCode;
			}
			set
			{
				if ((this._UnitCode != value))
				{
					this._UnitCode = value;
				}
			}
		}
		
		[Column(Storage="_WasteTreatmentCode", DbType="NVarChar(255)")]
		public string WasteTreatmentCode
		{
			get
			{
				return this._WasteTreatmentCode;
			}
			set
			{
				if ((this._WasteTreatmentCode != value))
				{
					this._WasteTreatmentCode = value;
				}
			}
		}
		
		[Column(Storage="_NumberOfReports", DbType="Int")]
		public System.Nullable<int> NumberOfReports
		{
			get
			{
				return this._NumberOfReports;
			}
			set
			{
				if ((this._NumberOfReports != value))
				{
					this._NumberOfReports = value;
				}
			}
		}
		
		[Column(Storage="_CountryCode", DbType="NVarChar(255)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_CountryID", DbType="Int NOT NULL")]
		public int LOV_CountryID
		{
			get
			{
				return this._LOV_CountryID;
			}
			set
			{
				if ((this._LOV_CountryID != value))
				{
					this._LOV_CountryID = value;
				}
			}
		}
		
		[Column(Storage="_RiverBasinDistrictCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string RiverBasinDistrictCode
		{
			get
			{
				return this._RiverBasinDistrictCode;
			}
			set
			{
				if ((this._RiverBasinDistrictCode != value))
				{
					this._RiverBasinDistrictCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_RiverBasinDistrictID", DbType="Int NOT NULL")]
		public int LOV_RiverBasinDistrictID
		{
			get
			{
				return this._LOV_RiverBasinDistrictID;
			}
			set
			{
				if ((this._LOV_RiverBasinDistrictID != value))
				{
					this._LOV_RiverBasinDistrictID = value;
				}
			}
		}
		
		[Column(Storage="_NUTSLevel2RegionCode", DbType="NVarChar(255)")]
		public string NUTSLevel2RegionCode
		{
			get
			{
				return this._NUTSLevel2RegionCode;
			}
			set
			{
				if ((this._NUTSLevel2RegionCode != value))
				{
					this._NUTSLevel2RegionCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel1ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel1ID
		{
			get
			{
				return this._LOV_NUTSRLevel1ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel1ID != value))
				{
					this._LOV_NUTSRLevel1ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel2ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel2ID
		{
			get
			{
				return this._LOV_NUTSRLevel2ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel2ID != value))
				{
					this._LOV_NUTSRLevel2ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel3ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel3ID
		{
			get
			{
				return this._LOV_NUTSRLevel3ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel3ID != value))
				{
					this._LOV_NUTSRLevel3ID = value;
				}
			}
		}
		
		[Column(Storage="_IASectorCode", DbType="NVarChar(255)")]
		public string IASectorCode
		{
			get
			{
				return this._IASectorCode;
			}
			set
			{
				if ((this._IASectorCode != value))
				{
					this._IASectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IAActivityCode", DbType="NVarChar(255)")]
		public string IAActivityCode
		{
			get
			{
				return this._IAActivityCode;
			}
			set
			{
				if ((this._IAActivityCode != value))
				{
					this._IAActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IASubActivityCode", DbType="NVarChar(255)")]
		public string IASubActivityCode
		{
			get
			{
				return this._IASubActivityCode;
			}
			set
			{
				if ((this._IASubActivityCode != value))
				{
					this._IASubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSectorCode", DbType="NVarChar(255)")]
		public string IPPCSectorCode
		{
			get
			{
				return this._IPPCSectorCode;
			}
			set
			{
				if ((this._IPPCSectorCode != value))
				{
					this._IPPCSectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCActivityCode", DbType="NVarChar(255)")]
		public string IPPCActivityCode
		{
			get
			{
				return this._IPPCActivityCode;
			}
			set
			{
				if ((this._IPPCActivityCode != value))
				{
					this._IPPCActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSubActivityCode", DbType="NVarChar(255)")]
		public string IPPCSubActivityCode
		{
			get
			{
				return this._IPPCSubActivityCode;
			}
			set
			{
				if ((this._IPPCSubActivityCode != value))
				{
					this._IPPCSubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASectorID", DbType="Int")]
		public System.Nullable<int> LOV_IASectorID
		{
			get
			{
				return this._LOV_IASectorID;
			}
			set
			{
				if ((this._LOV_IASectorID != value))
				{
					this._LOV_IASectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IAActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IAActivityID
		{
			get
			{
				return this._LOV_IAActivityID;
			}
			set
			{
				if ((this._LOV_IAActivityID != value))
				{
					this._LOV_IAActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IASubActivityID
		{
			get
			{
				return this._LOV_IASubActivityID;
			}
			set
			{
				if ((this._LOV_IASubActivityID != value))
				{
					this._LOV_IASubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_NACESectorCode", DbType="NVarChar(255)")]
		public string NACESectorCode
		{
			get
			{
				return this._NACESectorCode;
			}
			set
			{
				if ((this._NACESectorCode != value))
				{
					this._NACESectorCode = value;
				}
			}
		}
		
		[Column(Storage="_NACEActivityCode", DbType="NVarChar(255)")]
		public string NACEActivityCode
		{
			get
			{
				return this._NACEActivityCode;
			}
			set
			{
				if ((this._NACEActivityCode != value))
				{
					this._NACEActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_NACESubActivityCode", DbType="NVarChar(255)")]
		public string NACESubActivityCode
		{
			get
			{
				return this._NACESubActivityCode;
			}
			set
			{
				if ((this._NACESubActivityCode != value))
				{
					this._NACESubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESectorID", DbType="Int")]
		public System.Nullable<int> LOV_NACESectorID
		{
			get
			{
				return this._LOV_NACESectorID;
			}
			set
			{
				if ((this._LOV_NACESectorID != value))
				{
					this._LOV_NACESectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACEActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACEActivityID
		{
			get
			{
				return this._LOV_NACEActivityID;
			}
			set
			{
				if ((this._LOV_NACEActivityID != value))
				{
					this._LOV_NACEActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACESubActivityID
		{
			get
			{
				return this._LOV_NACESubActivityID;
			}
			set
			{
				if ((this._LOV_NACESubActivityID != value))
				{
					this._LOV_NACESubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialCode", DbType="NVarChar(255)")]
		public string ConfidentialCode
		{
			get
			{
				return this._ConfidentialCode;
			}
			set
			{
				if ((this._ConfidentialCode != value))
				{
					this._ConfidentialCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_ConfidentialityID", DbType="Int")]
		public System.Nullable<int> LOV_ConfidentialityID
		{
			get
			{
				return this._LOV_ConfidentialityID;
			}
			set
			{
				if ((this._LOV_ConfidentialityID != value))
				{
					this._LOV_ConfidentialityID = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicator
		{
			get
			{
				return this._ConfidentialIndicator;
			}
			set
			{
				if ((this._ConfidentialIndicator != value))
				{
					this._ConfidentialIndicator = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorFacility", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicatorFacility
		{
			get
			{
				return this._ConfidentialIndicatorFacility;
			}
			set
			{
				if ((this._ConfidentialIndicatorFacility != value))
				{
					this._ConfidentialIndicatorFacility = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.WASTETRANSFER_CONFIDENTIAL")]
	public partial class WASTETRANSFER_CONFIDENTIAL
	{
		
		private int _FacilityReportID;
		
		private int _LOV_WasteTypeID;
		
		private string _WasteTypeCode;
		
		private int _LOV_ConfidentialityID;
		
		private string _ConfidentialCode;
		
		private System.Nullable<bool> _ConfidentialityOnQuantity;
		
		private System.Nullable<bool> _ConfidentialityOnTreatmant;
		
		private System.Nullable<bool> _ConfidentialityOnReceivingCountry;
		
		private int _ReportingYear;
		
		private string _CountryCode;
		
		private int _LOV_CountryID;
		
		private string _RiverBasinDistrictCode;
		
		private int _LOV_RiverBasinDistrictID;
		
		private string _NUTSLevel2RegionCode;
		
		private System.Nullable<int> _LOV_NUTSRLevel1ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel2ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel3ID;
		
		private string _IASectorCode;
		
		private string _IAActivityCode;
		
		private string _IASubActivityCode;
		
		private string _IPPCSectorCode;
		
		private string _IPPCActivityCode;
		
		private string _IPPCSubActivityCode;
		
		private System.Nullable<int> _LOV_IASectorID;
		
		private System.Nullable<int> _LOV_IAActivityID;
		
		private System.Nullable<int> _LOV_IASubActivityID;
		
		private string _NACESectorCode;
		
		private string _NACEActivityCode;
		
		private string _NACESubActivityCode;
		
		private System.Nullable<int> _LOV_NACESectorID;
		
		private System.Nullable<int> _LOV_NACEActivityID;
		
		private System.Nullable<int> _LOV_NACESubActivityID;
		
		private bool _HasReportedRecovery;
		
		private bool _HasReportedDisposal;
		
		private bool _HasReportedUnspecified;
		
		public WASTETRANSFER_CONFIDENTIAL()
		{
		}
		
		[Column(Storage="_FacilityReportID", DbType="Int NOT NULL")]
		public int FacilityReportID
		{
			get
			{
				return this._FacilityReportID;
			}
			set
			{
				if ((this._FacilityReportID != value))
				{
					this._FacilityReportID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_WasteTypeID", DbType="Int NOT NULL")]
		public int LOV_WasteTypeID
		{
			get
			{
				return this._LOV_WasteTypeID;
			}
			set
			{
				if ((this._LOV_WasteTypeID != value))
				{
					this._LOV_WasteTypeID = value;
				}
			}
		}
		
		[Column(Storage="_WasteTypeCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string WasteTypeCode
		{
			get
			{
				return this._WasteTypeCode;
			}
			set
			{
				if ((this._WasteTypeCode != value))
				{
					this._WasteTypeCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_ConfidentialityID", DbType="Int NOT NULL")]
		public int LOV_ConfidentialityID
		{
			get
			{
				return this._LOV_ConfidentialityID;
			}
			set
			{
				if ((this._LOV_ConfidentialityID != value))
				{
					this._LOV_ConfidentialityID = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ConfidentialCode
		{
			get
			{
				return this._ConfidentialCode;
			}
			set
			{
				if ((this._ConfidentialCode != value))
				{
					this._ConfidentialCode = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialityOnQuantity", DbType="Bit")]
		public System.Nullable<bool> ConfidentialityOnQuantity
		{
			get
			{
				return this._ConfidentialityOnQuantity;
			}
			set
			{
				if ((this._ConfidentialityOnQuantity != value))
				{
					this._ConfidentialityOnQuantity = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialityOnTreatmant", DbType="Bit")]
		public System.Nullable<bool> ConfidentialityOnTreatmant
		{
			get
			{
				return this._ConfidentialityOnTreatmant;
			}
			set
			{
				if ((this._ConfidentialityOnTreatmant != value))
				{
					this._ConfidentialityOnTreatmant = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialityOnReceivingCountry", DbType="Bit")]
		public System.Nullable<bool> ConfidentialityOnReceivingCountry
		{
			get
			{
				return this._ConfidentialityOnReceivingCountry;
			}
			set
			{
				if ((this._ConfidentialityOnReceivingCountry != value))
				{
					this._ConfidentialityOnReceivingCountry = value;
				}
			}
		}
		
		[Column(Storage="_ReportingYear", DbType="Int NOT NULL")]
		public int ReportingYear
		{
			get
			{
				return this._ReportingYear;
			}
			set
			{
				if ((this._ReportingYear != value))
				{
					this._ReportingYear = value;
				}
			}
		}
		
		[Column(Storage="_CountryCode", DbType="NVarChar(255)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_CountryID", DbType="Int NOT NULL")]
		public int LOV_CountryID
		{
			get
			{
				return this._LOV_CountryID;
			}
			set
			{
				if ((this._LOV_CountryID != value))
				{
					this._LOV_CountryID = value;
				}
			}
		}
		
		[Column(Storage="_RiverBasinDistrictCode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string RiverBasinDistrictCode
		{
			get
			{
				return this._RiverBasinDistrictCode;
			}
			set
			{
				if ((this._RiverBasinDistrictCode != value))
				{
					this._RiverBasinDistrictCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_RiverBasinDistrictID", DbType="Int NOT NULL")]
		public int LOV_RiverBasinDistrictID
		{
			get
			{
				return this._LOV_RiverBasinDistrictID;
			}
			set
			{
				if ((this._LOV_RiverBasinDistrictID != value))
				{
					this._LOV_RiverBasinDistrictID = value;
				}
			}
		}
		
		[Column(Storage="_NUTSLevel2RegionCode", DbType="NVarChar(255)")]
		public string NUTSLevel2RegionCode
		{
			get
			{
				return this._NUTSLevel2RegionCode;
			}
			set
			{
				if ((this._NUTSLevel2RegionCode != value))
				{
					this._NUTSLevel2RegionCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel1ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel1ID
		{
			get
			{
				return this._LOV_NUTSRLevel1ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel1ID != value))
				{
					this._LOV_NUTSRLevel1ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel2ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel2ID
		{
			get
			{
				return this._LOV_NUTSRLevel2ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel2ID != value))
				{
					this._LOV_NUTSRLevel2ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel3ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel3ID
		{
			get
			{
				return this._LOV_NUTSRLevel3ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel3ID != value))
				{
					this._LOV_NUTSRLevel3ID = value;
				}
			}
		}
		
		[Column(Storage="_IASectorCode", DbType="NVarChar(255)")]
		public string IASectorCode
		{
			get
			{
				return this._IASectorCode;
			}
			set
			{
				if ((this._IASectorCode != value))
				{
					this._IASectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IAActivityCode", DbType="NVarChar(255)")]
		public string IAActivityCode
		{
			get
			{
				return this._IAActivityCode;
			}
			set
			{
				if ((this._IAActivityCode != value))
				{
					this._IAActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IASubActivityCode", DbType="NVarChar(255)")]
		public string IASubActivityCode
		{
			get
			{
				return this._IASubActivityCode;
			}
			set
			{
				if ((this._IASubActivityCode != value))
				{
					this._IASubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSectorCode", DbType="NVarChar(255)")]
		public string IPPCSectorCode
		{
			get
			{
				return this._IPPCSectorCode;
			}
			set
			{
				if ((this._IPPCSectorCode != value))
				{
					this._IPPCSectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCActivityCode", DbType="NVarChar(255)")]
		public string IPPCActivityCode
		{
			get
			{
				return this._IPPCActivityCode;
			}
			set
			{
				if ((this._IPPCActivityCode != value))
				{
					this._IPPCActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSubActivityCode", DbType="NVarChar(255)")]
		public string IPPCSubActivityCode
		{
			get
			{
				return this._IPPCSubActivityCode;
			}
			set
			{
				if ((this._IPPCSubActivityCode != value))
				{
					this._IPPCSubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASectorID", DbType="Int")]
		public System.Nullable<int> LOV_IASectorID
		{
			get
			{
				return this._LOV_IASectorID;
			}
			set
			{
				if ((this._LOV_IASectorID != value))
				{
					this._LOV_IASectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IAActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IAActivityID
		{
			get
			{
				return this._LOV_IAActivityID;
			}
			set
			{
				if ((this._LOV_IAActivityID != value))
				{
					this._LOV_IAActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IASubActivityID
		{
			get
			{
				return this._LOV_IASubActivityID;
			}
			set
			{
				if ((this._LOV_IASubActivityID != value))
				{
					this._LOV_IASubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_NACESectorCode", DbType="NVarChar(255)")]
		public string NACESectorCode
		{
			get
			{
				return this._NACESectorCode;
			}
			set
			{
				if ((this._NACESectorCode != value))
				{
					this._NACESectorCode = value;
				}
			}
		}
		
		[Column(Storage="_NACEActivityCode", DbType="NVarChar(255)")]
		public string NACEActivityCode
		{
			get
			{
				return this._NACEActivityCode;
			}
			set
			{
				if ((this._NACEActivityCode != value))
				{
					this._NACEActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_NACESubActivityCode", DbType="NVarChar(255)")]
		public string NACESubActivityCode
		{
			get
			{
				return this._NACESubActivityCode;
			}
			set
			{
				if ((this._NACESubActivityCode != value))
				{
					this._NACESubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESectorID", DbType="Int")]
		public System.Nullable<int> LOV_NACESectorID
		{
			get
			{
				return this._LOV_NACESectorID;
			}
			set
			{
				if ((this._LOV_NACESectorID != value))
				{
					this._LOV_NACESectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACEActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACEActivityID
		{
			get
			{
				return this._LOV_NACEActivityID;
			}
			set
			{
				if ((this._LOV_NACEActivityID != value))
				{
					this._LOV_NACEActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACESubActivityID
		{
			get
			{
				return this._LOV_NACESubActivityID;
			}
			set
			{
				if ((this._LOV_NACESubActivityID != value))
				{
					this._LOV_NACESubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedRecovery", DbType="Bit NOT NULL")]
		public bool HasReportedRecovery
		{
			get
			{
				return this._HasReportedRecovery;
			}
			set
			{
				if ((this._HasReportedRecovery != value))
				{
					this._HasReportedRecovery = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedDisposal", DbType="Bit NOT NULL")]
		public bool HasReportedDisposal
		{
			get
			{
				return this._HasReportedDisposal;
			}
			set
			{
				if ((this._HasReportedDisposal != value))
				{
					this._HasReportedDisposal = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedUnspecified", DbType="Bit NOT NULL")]
		public bool HasReportedUnspecified
		{
			get
			{
				return this._HasReportedUnspecified;
			}
			set
			{
				if ((this._HasReportedUnspecified != value))
				{
					this._HasReportedUnspecified = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.WASTETRANSFER_RECEIVINGCOUNTRY")]
	public partial class WASTETRANSFER_RECEIVINGCOUNTRY
	{
		
		private int _FacilityReportID;
		
		private string _FacilityName;
		
		private int _FacilityID;
		
		private int _ReportingYear;
		
		private System.Nullable<double> _QuantityRecovery;
		
		private System.Nullable<double> _QuantityDisposal;
		
		private System.Nullable<double> _QuantityUnspec;
		
		private System.Nullable<double> _QuantityTotal;
		
		private string _ReceivingCountryCode;
		
		private string _UnitCode;
		
		private System.Nullable<int> _LOV_ConfidentialityID;
		
		private string _CountryCode;
		
		private int _LOV_CountryID;
		
		private string _RiverBasinDistrictCode;
		
		private int _LOV_RiverBasinDistrictID;
		
		private string _NUTSLevel2RegionCode;
		
		private System.Nullable<int> _LOV_NUTSRLevel1ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel2ID;
		
		private System.Nullable<int> _LOV_NUTSRLevel3ID;
		
		private string _IASectorCode;
		
		private string _IAActivityCode;
		
		private string _IASubActivityCode;
		
		private string _IPPCSectorCode;
		
		private string _IPPCActivityCode;
		
		private string _IPPCSubActivityCode;
		
		private System.Nullable<int> _LOV_IASectorID;
		
		private System.Nullable<int> _LOV_IAActivityID;
		
		private System.Nullable<int> _LOV_IASubActivityID;
		
		private string _NACESectorCode;
		
		private string _NACEActivityCode;
		
		private string _NACESubActivityCode;
		
		private System.Nullable<int> _LOV_NACESectorID;
		
		private System.Nullable<int> _LOV_NACEActivityID;
		
		private System.Nullable<int> _LOV_NACESubActivityID;
		
		private bool _HasReportedRecovery;
		
		private bool _HasReportedDisposal;
		
		private bool _HasReportedUnspecified;
		
		private bool _ConfidentialIndicator;
		
		private bool _ConfidentialIndicatorFacility;
		
		public WASTETRANSFER_RECEIVINGCOUNTRY()
		{
		}
		
		[Column(Storage="_FacilityReportID", DbType="Int NOT NULL")]
		public int FacilityReportID
		{
			get
			{
				return this._FacilityReportID;
			}
			set
			{
				if ((this._FacilityReportID != value))
				{
					this._FacilityReportID = value;
				}
			}
		}
		
		[Column(Storage="_FacilityName", DbType="NVarChar(255)")]
		public string FacilityName
		{
			get
			{
				return this._FacilityName;
			}
			set
			{
				if ((this._FacilityName != value))
				{
					this._FacilityName = value;
				}
			}
		}
		
		[Column(Storage="_FacilityID", DbType="Int NOT NULL")]
		public int FacilityID
		{
			get
			{
				return this._FacilityID;
			}
			set
			{
				if ((this._FacilityID != value))
				{
					this._FacilityID = value;
				}
			}
		}
		
		[Column(Storage="_ReportingYear", DbType="Int NOT NULL")]
		public int ReportingYear
		{
			get
			{
				return this._ReportingYear;
			}
			set
			{
				if ((this._ReportingYear != value))
				{
					this._ReportingYear = value;
				}
			}
		}
		
		[Column(Storage="_QuantityRecovery", DbType="Float")]
		public System.Nullable<double> QuantityRecovery
		{
			get
			{
				return this._QuantityRecovery;
			}
			set
			{
				if ((this._QuantityRecovery != value))
				{
					this._QuantityRecovery = value;
				}
			}
		}
		
		[Column(Storage="_QuantityDisposal", DbType="Float")]
		public System.Nullable<double> QuantityDisposal
		{
			get
			{
				return this._QuantityDisposal;
			}
			set
			{
				if ((this._QuantityDisposal != value))
				{
					this._QuantityDisposal = value;
				}
			}
		}
		
		[Column(Storage="_QuantityUnspec", DbType="Float")]
		public System.Nullable<double> QuantityUnspec
		{
			get
			{
				return this._QuantityUnspec;
			}
			set
			{
				if ((this._QuantityUnspec != value))
				{
					this._QuantityUnspec = value;
				}
			}
		}
		
		[Column(Storage="_QuantityTotal", DbType="Float")]
		public System.Nullable<double> QuantityTotal
		{
			get
			{
				return this._QuantityTotal;
			}
			set
			{
				if ((this._QuantityTotal != value))
				{
					this._QuantityTotal = value;
				}
			}
		}
		
		[Column(Storage="_ReceivingCountryCode", DbType="NVarChar(255)")]
		public string ReceivingCountryCode
		{
			get
			{
				return this._ReceivingCountryCode;
			}
			set
			{
				if ((this._ReceivingCountryCode != value))
				{
					this._ReceivingCountryCode = value;
				}
			}
		}
		
		[Column(Storage="_UnitCode", DbType="NVarChar(255)")]
		public string UnitCode
		{
			get
			{
				return this._UnitCode;
			}
			set
			{
				if ((this._UnitCode != value))
				{
					this._UnitCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_ConfidentialityID", DbType="Int")]
		public System.Nullable<int> LOV_ConfidentialityID
		{
			get
			{
				return this._LOV_ConfidentialityID;
			}
			set
			{
				if ((this._LOV_ConfidentialityID != value))
				{
					this._LOV_ConfidentialityID = value;
				}
			}
		}
		
		[Column(Storage="_CountryCode", DbType="NVarChar(255)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_CountryID", DbType="Int NOT NULL")]
		public int LOV_CountryID
		{
			get
			{
				return this._LOV_CountryID;
			}
			set
			{
				if ((this._LOV_CountryID != value))
				{
					this._LOV_CountryID = value;
				}
			}
		}
		
		[Column(Storage="_RiverBasinDistrictCode", DbType="NVarChar(255)")]
		public string RiverBasinDistrictCode
		{
			get
			{
				return this._RiverBasinDistrictCode;
			}
			set
			{
				if ((this._RiverBasinDistrictCode != value))
				{
					this._RiverBasinDistrictCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_RiverBasinDistrictID", DbType="Int NOT NULL")]
		public int LOV_RiverBasinDistrictID
		{
			get
			{
				return this._LOV_RiverBasinDistrictID;
			}
			set
			{
				if ((this._LOV_RiverBasinDistrictID != value))
				{
					this._LOV_RiverBasinDistrictID = value;
				}
			}
		}
		
		[Column(Storage="_NUTSLevel2RegionCode", DbType="NVarChar(255)")]
		public string NUTSLevel2RegionCode
		{
			get
			{
				return this._NUTSLevel2RegionCode;
			}
			set
			{
				if ((this._NUTSLevel2RegionCode != value))
				{
					this._NUTSLevel2RegionCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel1ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel1ID
		{
			get
			{
				return this._LOV_NUTSRLevel1ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel1ID != value))
				{
					this._LOV_NUTSRLevel1ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel2ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel2ID
		{
			get
			{
				return this._LOV_NUTSRLevel2ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel2ID != value))
				{
					this._LOV_NUTSRLevel2ID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NUTSRLevel3ID", DbType="Int")]
		public System.Nullable<int> LOV_NUTSRLevel3ID
		{
			get
			{
				return this._LOV_NUTSRLevel3ID;
			}
			set
			{
				if ((this._LOV_NUTSRLevel3ID != value))
				{
					this._LOV_NUTSRLevel3ID = value;
				}
			}
		}
		
		[Column(Storage="_IASectorCode", DbType="NVarChar(255)")]
		public string IASectorCode
		{
			get
			{
				return this._IASectorCode;
			}
			set
			{
				if ((this._IASectorCode != value))
				{
					this._IASectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IAActivityCode", DbType="NVarChar(255)")]
		public string IAActivityCode
		{
			get
			{
				return this._IAActivityCode;
			}
			set
			{
				if ((this._IAActivityCode != value))
				{
					this._IAActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IASubActivityCode", DbType="NVarChar(255)")]
		public string IASubActivityCode
		{
			get
			{
				return this._IASubActivityCode;
			}
			set
			{
				if ((this._IASubActivityCode != value))
				{
					this._IASubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSectorCode", DbType="NVarChar(255)")]
		public string IPPCSectorCode
		{
			get
			{
				return this._IPPCSectorCode;
			}
			set
			{
				if ((this._IPPCSectorCode != value))
				{
					this._IPPCSectorCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCActivityCode", DbType="NVarChar(255)")]
		public string IPPCActivityCode
		{
			get
			{
				return this._IPPCActivityCode;
			}
			set
			{
				if ((this._IPPCActivityCode != value))
				{
					this._IPPCActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_IPPCSubActivityCode", DbType="NVarChar(255)")]
		public string IPPCSubActivityCode
		{
			get
			{
				return this._IPPCSubActivityCode;
			}
			set
			{
				if ((this._IPPCSubActivityCode != value))
				{
					this._IPPCSubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASectorID", DbType="Int")]
		public System.Nullable<int> LOV_IASectorID
		{
			get
			{
				return this._LOV_IASectorID;
			}
			set
			{
				if ((this._LOV_IASectorID != value))
				{
					this._LOV_IASectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IAActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IAActivityID
		{
			get
			{
				return this._LOV_IAActivityID;
			}
			set
			{
				if ((this._LOV_IAActivityID != value))
				{
					this._LOV_IAActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_IASubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_IASubActivityID
		{
			get
			{
				return this._LOV_IASubActivityID;
			}
			set
			{
				if ((this._LOV_IASubActivityID != value))
				{
					this._LOV_IASubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_NACESectorCode", DbType="NVarChar(255)")]
		public string NACESectorCode
		{
			get
			{
				return this._NACESectorCode;
			}
			set
			{
				if ((this._NACESectorCode != value))
				{
					this._NACESectorCode = value;
				}
			}
		}
		
		[Column(Storage="_NACEActivityCode", DbType="NVarChar(255)")]
		public string NACEActivityCode
		{
			get
			{
				return this._NACEActivityCode;
			}
			set
			{
				if ((this._NACEActivityCode != value))
				{
					this._NACEActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_NACESubActivityCode", DbType="NVarChar(255)")]
		public string NACESubActivityCode
		{
			get
			{
				return this._NACESubActivityCode;
			}
			set
			{
				if ((this._NACESubActivityCode != value))
				{
					this._NACESubActivityCode = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESectorID", DbType="Int")]
		public System.Nullable<int> LOV_NACESectorID
		{
			get
			{
				return this._LOV_NACESectorID;
			}
			set
			{
				if ((this._LOV_NACESectorID != value))
				{
					this._LOV_NACESectorID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACEActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACEActivityID
		{
			get
			{
				return this._LOV_NACEActivityID;
			}
			set
			{
				if ((this._LOV_NACEActivityID != value))
				{
					this._LOV_NACEActivityID = value;
				}
			}
		}
		
		[Column(Storage="_LOV_NACESubActivityID", DbType="Int")]
		public System.Nullable<int> LOV_NACESubActivityID
		{
			get
			{
				return this._LOV_NACESubActivityID;
			}
			set
			{
				if ((this._LOV_NACESubActivityID != value))
				{
					this._LOV_NACESubActivityID = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedRecovery", DbType="Bit NOT NULL")]
		public bool HasReportedRecovery
		{
			get
			{
				return this._HasReportedRecovery;
			}
			set
			{
				if ((this._HasReportedRecovery != value))
				{
					this._HasReportedRecovery = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedDisposal", DbType="Bit NOT NULL")]
		public bool HasReportedDisposal
		{
			get
			{
				return this._HasReportedDisposal;
			}
			set
			{
				if ((this._HasReportedDisposal != value))
				{
					this._HasReportedDisposal = value;
				}
			}
		}
		
		[Column(Storage="_HasReportedUnspecified", DbType="Bit NOT NULL")]
		public bool HasReportedUnspecified
		{
			get
			{
				return this._HasReportedUnspecified;
			}
			set
			{
				if ((this._HasReportedUnspecified != value))
				{
					this._HasReportedUnspecified = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicator", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicator
		{
			get
			{
				return this._ConfidentialIndicator;
			}
			set
			{
				if ((this._ConfidentialIndicator != value))
				{
					this._ConfidentialIndicator = value;
				}
			}
		}
		
		[Column(Storage="_ConfidentialIndicatorFacility", DbType="Bit NOT NULL")]
		public bool ConfidentialIndicatorFacility
		{
			get
			{
				return this._ConfidentialIndicatorFacility;
			}
			set
			{
				if ((this._ConfidentialIndicatorFacility != value))
				{
					this._ConfidentialIndicatorFacility = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
