#!/bin/sh
CP="../java/GenerateRDF:../java/GenerateRDF/jtds-1.2.5.jar"
#java -cp $CP GenerateRDF sectors >sectors.rdf
#java -cp $CP GenerateRDF emissions >emissions.rdf
java -cp $CP GenerateRDF sectors notations emissions |gzip >lrtap.rdf.gz
scp lrtap.rdf.gz root@koala:/var/local/rdfdata/htdocs/
