insert into Common_OtherGasesType values ('Blast furnace gas');
insert into Common_OtherGasesType values ('Products of gasification');
insert into Common_OtherGasesType values ('Other');

insert into Common_OtherSolidFuels values ('Peat');
insert into Common_OtherSolidFuels values ('Lignite');
insert into Common_OtherSolidFuels values ('Sub-bituminous coal');
insert into Common_OtherSolidFuels values ('Bituminous coal');
insert into Common_OtherSolidFuels values ('Anthracite');
insert into Common_OtherSolidFuels values ('Other');

insert into Common_MethodBasisCodeType values ('C - Calculated');
insert into Common_MethodBasisCodeType values ('E - Estimated');
insert into Common_MethodBasisCodeType values ('M - Measured');

insert into Common_MethodTypeCodeType values ('ALT - Alternative measurement methodology in accordance with existing CEN/ISO measurements standards');
insert into Common_MethodTypeCodeType values ('CEN/ISO - Internationally approved measurement standard');
insert into Common_MethodTypeCodeType values ('CRM - Measurement methodology for the performance of which is demonstrated by means of certified reference materials and accepted by competent authority.');
insert into Common_MethodTypeCodeType values ('ETS - Guidelines for the monitoring and reporting of greenhouse gas emissions under the Emission Trading Scheme');
insert into Common_MethodTypeCodeType values ('IPCC - IPCC Guidelines');
insert into Common_MethodTypeCodeType values ('MAB - Mass balance method which is accepted by the competent authority');
insert into Common_MethodTypeCodeType values ('NRB - National or regional binding measurement/calculation methodology prescribed by legal act for the pollutant and facility concerned');
insert into Common_MethodTypeCodeType values ('OTH - Other measurement/calculation methodology');
insert into Common_MethodTypeCodeType values ('PER - Measurement/Calculation Methodology already prescribed by the competent authority in a licence or an operating permit for the facility');
insert into Common_MethodTypeCodeType values ('SSC - European-wide sector specific calculation method');
insert into Common_MethodTypeCodeType values ('UNECE/EMEP - UNECE/EMEP EMEP/CORINAIR Emission Inventory Guidebook');
insert into Common_MethodTypeCodeType values ('WEIGH - Weighing');

insert into Common_StatusOfThePlantType values ('Art 30(2) - existing plants under IED');
insert into Common_StatusOfThePlantType values ('Art 30(3) - new plants under IED');

insert into Common_CombustionType values ('Boiler');
insert into Common_CombustionType values ('DieselEngine');
insert into Common_CombustionType values ('GasEngine');
insert into Common_CombustionType values ('GasTurbine');
insert into Common_CombustionType values ('Others');

insert into Common_EnergyInputType values ('Biomass');
insert into Common_EnergyInputType values ('HardCoal');
insert into Common_EnergyInputType values ('Lignite');
insert into Common_EnergyInputType values ('LiquidFuels');
insert into Common_EnergyInputType values ('NaturalGas');
insert into Common_EnergyInputType values ('Peat');
insert into Common_EnergyInputType values ('OtherGases');
insert into Common_EnergyInputType values ('OtherSolidFuels');

insert into Common_ConfidentialCodeType values ('A42a - Article 4(2)(a) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42b - Article 4(2)(b) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42c - Article 4(2)(c) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42d - Article 4(2)(d) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42e - Article 4(2)(e) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42f - Article 4(2)(f) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42g - Article 4(2)(g) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType values ('A42h - Article 4(2)(h) of Directive 2003/4/EC');

insert into Common_WasteTypeCodeType values ('HW - Hazardous waste');
insert into Common_WasteTypeCodeType values ('HWIC - Hazardous waste within country');
insert into Common_WasteTypeCodeType values ('HWOC - Harzodous waste outside country');
insert into Common_WasteTypeCodeType values ('NON-HW - Non-hazardous waste');

insert into Common_WasteTreatmentCodeType values ('D - Destined for disposal');
insert into Common_WasteTreatmentCodeType values ('R - Destined for recovery');

insert into Common_PollutantType values ('GRHGAS');
insert into Common_PollutantType values ('CH4');
insert into Common_PollutantType values ('CO');
insert into Common_PollutantType values ('CO2 EXCL BIOMASS');
insert into Common_PollutantType values ('HCFCS');
insert into Common_PollutantType values ('N2O');
insert into Common_PollutantType values ('PFCS');
insert into Common_PollutantType values ('SF6');
insert into Common_PollutantType values ('OTHGAS');
insert into Common_PollutantType values ('CO');
insert into Common_PollutantType values ('NH3');
insert into Common_PollutantType values ('NMVOC');
insert into Common_PollutantType values ('NOX');
insert into Common_PollutantType values ('SOX');
insert into Common_PollutantType values ('H');
insert into Common_PollutantType values ('HALOGENATED ORGANIC COMPOUNDS');
insert into Common_PollutantType values ('HALONS');
insert into Common_PollutantType values ('HCN');
insert into Common_PollutantType values ('HEPTACHLOR');
insert into Common_PollutantType values ('HEVMET');
insert into Common_PollutantType values ('HEXABROMOBIPHENYL');
insert into Common_PollutantType values ('HEXACHLOROBENZENE (HCB)');
insert into Common_PollutantType values ('HEXACHLOROBUTADIENE (HCBD)');
insert into Common_PollutantType values ('CR AND COMPOUNDS');
insert into Common_PollutantType values ('HEXACHLOROCYCLOHEXANE(HCH)');
insert into Common_PollutantType values ('CU AND COMPOUNDS');
insert into Common_PollutantType values ('HFCS');
insert into Common_PollutantType values ('CYANIDES');
insert into Common_PollutantType values ('HG AND COMPOUNDS');
insert into Common_PollutantType values ('DDT');
insert into Common_PollutantType values ('I)PERYLENE');
insert into Common_PollutantType values ('DEHP');
insert into Common_PollutantType values ('INORG');
insert into Common_PollutantType values ('DICHLOROETHANE (DCE)');
insert into Common_PollutantType values ('ISODRIN');
insert into Common_PollutantType values ('DICHLOROMETHANE (DCM)');
insert into Common_PollutantType values ('ISOPROTURON');
insert into Common_PollutantType values ('DIELDRIN');
insert into Common_PollutantType values ('LINDANE');
insert into Common_PollutantType values ('DIURON');
insert into Common_PollutantType values ('MIREX');
insert into Common_PollutantType values ('ENDOSULPHAN');
insert into Common_PollutantType values ('NAPHTHALENE');
insert into Common_PollutantType values ('ENDRIN');
insert into Common_PollutantType values ('NI AND COMPOUNDS');
insert into Common_PollutantType values ('ETHYLBENZENE');
insert into Common_PollutantType values ('NP/NPES');
insert into Common_PollutantType values ('ETHYLENE OXIDE');
insert into Common_PollutantType values ('OCTYLPHENOLS AND OCTYLPHENOL ETHOXYLATES');
insert into Common_PollutantType values ('FLUORANTHENE');
insert into Common_PollutantType values ('ORGANOTIN - COMPOUNDS');
insert into Common_PollutantType values ('FLUORIDES');
insert into Common_PollutantType values ('OTHORG');
insert into Common_PollutantType values ('FLUORINE AND INORGANIC COMPOUNDS');
insert into Common_PollutantType values ('PB AND COMPOUNDS');
insert into Common_PollutantType values ('PCDD+PCDF (DIOXINS+FURANS)');
insert into Common_PollutantType values ('PENTACHLOROBENZENE');
insert into Common_PollutantType values ('PENTACHLOROPHENOL (PCP)');
insert into Common_PollutantType values ('PEST');
insert into Common_PollutantType values ('PHENOLS');
insert into Common_PollutantType values ('PM10');
insert into Common_PollutantType values ('POLYCHLORINATED BIPHENYLS (PCBS)');
insert into Common_PollutantType values ('POLYCYCLIC AROMATIC HYDROCARBONS');
insert into Common_PollutantType values ('SIMAZINE');
insert into Common_PollutantType values ('TETRACHLOROETHANE');
insert into Common_PollutantType values ('TETRACHLOROETHYLENE (PER)');
insert into Common_PollutantType values ('TETRACHLOROMETHANE (TCM)');
insert into Common_PollutantType values ('TOLUENE');
insert into Common_PollutantType values ('TOTAL NITROGEN');
insert into Common_PollutantType values ('TOTAL ORGANIC CARBON (TOC)');
insert into Common_PollutantType values ('TOTAL PHOSPHORUS');
insert into Common_PollutantType values ('TOXAPHENE');
insert into Common_PollutantType values ('TRIBUTYLTIN AND COMPOUNDS');
insert into Common_PollutantType values ('TRICHLOROBENZENES (TCB)');
insert into Common_PollutantType values ('TRICHLOROETHANE (TCE)');
insert into Common_PollutantType values ('TRICHLOROETHYLENE (TRI)');
insert into Common_PollutantType values ('TRICHLOROMETHANE');
insert into Common_PollutantType values ('TRIFLURALIN');
insert into Common_PollutantType values ('TRIPHENYLTIN AND COMPOUNDS');
insert into Common_PollutantType values ('VINYL CHLORIDE');
insert into Common_PollutantType values ('XYLENES');
insert into Common_PollutantType values ('ZN AND COMPOUNDS');
insert into Common_PollutantType values ('ALACHLOR');
insert into Common_PollutantType values ('ALDRIN');
insert into Common_PollutantType values ('ANTHRACENE');
insert into Common_PollutantType values ('AS AND COMPOUNDS');
insert into Common_PollutantType values ('ASBESTOS');
insert into Common_PollutantType values ('ATRAZINE');
insert into Common_PollutantType values ('BENZENE');
insert into Common_PollutantType values ('BENZO(G');
insert into Common_PollutantType values ('BROMINATED DIPHENYLETHER');
insert into Common_PollutantType values ('CD AND COMPOUNDS');
insert into Common_PollutantType values ('CFCS');
insert into Common_PollutantType values ('CHLORDECONE');
insert into Common_PollutantType values ('CHLORFENVINPHOS');
insert into Common_PollutantType values ('CHLORG');
insert into Common_PollutantType values ('CHLORIDES');
insert into Common_PollutantType values ('CHLORINE AND INORGANIC COMPOUNDS');
insert into Common_PollutantType values ('CHLORO-ALKANES (C10-13)');
insert into Common_PollutantType values ('CHLORPYRIFOS');
insert into Common_PollutantType values ('CLORDANE');

insert into Common_UnitCodeType values ('A90 - gigawatt');
insert into Common_UnitCodeType values ('GV - gigajoule');
insert into Common_UnitCodeType values ('GWH - gigawatt hour');
insert into Common_UnitCodeType values ('HLT - hectolitre');
insert into Common_UnitCodeType values ('KGM - kilogram');
insert into Common_UnitCodeType values ('KWH - kilowatt hour');
insert into Common_UnitCodeType values ('KWT - kilowatt');
insert into Common_UnitCodeType values ('LTR - litre');
insert into Common_UnitCodeType values ('MAW - megawatt');
insert into Common_UnitCodeType values ('MTK - square metre');
insert into Common_UnitCodeType values ('MTQ - cubic metre');
insert into Common_UnitCodeType values ('MWH - megawatt hour');
insert into Common_UnitCodeType values ('PCS - pieces');
insert into Common_UnitCodeType values ('TNE - tonne (metric ton)');

insert into Common_MonthType values ('January');
insert into Common_MonthType values ('February');
insert into Common_MonthType values ('March');
insert into Common_MonthType values ('April');
insert into Common_MonthType values ('May');
insert into Common_MonthType values ('June');
insert into Common_MonthType values ('July');
insert into Common_MonthType values ('August');
insert into Common_MonthType values ('September');
insert into Common_MonthType values ('October');
insert into Common_MonthType values ('November');
insert into Common_MonthType values ('December');

insert into Common_CountryCodeType values ('AT - Austria');
insert into Common_CountryCodeType values ('BE - Belgium');
insert into Common_CountryCodeType values ('BG - Bulgaria');
insert into Common_CountryCodeType values ('CH - Switzerland');
insert into Common_CountryCodeType values ('CY - Cyprus');
insert into Common_CountryCodeType values ('CZ - Czech Republic');
insert into Common_CountryCodeType values ('DE - Germany');
insert into Common_CountryCodeType values ('DK - Denmark');
insert into Common_CountryCodeType values ('EE - Estonia');
insert into Common_CountryCodeType values ('EL - Greece');
insert into Common_CountryCodeType values ('ES - Spain');
insert into Common_CountryCodeType values ('FI - Finland');
insert into Common_CountryCodeType values ('FR - France');
insert into Common_CountryCodeType values ('HR - Croatia');
insert into Common_CountryCodeType values ('GB - United Kingdom');
insert into Common_CountryCodeType values ('HU - Hungary');
insert into Common_CountryCodeType values ('IE - Ireland');
insert into Common_CountryCodeType values ('IS - Iceland');
insert into Common_CountryCodeType values ('IT - Italy');
insert into Common_CountryCodeType values ('LT - Lithuania');
insert into Common_CountryCodeType values ('LU - Luxembourg');
insert into Common_CountryCodeType values ('LV - Latvia');
insert into Common_CountryCodeType values ('MT - Malta');
insert into Common_CountryCodeType values ('NL - Netherlands');
insert into Common_CountryCodeType values ('NO - Norway');
insert into Common_CountryCodeType values ('PL - Poland');
insert into Common_CountryCodeType values ('PT - Portugal');
insert into Common_CountryCodeType values ('RO - Romania');
insert into Common_CountryCodeType values ('RS - Serbia');
insert into Common_CountryCodeType values ('SE - Sweden');
insert into Common_CountryCodeType values ('SI - Slovenia');
insert into Common_CountryCodeType values ('SK - Slovakia');

insert into Common_TotalEmissionsToAirType values ('Dust');
insert into Common_TotalEmissionsToAirType values ('NOx');
insert into Common_TotalEmissionsToAirType values ('SO2');

insert into Common_MediumCodeType values ('AIR');
insert into Common_MediumCodeType values ('LAND');
insert into Common_MediumCodeType values ('WATER');