/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-dic-2015 11:20:38 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [dbo].[WasteTransfer]
(
	[wasteTypeCode] int NULL,    -- Required. Identifies the type of waste (non-hazardous, hazardous, hazardous within country and hazardous outside country).
	[wasteTreatmentCode] int NULL,    -- Conditional. Identifies the waste treatment operation (recovery or disposal)
	[quantity] float NULL,    -- Conditional. Quantity [t/year] Must be reported with 3 significant digits.
	[methodBasisCode] int NULL,    -- Conditional. Identifies the basis of the main method used (M/C/E).
	[methodUsed] int NULL,    -- Conditional. Identifies the calculation and measurement method(s) used for determination of the quantity
	[confidentialIndicator] bit NULL,    -- Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     
	[confidentialCode] int NULL,    -- Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).
	[remarkText] nvarchar(1000) NULL,    -- Textual remark, e.g. elaboration on the reason for confidentiality.
	[wasteTransferID] int NOT NULL IDENTITY (1, 1),
	[facilityReportID] int NULL
)
GO

CREATE TABLE [dbo].[WasteHandlerParty]
(
	[name] nvarchar(255) NULL,    -- Conditional. Name of recoverer/disposer. Required unless confidentiality is claimed for the WasteTransfer element
	[address] int NULL,    -- Conditional. The address of the recoverer/disposer. Required unless confidentiality is claimed for the WasteTransfer.
	[siteAddress] int NULL,    -- Conditional. The address of the actual recoverer/disposer site. 
	[wasteHandlerPartyID] int NOT NULL IDENTITY (1, 1),
	[wasteTransferID] int NULL
)
GO

CREATE TABLE [dbo].[TotalEmissionsToAir]
(
	[type] int NULL,    -- Required.
	[quantity] float NULL,    -- Required.
	[totalEmissionsToAirID] int NOT NULL IDENTITY (1, 1),
	[plantReportID] int NOT NULL
)
GO

CREATE TABLE [dbo].[SO2]
(
	[month] int NULL,
	[quantity] float NULL,
	[sO2ID] int NOT NULL IDENTITY (1, 1),
	[iEDArt72ID] int NULL
)
GO

CREATE TABLE [dbo].[Report]
(
	[countryID] int NULL,    -- Required. The Member State reporting. The list of legal values identifying the countries correspond to ISO 3166 alpha-2 except for Greece and the United Kingdom as recommended in http://publications.europa.eu/code/pdf/370000en.htm#pays, Revision 8. 
	[remarkText] nvarchar(1000) NULL,    -- Textual remark from MS. 
	[reportingYear] smallint NULL,    -- Required. The calendar year for which data is gathered. Must be in the interval [2006; this year].
	[reportID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[QuantityType]
(
	[Quantity] float NULL,
	[UnitCode] int NULL,
	[quantityTypeID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[ProductionVolume]
(
	[productName] nvarchar(255) NULL,    -- Required. The product/product group.
	[quantity] int NULL,    -- Required. The total volume. The unit must be given in attribute unitCode.
	[productionVolumeID] int NOT NULL IDENTITY (1, 1),
	[facilityReportID] int NULL
)
GO

CREATE TABLE [dbo].[PollutantTransfer]
(
	[pollutantCode] int NULL,    -- Required. Identifies the pollutant (or the pollutant group if confidentiality is claimed)
	[methodBasisCode] int NULL,    -- Required. Identifies the basis of the main method used (M/C/E).
	[methodUsed] int NULL,    -- Conditional. Identifies the calculation and measurement method(s) used for determination of the quantity.
	[quantity] float NULL,    -- Required. Total quantity [kg/year]. Must be reported with 3 significant digits. Values below threshold are considered voluntary and will not be published.
	[confidentialIndicator] bit NULL,    -- Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     
	[confidentialCode] int NULL,    -- Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).
	[remarkText] nvarchar(1000) NULL,    -- Textual remark, e.g. elaboration on the reason for confidentiality.
	[pollutantTransferID] int NOT NULL IDENTITY (1, 1),
	[facilityReportID] int NULL
)
GO

CREATE TABLE [dbo].[PollutantRelease]
(
	[mediumCode] int NULL,    -- Required. Identifies the environmental medium (air, water, land). 
	[pollutantCode] int NULL,    -- Required. Identifies the pollutant (or the pollutant group if confidentiality is claimed) Notice that if confidentiality is claimed the pollutant group must be reported.
	[methodBasisCode] int NULL,    -- Required. Identifies the basis of the main method used (M/C/E)
	[methodUsed] int NULL,    -- Conditional. Identifies the calculation and measurement method(s) used for determination of the total quantity.
	[totalQuantity] float NULL,    -- Required. Total quantity including accidental quantity [kg/year]. Values below threshold are considered voluntary and will not be published. Must be reported with 3 significant digits
	[accidentalQuantity] float NULL,    -- Required. Accidental quantity [kg/year] Must be reported with 3 significant digits.
	[confidentialIndicator] bit NULL,    -- Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     
	[confidentialCode] int NULL,    -- Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).
	[remarkText] nvarchar(1000) NULL,    -- Textual remark, e.g. elaboration on the reason for confidentiality.
	[pollutantReleaseID] int NOT NULL IDENTITY (1, 1),
	[facilityReportID] int NULL
)
GO

CREATE TABLE [dbo].[PlantType]
(
	[combustionPlantType] int NULL,    -- Required.
	[thermalInput] int NULL,    -- Required.
	[plantTypeID] int NOT NULL IDENTITY (1, 1),
	[plantReportID] int NOT NULL
)
GO

CREATE TABLE [dbo].[PlantReports]
(
	[plantReportsID] int NOT NULL IDENTITY (1, 1),
	[reportID] int NOT NULL
)
GO

CREATE TABLE [dbo].[PlantReport]
(
	[dBPlantId] nvarchar(255) NULL,    -- Required.
	[statusOfThePlant] int NULL,    -- Required.
	[mWth] int NULL,    -- Required.
	[extensionBy50MWOrMore] bit NULL,    -- Required.
	[capacityAddedMW] int NULL,    -- Required.
	[substantialChange] bit NULL,    -- Required.
	[capacityAffectedMW] int NULL,    -- Required.
	[dateOfStartOperation] date NULL,    -- Required.
	[refineries] bit NULL,    -- Required.
	[operationHours] float NULL,    -- Required.
	[remarkText] nvarchar(1000) NULL,
	[plantReportID] int NOT NULL IDENTITY (1, 1),
	[plantReportsID] int NULL
)
GO

CREATE TABLE [dbo].[MethodUsedType]
(
	[MethodTypeCode] int NULL,    -- Identifies the type of method used (CEN/ISO, ETS, etc.). Notice that the method type “WEIGH” (i.e. weighing) only is allowed for waste transfer.
	[Designation] nvarchar(255) NULL,    -- A short designation or description of the method used. Required for some method types as indicated in the list of legal method type codes.
	[methodUsedTypeID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[LCPDerogations]
(
	[art32TNP] bit NULL,    -- Required.
	[art33LLD] bit NULL,    -- Required.
	[art34SIS] bit NULL,    -- Required.
	[art35DHP] bit NULL,    -- Required.
	[usefulHeatProductionRollingAverage5Years] float NULL,    -- Required.
	[lCPDerogationsID] int NOT NULL IDENTITY (1, 1),
	[plantReportID] int NULL
)
GO

CREATE TABLE [dbo].[IEDArt72]
(
	[iEDArt72_4a] bit NULL,
	[iEDArt72_4b] bit NULL,
	[remarkText] nvarchar(1000) NULL,
	[iEDArt72ID] int NOT NULL IDENTITY (1, 1),
	[plantReportID] int NULL
)
GO

CREATE TABLE [dbo].[FacilityReports]
(
	[facilityReportsID] int NOT NULL IDENTITY (1, 1),
	[reportID] int NOT NULL
)
GO

CREATE TABLE [dbo].[FacilityReport]
(
	[dBFacitilyID] nvarchar(255) NULL,    -- Required.
	[operationHours] int NULL,    -- The number of operating hours in reporting year.
	[protectVoluntaryData] bit NULL,    -- Required . Indicates if voluntary data should be protected or not. In this case all voluntary data of the facility is considered protected with a few exceptions at stated in the descriptions of the individual elements. true marks protection, false marks no protection.
	[publicInformation] nvarchar(1000) NULL,    -- Textual information. Additional information to be published on web site as-is (e.g. e-mail, contact person etc.).
	[totalEmployeeQuantity] int NULL,    -- The number of employees.                   
	[confidentialIndicator] bit NULL,    -- Required. Indicates if confidentiality for mandatory data is claimed or not. true marks confidentiality, false marks no confidentiality.                     
	[confidentialCode] int NULL,    -- Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).
	[remarkText] nvarchar(1000) NULL,    -- Textual remark, e.g. information in changes of the history of the facility, elaboration on the reason for confidentiality etc.
	[facilityReportID] int NOT NULL IDENTITY (1, 1),
	[facilityReportsID] int NULL
)
GO

CREATE TABLE [dbo].[EnergyInput]
(
	[type] int NULL,    -- Required.
	[otherGases] int NULL,    -- Conditional.
	[otherSolidFuels] int NULL,    -- Conditional.
	[quantity] float NULL,    -- Required.
	[energyInputID] int NOT NULL IDENTITY (1, 1),
	[plantReportID] int NOT NULL
)
GO

CREATE TABLE [dbo].[DesulphurisationRate]
(
	[month] int NULL,
	[quantity] float NULL,
	[desulphurisationRateID] int NOT NULL IDENTITY (1, 1),
	[iEDArt72ID] int NULL
)
GO

CREATE TABLE [dbo].[Common_WasteTypeCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_WasteTreatmentCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_UnitCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_TotalEmissionsToAirType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_StatusOfThePlantType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_PollutantType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_OtherSolidFuels]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_OtherGasesType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_MonthType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_MethodTypeCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_MethodBasisCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_MediumCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_EnergyInputType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_CountryCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_ConfidentialCodeType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[Common_CombustionType]
(
	[value] nvarchar(255) NULL,
	[id] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [dbo].[AddressType]
(
	[StreetName] nvarchar(255) NULL,    -- The name, expressed as text, of a street in the address.
	[BuildingNumber] nvarchar(255) NULL,    -- The building number, expressed as text, in the address.
	[City] nvarchar(255) NULL,    -- The name, expressed as text, of the city, town or village in the address.
	[PostalCode] nvarchar(255) NULL,    -- The postcode, expressed as text, if the address.
	[CountryID] nvarchar(255) NULL,    -- The unique identifier of a country in the structured address (Reference ISO 3166 and UN/ECE Rec 3).
	[addressTypeID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[WasteTransfer] 
 ADD CONSTRAINT [PK_WasteTransfer]
	PRIMARY KEY CLUSTERED ([wasteTransferID])
GO

ALTER TABLE [dbo].[WasteHandlerParty] 
 ADD CONSTRAINT [PK_WasteHandlerParty]
	PRIMARY KEY CLUSTERED ([wasteHandlerPartyID])
GO

ALTER TABLE [dbo].[TotalEmissionsToAir] 
 ADD CONSTRAINT [PK_TotalEmissionsToAir]
	PRIMARY KEY CLUSTERED ([totalEmissionsToAirID])
GO

ALTER TABLE [dbo].[SO2] 
 ADD CONSTRAINT [PK_SO2]
	PRIMARY KEY CLUSTERED ([sO2ID])
GO

ALTER TABLE [dbo].[Report] 
 ADD CONSTRAINT [PK_Report]
	PRIMARY KEY CLUSTERED ([reportID])
GO

ALTER TABLE [dbo].[QuantityType] 
 ADD CONSTRAINT [PK_QuantityType]
	PRIMARY KEY CLUSTERED ([quantityTypeID])
GO

ALTER TABLE [dbo].[ProductionVolume] 
 ADD CONSTRAINT [PK_ProductionVolume]
	PRIMARY KEY CLUSTERED ([productionVolumeID])
GO

ALTER TABLE [dbo].[PollutantTransfer] 
 ADD CONSTRAINT [PK_PollutantTransfer]
	PRIMARY KEY CLUSTERED ([pollutantTransferID])
GO

ALTER TABLE [dbo].[PollutantRelease] 
 ADD CONSTRAINT [PK_PollutantRelease]
	PRIMARY KEY CLUSTERED ([pollutantReleaseID])
GO

ALTER TABLE [dbo].[PlantType] 
 ADD CONSTRAINT [PK_PlantType]
	PRIMARY KEY CLUSTERED ([plantTypeID])
GO

ALTER TABLE [dbo].[PlantReports] 
 ADD CONSTRAINT [PK_PlantReports]
	PRIMARY KEY CLUSTERED ([plantReportsID])
GO

ALTER TABLE [dbo].[PlantReport] 
 ADD CONSTRAINT [PK_PlantReport]
	PRIMARY KEY CLUSTERED ([plantReportID])
GO

ALTER TABLE [dbo].[MethodUsedType] 
 ADD CONSTRAINT [PK_MethodUsedType]
	PRIMARY KEY CLUSTERED ([methodUsedTypeID])
GO

ALTER TABLE [dbo].[LCPDerogations] 
 ADD CONSTRAINT [PK_LCPDerogations]
	PRIMARY KEY CLUSTERED ([lCPDerogationsID])
GO

ALTER TABLE [dbo].[IEDArt72] 
 ADD CONSTRAINT [PK_IEDArt72]
	PRIMARY KEY CLUSTERED ([iEDArt72ID])
GO

ALTER TABLE [dbo].[FacilityReports] 
 ADD CONSTRAINT [PK_FacilityReports]
	PRIMARY KEY CLUSTERED ([facilityReportsID])
GO

ALTER TABLE [dbo].[FacilityReport] 
 ADD CONSTRAINT [PK_FacilityReport]
	PRIMARY KEY CLUSTERED ([facilityReportID])
GO

ALTER TABLE [dbo].[EnergyInput] 
 ADD CONSTRAINT [PK_EnergyInput]
	PRIMARY KEY CLUSTERED ([energyInputID])
GO

ALTER TABLE [dbo].[DesulphurisationRate] 
 ADD CONSTRAINT [PK_DesulphurisationRate]
	PRIMARY KEY CLUSTERED ([desulphurisationRateID])
GO

ALTER TABLE [dbo].[Common_WasteTypeCodeType] 
 ADD CONSTRAINT [PK_Common_WasteTypeCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_WasteTreatmentCodeType] 
 ADD CONSTRAINT [PK_Common_WasteTreatmentCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_UnitCodeType] 
 ADD CONSTRAINT [PK_Common_UnitCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_TotalEmissionsToAirType] 
 ADD CONSTRAINT [PK_Common_TotalEmissionsToAirType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_StatusOfThePlantType] 
 ADD CONSTRAINT [PK_Common_StatusOfThePlantType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_PollutantType] 
 ADD CONSTRAINT [PK_Common_PollutantType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_OtherSolidFuels] 
 ADD CONSTRAINT [PK_Common_OtherSolidFuels]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_OtherGasesType] 
 ADD CONSTRAINT [PK_Common_OtherGasesType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_MonthType] 
 ADD CONSTRAINT [PK_Common_MonthType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_MethodTypeCodeType] 
 ADD CONSTRAINT [PK_Common_MethodTypeCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_MethodBasisCodeType] 
 ADD CONSTRAINT [PK_Common_MethodBasisCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_MediumCodeType] 
 ADD CONSTRAINT [PK_Common_MediumCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_EnergyInputType] 
 ADD CONSTRAINT [PK_Common_EnergyInputType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_CountryCodeType] 
 ADD CONSTRAINT [PK_Common_CountryCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_ConfidentialCodeType] 
 ADD CONSTRAINT [PK_Common_ConfidentialCodeType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[Common_CombustionType] 
 ADD CONSTRAINT [PK_Common_CombustionType]
	PRIMARY KEY CLUSTERED ([id])
GO

ALTER TABLE [dbo].[AddressType] 
 ADD CONSTRAINT [PK_AddressType]
	PRIMARY KEY CLUSTERED ([addressTypeID])
GO

/* Create Foreign Key Constraints */

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [dbo].[Common_ConfidentialCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [dbo].[Common_MethodBasisCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_WasteTreatmentCodeType]
	FOREIGN KEY ([wasteTreatmentCode]) REFERENCES [dbo].[Common_WasteTreatmentCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_WasteTypeCodeType]
	FOREIGN KEY ([wasteTypeCode]) REFERENCES [dbo].[Common_WasteTypeCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [dbo].[MethodUsedType] ([methodUsedTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [dbo].[FacilityReport] ([facilityReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_AddressType]
	FOREIGN KEY ([address]) REFERENCES [dbo].[AddressType] ([addressTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_AddressType_02]
	FOREIGN KEY ([siteAddress]) REFERENCES [dbo].[AddressType] ([addressTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_WasteTransfer]
	FOREIGN KEY ([wasteTransferID]) REFERENCES [dbo].[WasteTransfer] ([wasteTransferID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[TotalEmissionsToAir] ADD CONSTRAINT [FK_TotalEmissionsToAir_Common_TotalEmissionsToAirType]
	FOREIGN KEY ([type]) REFERENCES [dbo].[Common_TotalEmissionsToAirType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[TotalEmissionsToAir] ADD CONSTRAINT [FK_TotalEmissionsToAir_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [dbo].[PlantReport] ([plantReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[SO2] ADD CONSTRAINT [FK_SO2_Common_MonthType]
	FOREIGN KEY ([month]) REFERENCES [dbo].[Common_MonthType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[SO2] ADD CONSTRAINT [FK_SO2_IEDArt72]
	FOREIGN KEY ([iEDArt72ID]) REFERENCES [dbo].[IEDArt72] ([iEDArt72ID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[Report] ADD CONSTRAINT [FK_Report_Common_CountryCodeType]
	FOREIGN KEY ([countryID]) REFERENCES [dbo].[Common_CountryCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[QuantityType] ADD CONSTRAINT [FK_QuantityType_Common_UnitCodeType]
	FOREIGN KEY ([UnitCode]) REFERENCES [dbo].[Common_UnitCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[ProductionVolume] ADD CONSTRAINT [FK_ProductionVolume_QuantityType]
	FOREIGN KEY ([quantity]) REFERENCES [dbo].[QuantityType] ([quantityTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[ProductionVolume] ADD CONSTRAINT [FK_ProductionVolume_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [dbo].[FacilityReport] ([facilityReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [dbo].[Common_ConfidentialCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [dbo].[Common_MethodBasisCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_PollutantType]
	FOREIGN KEY ([pollutantCode]) REFERENCES [dbo].[Common_PollutantType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [dbo].[MethodUsedType] ([methodUsedTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [dbo].[FacilityReport] ([facilityReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [dbo].[Common_ConfidentialCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_MediumCodeType]
	FOREIGN KEY ([mediumCode]) REFERENCES [dbo].[Common_MediumCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [dbo].[Common_MethodBasisCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_PollutantType]
	FOREIGN KEY ([pollutantCode]) REFERENCES [dbo].[Common_PollutantType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [dbo].[MethodUsedType] ([methodUsedTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [dbo].[FacilityReport] ([facilityReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantType] ADD CONSTRAINT [FK_PlantType_Common_CombustionType]
	FOREIGN KEY ([combustionPlantType]) REFERENCES [dbo].[Common_CombustionType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantType] ADD CONSTRAINT [FK_PlantType_QuantityType]
	FOREIGN KEY ([thermalInput]) REFERENCES [dbo].[QuantityType] ([quantityTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantType] ADD CONSTRAINT [FK_PlantType_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [dbo].[PlantReport] ([plantReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReports] ADD CONSTRAINT [FK_PlantReports_Report]
	FOREIGN KEY ([reportID]) REFERENCES [dbo].[Report] ([reportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReport] ADD CONSTRAINT [FK_PlantReport_Common_StatusOfThePlantType]
	FOREIGN KEY ([statusOfThePlant]) REFERENCES [dbo].[Common_StatusOfThePlantType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType]
	FOREIGN KEY ([mWth]) REFERENCES [dbo].[QuantityType] ([quantityTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType_02]
	FOREIGN KEY ([capacityAddedMW]) REFERENCES [dbo].[QuantityType] ([quantityTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType_03]
	FOREIGN KEY ([capacityAffectedMW]) REFERENCES [dbo].[QuantityType] ([quantityTypeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[PlantReport] ADD CONSTRAINT [FK_PlantReport_PlantReports]
	FOREIGN KEY ([plantReportsID]) REFERENCES [dbo].[PlantReports] ([plantReportsID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[MethodUsedType] ADD CONSTRAINT [FK_MethodUsedType_Common_MethodTypeCodeType]
	FOREIGN KEY ([MethodTypeCode]) REFERENCES [dbo].[Common_MethodTypeCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[LCPDerogations] ADD CONSTRAINT [FK_LCPDerogations_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [dbo].[PlantReport] ([plantReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[IEDArt72] ADD CONSTRAINT [FK_IEDArt72_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [dbo].[PlantReport] ([plantReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[FacilityReports] ADD CONSTRAINT [FK_FacilityReports_Report]
	FOREIGN KEY ([reportID]) REFERENCES [dbo].[Report] ([reportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[FacilityReport] ADD CONSTRAINT [FK_FacilityReport_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [dbo].[Common_ConfidentialCodeType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[FacilityReport] ADD CONSTRAINT [FK_FacilityReport_FacilityReports]
	FOREIGN KEY ([facilityReportsID]) REFERENCES [dbo].[FacilityReports] ([facilityReportsID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_EnergyInputType]
	FOREIGN KEY ([type]) REFERENCES [dbo].[Common_EnergyInputType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_OtherGasesType]
	FOREIGN KEY ([otherGases]) REFERENCES [dbo].[Common_OtherGasesType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_OtherSolidFuels]
	FOREIGN KEY ([otherSolidFuels]) REFERENCES [dbo].[Common_OtherSolidFuels] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[EnergyInput] ADD CONSTRAINT [FK_EnergyInput_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [dbo].[PlantReport] ([plantReportID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[DesulphurisationRate] ADD CONSTRAINT [FK_DesulphurisationRate_Common_MonthType]
	FOREIGN KEY ([month]) REFERENCES [dbo].[Common_MonthType] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dbo].[DesulphurisationRate] ADD CONSTRAINT [FK_DesulphurisationRate_IEDArt72]
	FOREIGN KEY ([iEDArt72ID]) REFERENCES [dbo].[IEDArt72] ([iEDArt72ID]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'The WasteTransfer elements hold the reported data on off-site transfers of waste for a facility, except transfers of pollutants in waste-water which is reported in the PollutantTransfer element.', 'Schema', [dbo], 'table', [WasteTransfer]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the type of waste (non-hazardous, hazardous, hazardous within country and hazardous outside country).', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [wasteTypeCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the waste treatment operation (recovery or disposal)', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [wasteTreatmentCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Quantity [t/year] Must be reported with 3 significant digits.', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [quantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the basis of the main method used (M/C/E).', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [methodBasisCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the calculation and measurement method(s) used for determination of the quantity', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [methodUsed]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     ', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [confidentialIndicator]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [confidentialCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual remark, e.g. elaboration on the reason for confidentiality.', 'Schema', [dbo], 'table', [WasteTransfer], 'column', [remarkText]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The WasteHandlerParty element holds information about the recoverer/disposer of waste. This should only be reported for waste transfer of hazardous waste outside the country.', 'Schema', [dbo], 'table', [WasteHandlerParty]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Name of recoverer/disposer. Required unless confidentiality is claimed for the WasteTransfer element', 'Schema', [dbo], 'table', [WasteHandlerParty], 'column', [name]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. The address of the recoverer/disposer. Required unless confidentiality is claimed for the WasteTransfer.', 'Schema', [dbo], 'table', [WasteHandlerParty], 'column', [address]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. The address of the actual recoverer/disposer site. ', 'Schema', [dbo], 'table', [WasteHandlerParty], 'column', [siteAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [TotalEmissionsToAir], 'column', [type]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [TotalEmissionsToAir], 'column', [quantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. The Member State reporting. The list of legal values identifying the countries correspond to ISO 3166 alpha-2 except for Greece and the United Kingdom as recommended in http://publications.europa.eu/code/pdf/370000en.htm#pays, Revision 8. ', 'Schema', [dbo], 'table', [Report], 'column', [countryID]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual remark from MS. ', 'Schema', [dbo], 'table', [Report], 'column', [remarkText]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. The calendar year for which data is gathered. Must be in the interval [2006; this year].', 'Schema', [dbo], 'table', [Report], 'column', [reportingYear]
GO

EXEC sp_addextendedproperty 'MS_Description', 'TNE,', 'Schema', [dbo], 'table', [QuantityType]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The total production volume related to the main activity of the facility.', 'Schema', [dbo], 'table', [ProductionVolume]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. The product/product group.', 'Schema', [dbo], 'table', [ProductionVolume], 'column', [productName]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. The total volume. The unit must be given in attribute unitCode.', 'Schema', [dbo], 'table', [ProductionVolume], 'column', [quantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The PollutantTransfer elements hold the reported data on off-site transfers of pollutants in waste water for a facility.                 ', 'Schema', [dbo], 'table', [PollutantTransfer]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the pollutant (or the pollutant group if confidentiality is claimed)', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [pollutantCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the basis of the main method used (M/C/E).', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [methodBasisCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the calculation and measurement method(s) used for determination of the quantity.', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [methodUsed]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Total quantity [kg/year]. Must be reported with 3 significant digits. Values below threshold are considered voluntary and will not be published.', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [quantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     ', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [confidentialIndicator]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [confidentialCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual remark, e.g. elaboration on the reason for confidentiality.', 'Schema', [dbo], 'table', [PollutantTransfer], 'column', [remarkText]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The PollutantRelease elements hold the reported releases of pollutants for a facility. It covers both releases to air, water and land. This will be indicated by the medium selected. Transfers in waste-water will be reported in the PollutantTransfer elements', 'Schema', [dbo], 'table', [PollutantRelease]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the environmental medium (air, water, land). ', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [mediumCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the pollutant (or the pollutant group if confidentiality is claimed) Notice that if confidentiality is claimed the pollutant group must be reported.', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [pollutantCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Identifies the basis of the main method used (M/C/E)', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [methodBasisCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the calculation and measurement method(s) used for determination of the total quantity.', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [methodUsed]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Total quantity including accidental quantity [kg/year]. Values below threshold are considered voluntary and will not be published. Must be reported with 3 significant digits', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [totalQuantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Accidental quantity [kg/year] Must be reported with 3 significant digits.', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [accidentalQuantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Indicates if confidentiality is claimed or not. true marks confidentiality, false marks no confidentiality.                     ', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [confidentialIndicator]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [confidentialCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual remark, e.g. elaboration on the reason for confidentiality.', 'Schema', [dbo], 'table', [PollutantRelease], 'column', [remarkText]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantType], 'column', [combustionPlantType]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantType], 'column', [thermalInput]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Holds the reporting for a given plant', 'Schema', [dbo], 'table', [PlantReport]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [dBPlantId]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [statusOfThePlant]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [mWth]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [extensionBy50MWOrMore]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [capacityAddedMW]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [substantialChange]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [capacityAffectedMW]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [dateOfStartOperation]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [refineries]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [PlantReport], 'column', [operationHours]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Describes a measurement/calculation method used for determination of quantities of pollutants and waste             ', 'Schema', [dbo], 'table', [MethodUsedType]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identifies the type of method used (CEN/ISO, ETS, etc.). Notice that the method type “WEIGH” (i.e. weighing) only is allowed for waste transfer.', 'Schema', [dbo], 'table', [MethodUsedType], 'column', [MethodTypeCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'A short designation or description of the method used. Required for some method types as indicated in the list of legal method type codes.', 'Schema', [dbo], 'table', [MethodUsedType], 'column', [Designation]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [LCPDerogations], 'column', [art32TNP]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [LCPDerogations], 'column', [art33LLD]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [LCPDerogations], 'column', [art34SIS]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [LCPDerogations], 'column', [art35DHP]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [LCPDerogations], 'column', [usefulHeatProductionRollingAverage5Years]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Holds the reporting for a given facility             ', 'Schema', [dbo], 'table', [FacilityReport]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [FacilityReport], 'column', [dBFacitilyID]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The number of operating hours in reporting year.', 'Schema', [dbo], 'table', [FacilityReport], 'column', [operationHours]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required . Indicates if voluntary data should be protected or not. In this case all voluntary data of the facility is considered protected with a few exceptions at stated in the descriptions of the individual elements. true marks protection, false marks no protection.', 'Schema', [dbo], 'table', [FacilityReport], 'column', [protectVoluntaryData]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual information. Additional information to be published on web site as-is (e.g. e-mail, contact person etc.).', 'Schema', [dbo], 'table', [FacilityReport], 'column', [publicInformation]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The number of employees.                   ', 'Schema', [dbo], 'table', [FacilityReport], 'column', [totalEmployeeQuantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required. Indicates if confidentiality for mandatory data is claimed or not. true marks confidentiality, false marks no confidentiality.                     ', 'Schema', [dbo], 'table', [FacilityReport], 'column', [confidentialIndicator]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional. Identifies the reason for confidentiality according to Directive 2003/4/EC, Article 4(2).', 'Schema', [dbo], 'table', [FacilityReport], 'column', [confidentialCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Textual remark, e.g. information in changes of the history of the facility, elaboration on the reason for confidentiality etc.', 'Schema', [dbo], 'table', [FacilityReport], 'column', [remarkText]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [EnergyInput], 'column', [type]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional.', 'Schema', [dbo], 'table', [EnergyInput], 'column', [otherGases]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Conditional.', 'Schema', [dbo], 'table', [EnergyInput], 'column', [otherSolidFuels]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Required.', 'Schema', [dbo], 'table', [EnergyInput], 'column', [quantity]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The base format for addresses in PRTR.             ', 'Schema', [dbo], 'table', [AddressType]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The name, expressed as text, of a street in the address.', 'Schema', [dbo], 'table', [AddressType], 'column', [StreetName]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The building number, expressed as text, in the address.', 'Schema', [dbo], 'table', [AddressType], 'column', [BuildingNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The name, expressed as text, of the city, town or village in the address.', 'Schema', [dbo], 'table', [AddressType], 'column', [City]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The postcode, expressed as text, if the address.', 'Schema', [dbo], 'table', [AddressType], 'column', [PostalCode]
GO

EXEC sp_addextendedproperty 'MS_Description', 'The unique identifier of a country in the structured address (Reference ISO 3166 and UN/ECE Rec 3).', 'Schema', [dbo], 'table', [AddressType], 'column', [CountryID]
GO
