//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TextStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date appears along with the news story on the E-PRTR website.
        /// </summary>
        internal static string CalendarToolTip {
            get {
                return ResourceManager.GetString("CalendarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string ClearCacheButtonText {
            get {
                return ResourceManager.GetString("ClearCacheButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to clear the resource cache of the E-PRTR website and E-PRTR Review website.
        /// </summary>
        internal static string ClearCacheText {
            get {
                return ResourceManager.GetString("ClearCacheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-PRTR CMS.
        /// </summary>
        internal static string CmsWebsiteTitle {
            get {
                return ResourceManager.GetString("CmsWebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Environmental Agency.
        /// </summary>
        internal static string EEANAME {
            get {
                return ResourceManager.GetString("EEANAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The European Pollutant Release and Transfer Register.
        /// </summary>
        internal static string EPRTRNAME {
            get {
                return ResourceManager.GetString("EPRTRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates Indicates whether this news story is entirely omitted from the E-PRTR website.
        /// </summary>
        internal static string HideNewsToolTip {
            get {
                return ResourceManager.GetString("HideNewsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string KeyDescription {
            get {
                return ResourceManager.GetString("KeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string KeyTitle {
            get {
                return ResourceManager.GetString("KeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to the E-PRTR CMS.
        /// </summary>
        internal static string LoginHeaderText {
            get {
                return ResourceManager.GetString("LoginHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Only plain text is allowed in this text field).
        /// </summary>
        internal static string PlainTextWarning {
            get {
                return ResourceManager.GetString("PlainTextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On submit changes become online immediately.
        /// </summary>
        internal static string SubmitWarning {
            get {
                return ResourceManager.GetString("SubmitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether this news story is shown on the E-PRTR front page.
        /// </summary>
        internal static string TopNewsToolTip {
            get {
                return ResourceManager.GetString("TopNewsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the E-PRTR CMS.
        /// </summary>
        internal static string WelcomeHeaderText {
            get {
                return ResourceManager.GetString("WelcomeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;With this CMS website you can edit those parts of the E-PRTR website that are CMS enabled.&lt;/p&gt;
        ///&lt;p&gt;&lt;br /&gt;Click one of the links &lt;a href=&quot;TextEditPage.aspx&quot;&gt;Static text editor&lt;/a&gt;&amp;nbsp;or&amp;nbsp;&lt;a href=&quot;NewsEditPage.aspx&quot;&gt;News editor&lt;/a&gt;&amp;nbsp;in the top menu to start editing.&amp;nbsp;Alternatively, if you want to upload one or more files click the &lt;a href=&quot;FileCatalog.aspx&quot;&gt;File catalog&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
