//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace EPRTRT.DataContracts
{
	/// <summary>
    /// Data Contract Class - WasteTransferBoundary. Used to populate charts.
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://atkins.com", Name = "WasteTransferBoundary")]
	public partial class WasteTransferBoundary
	{
		private string fromCountry;
		private string toCountry;
		private string facilities;
		private string percentEUTotal;
		private string doubleCounting;
		private string recovery;
		private string total;
	    private string disposal;
        private string name;
		
		[WcfSerialization::DataMember(Name = "FromCountry", IsRequired = false, Order = 0)]
		public string FromCountry
		{
		  get { return fromCountry; }
		  set { fromCountry = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ToCountry", IsRequired = false, Order = 1)]
		public string ToCountry
		{
		  get { return toCountry; }
		  set { toCountry = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Facilities", IsRequired = false, Order = 2)]
		public string Facilities
		{
		  get { return facilities; }
		  set { facilities = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PercentEUTotal", IsRequired = false, Order = 3)]
		public string PercentEUTotal
		{
		  get { return percentEUTotal; }
		  set { percentEUTotal = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DoubleCounting", IsRequired = false, Order = 4)]
		public string DoubleCounting
		{
		  get { return doubleCounting; }
		  set { doubleCounting = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Recovery", IsRequired = false, Order = 5)]
		public string Recovery
		{
		  get { return recovery; }
		  set { recovery = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Total", IsRequired = false, Order = 6)]
		public string Total
		{
		  get { return total; }
		  set { total = value; }
		}
        [WcfSerialization::DataMember(Name = "Disposal", IsRequired = false, Order = 7)]
        public string Disposal
        {
            get { return disposal; }
            set { disposal = value; }
        }

        [WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 8)]
        public string Name
        {
            get { return name; }
            set { name = value; }
        }
	}
}


