//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace EPRTRT.DataContracts
{
	/// <summary>
    /// Data Contract Class - WasteTransfers. Used to populate charts.
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://atkins.com", ItemName = "WasteTransfers")]
	public partial class WasteTransfers : System.Collections.ObjectModel.Collection<WasteTransfer>
	{
	}
}

