rem update of eprtrreview-maps with regards to arcgis server
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitydetails.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"

rem review is under test folder
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitydetails.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\testconfig.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "services/Air" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "services/Air" "services/Test"

cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitydetails.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "services/Internal" "services/Test"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "services/Internal" "services/Test"

cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_air_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_air_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_water_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_water_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"

rem update of eprtrreview-maps with regards to google search license key
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_air_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_diffuse_water_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_facilitylevels_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_industrialactivity_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_mapsearch_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\config_wastetransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"

rem update of review maps regarding search - only in review
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Air/" "Test/"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRreview\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Internal/" "Test/"

rem update of eprtrpublic-maps with regards to arcgis server
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_facilitydetails.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_facilitylevels_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_facilitylevels_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_industrialactivity_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_industrialactivity_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_mapsearch.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_mapsearch_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\testconfig.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_air_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_air_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_water_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_water_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"
cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services" "http://discomap.eea.europa.eu/ArcGIS/rest/services"

rem update of eprtrpublic-maps with regards to google search license key
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_air_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_diffuse_water_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_facilitylevels_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_industrialactivity_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_mapsearch.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_mapsearch_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutantrelease_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg" 
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
rem cscript replace.vbs "C:\E-PRTR_Ori\EEA\EPRTRpublic\EPRTRweb\Map\config_wastetransfer_ex.xml" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBQP9DYj1SGFg6FM-rqk8vMgigJ1RBSHXcG5VbvJ5me6pgaERQCc7FgAPg" "ABQIAAAAA1acrdbJJPhJK7NdgNERGBTwqcV4DUuFpXoDDxcq42tGWfpXOxSpmeioGpEuGpyeA4ws71HBLX54Jg"
