<?xml version="1.0" encoding="utf-8"?>
<Database Name="EPRTRcms" Class="DataClassesNewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sdkcga6302;Initial Catalog=EPRTRcms;User ID=sa" SettingsObjectName="QueryLayer.Properties.Settings" SettingsPropertyName="EPRTRcmsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NewsKey" Member="NewsKeys">
    <Type Name="NewsKey">
      <Column Name="NewsKeyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TopNewsIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NewsKey_NewsValue" Member="NewsValues" ThisKey="NewsKeyID" OtherKey="NewsKeyID" Type="NewsValue" />
    </Type>
  </Table>
  <Table Name="dbo.NewsValue" Member="NewsValues">
    <Type Name="NewsValue">
      <Column Name="NewsValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsKeyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CultureCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HeaderText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BodyText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NewsKey_NewsValue" Member="NewsKey" ThisKey="NewsKeyID" OtherKey="NewsKeyID" Type="NewsKey" IsForeignKey="true" />
    </Type>
  </Table>
</Database>