--INSERT into tAT_ResourceKey the EPER ResourceKeys
USE EPRTRcms

INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('GRHGASEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('OTHGASEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HEVMETEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CHLORGEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('OTHORGEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('BTEXEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CH4EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CO2EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HFCSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('N2OEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PFCSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('SF6EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('COEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('NH3EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('NMVOCEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('NOXEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('SOXEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CHLORINE AND INORGANIC COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('FLUORINE AND INORGANIC COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HCNEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('AS AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CD AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CR AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CU AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HG AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('NI AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ZN AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HEXACHLOROCYCLOHEXANE(HCH)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CHLORO-ALKANES (C10-13)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('DICHLOROETHANE-1,2 (DCE)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('DICHLOROMETHANE (DCM)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HALOGENATED ORGANIC COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HEXACHLOROBENZENE (HCB)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('HEXACHLOROBUTADIENE (HCBD)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PCDD+PCDF (DIOXINS+FURANS)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PENTACHLOROPHENOL (PCP)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TETRACHLOROETHYLENE (PER)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TETRACHLOROMETHANE (TCM)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TRICHLOROBENZENES (TCB)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TRICHLOROETHANE-1,1,1 (TCE)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TRICHLOROETHYLENE (TRI)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TRICHLOROMETHANEEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PB AND COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('BROMINATED DIPHENYLETHEREPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ORGANOTIN - COMPOUNDSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PHENOLSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TOTAL ORGANIC CARBON (TOC)EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('BENZENEEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ETHYLBENZENEEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TOLUENEEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('XYLENESEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TOTAL - NITROGENEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('TOTAL - PHOSPHORUSEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CHLORIDESEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('CYANIDESEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('FLUORIDESEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PM10EPER','LOV_POLLUTANT',0,0,'');
--INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PAHs in EPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('INORGEPER','LOV_POLLUTANT',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionsToAir','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionsName','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('Emissions','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionsToWater','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ContentEmissions','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionsTo','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('WaterDirect','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('WaterIndirect','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionGroup','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('SearchEPERData','Web.sitemap',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('SearchEPERPollutant','Web.sitemap',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('SearchEPERActivities','Web.sitemap',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EPER Activity Information','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EPER Emission Information','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('InfoEmissions','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('AllValuesAreYearlyEmissions','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionReleaseTimeSeries','Facility',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmissionReleaseComparison','Facility',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ContentEmissionsRelease','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('ContentEmissionsTransfers','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('FacilityEmissionsEPER','Facility',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('FacilityInfoEmission','Facility',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('AllEmissionsGroups','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('AllEmissions','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('PollutantPageContentEPER','Common',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('NACE_1.1:OTHER','LOV_NACEACTIVITY',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('EmmissionsName','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('FacilitylevelPollutanttransfersEPER','Facility',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('AllValuesAreYearlyTransfersEPER','Pollutant',0,0,'');
INSERT INTO [EPRTRcms].[dbo].[tAT_ResourceKey] ([ResourceKey],[ResourceType],[AllowHTML],[EditCMS],[KeyDescription]) VALUES ('Legend','Common',0,0,'');
