--CREATE FOREIGN KEYS

ALTER TABLE ADDRESS_COMPETENT ADD CONSTRAINT FK_ADDRESS_COMPETENT_COMPETENTAUTHORITYPARTY 
FOREIGN KEY (CompetentAuthorityPartyID) REFERENCES COMPETENTAUTHORITYPARTY(CompetentAuthorityPartyID)

ALTER TABLE ADDRESS_FACILITY ADD CONSTRAINT FK_ADDRESS_FACILITY_FacilityReport 
FOREIGN KEY (FacilityReportID) REFERENCES FacilityReport(FacilityReportID)

ALTER TABLE ADDRESS_WASTE ADD CONSTRAINT FK_ADDRESS_WASTE_WasteTransfer 
FOREIGN KEY (WasteTransferID) REFERENCES WasteTransfer(WasteTransferID)

ALTER TABLE ADDRESS_WASTESITE ADD CONSTRAINT FK_ADDRESS_WASTESITE_WasteTransfer 
FOREIGN KEY (WasteTransferID) REFERENCES WasteTransfer(WasteTransferID)

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_FACILITYREPORT 
FOREIGN KEY (FacilityReportID) REFERENCES FACILITYREPORT(FacilityReportID)

ALTER TABLE COMPETENTAUTHORITYPARTY ADD CONSTRAINT FK_COMPETENTAUTHORITYPARTY_POLLUTANTRELEASEANDTRANSFERREPORT 
FOREIGN KEY (PollutantReleaseAndTransferReportID) REFERENCES POLLUTANTRELEASEANDTRANSFERREPORT(PollutantReleaseAndTransferReportID)


--ALTER TABLE COMPETENTAUTHORITYPARTY ADD CONSTRAINT FK_COMPETENTAUTHORITYPARTY_ADDRESS 
--FOREIGN KEY (AddressID) REFERENCES ADDRESS(AddressID)

--ALTER TABLE COMPETENTAUTHORITYPARTY ADD CONSTRAINT FK_COMPETENTAUTHORITYPARTY_ADDRESS 
--FOREIGN KEY (AddressID) REFERENCES ADDRESS(AddressID)


--ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_ADDRESS
--FOREIGN KEY (AddressID) REFERENCES ADDRESS(AddressID)

--ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_COMPETENTAUTHORITYPARTY 
--FOREIGN KEY (CompetentAuthorityPartyID) REFERENCES COMPETENTAUTHORITYPARTY(CompetentAuthorityPartyID)

ALTER TABLE METHODUSED_POLLUTANTRELEASE ADD CONSTRAINT FK_METHODUSED_POLLUTANTRELEASE 
FOREIGN KEY (PollutantReleaseID) REFERENCES POLLUTANTRELEASE(PollutantReleaseID)

ALTER TABLE METHODUSED_POLLUTANTTRANSFER ADD CONSTRAINT FK_METHODUSED_POLLUTANTTRANSFER 
FOREIGN KEY (PollutantTransferID) REFERENCES POLLUTANTTRANSFER(PollutantTransferID)

ALTER TABLE METHODUSED_WASTETRANSFER ADD CONSTRAINT FK_METHODUSED_WASTETRANSFER 
FOREIGN KEY (WasteTransferID) REFERENCES WASTETRANSFER(WasteTransferID)


ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_POLLUTANTRELEASEANDTRANSFERREPORT 
FOREIGN KEY (PollutantReleaseAndTransferReportID) REFERENCES POLLUTANTRELEASEANDTRANSFERREPORT(PollutantReleaseAndTransferReportID)

ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_FACILITYREPORT 
FOREIGN KEY (FacilityReportID) REFERENCES FACILITYREPORT(FacilityReportID)

ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_FACILITYREPORT 
FOREIGN KEY (FacilityReportID) REFERENCES FACILITYREPORT(FacilityReportID)

ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_FACILITYREPORT 
FOREIGN KEY (FacilityReportID) REFERENCES FACILITYREPORT(FacilityReportID)

--ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_ADDRESS
--FOREIGN KEY (WasteHandlerPartyAddressID) REFERENCES ADDRESS(AddressID)

--ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_SITEADDRESS
--FOREIGN KEY (WasteHandlerPartySiteAddressID) REFERENCES ADDRESS(AddressID)
