//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationChecker.LDAPAuthenticationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eea.europa.eu/Services", ConfigurationName="LDAPAuthenticationService.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Generating message contract since element name usr from namespace http://eea.europa.eu/Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eea.europa.eu/Services/SqlExecute", ReplyAction="*")]
        AuthenticationChecker.LDAPAuthenticationService.SqlExecuteResponse SqlExecute(AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://eea.europa.eu/Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eea.europa.eu/Services/LDAPAuthenticationCheck", ReplyAction="*")]
        AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckResponse LDAPAuthenticationCheck(AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequest request);
        
        // CODEGEN: Generating message contract since element name strUrl from namespace http://eea.europa.eu/Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eea.europa.eu/Services/XmlRouter", ReplyAction="*")]
        AuthenticationChecker.LDAPAuthenticationService.XmlRouterResponse XmlRouter(AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SqlExecute", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequestBody Body;
        
        public SqlExecuteRequest() {
        }
        
        public SqlExecuteRequest(AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class SqlExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string server;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sql;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string name;
        
        public SqlExecuteRequestBody() {
        }
        
        public SqlExecuteRequestBody(string usr, string pwd, string server, string database, string sql, string name) {
            this.usr = usr;
            this.pwd = pwd;
            this.server = server;
            this.database = database;
            this.sql = sql;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SqlExecuteResponse", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.SqlExecuteResponseBody Body;
        
        public SqlExecuteResponse() {
        }
        
        public SqlExecuteResponse(AuthenticationChecker.LDAPAuthenticationService.SqlExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class SqlExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object SqlExecuteResult;
        
        public SqlExecuteResponseBody() {
        }
        
        public SqlExecuteResponseBody(object SqlExecuteResult) {
            this.SqlExecuteResult = SqlExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LDAPAuthenticationCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LDAPAuthenticationCheck", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequestBody Body;
        
        public LDAPAuthenticationCheckRequest() {
        }
        
        public LDAPAuthenticationCheckRequest(AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class LDAPAuthenticationCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LDAPPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Role;
        
        public LDAPAuthenticationCheckRequestBody() {
        }
        
        public LDAPAuthenticationCheckRequestBody(string username, string password, string LDAPPath, string Role) {
            this.username = username;
            this.password = password;
            this.LDAPPath = LDAPPath;
            this.Role = Role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LDAPAuthenticationCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LDAPAuthenticationCheckResponse", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckResponseBody Body;
        
        public LDAPAuthenticationCheckResponse() {
        }
        
        public LDAPAuthenticationCheckResponse(AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class LDAPAuthenticationCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object LDAPAuthenticationCheckResult;
        
        public LDAPAuthenticationCheckResponseBody() {
        }
        
        public LDAPAuthenticationCheckResponseBody(object LDAPAuthenticationCheckResult) {
            this.LDAPAuthenticationCheckResult = LDAPAuthenticationCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlRouterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlRouter", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequestBody Body;
        
        public XmlRouterRequest() {
        }
        
        public XmlRouterRequest(AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class XmlRouterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strData;
        
        public XmlRouterRequestBody() {
        }
        
        public XmlRouterRequestBody(string strUrl, string strData) {
            this.strUrl = strUrl;
            this.strData = strData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlRouterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlRouterResponse", Namespace="http://eea.europa.eu/Services", Order=0)]
        public AuthenticationChecker.LDAPAuthenticationService.XmlRouterResponseBody Body;
        
        public XmlRouterResponse() {
        }
        
        public XmlRouterResponse(AuthenticationChecker.LDAPAuthenticationService.XmlRouterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eea.europa.eu/Services")]
    public partial class XmlRouterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object XmlRouterResult;
        
        public XmlRouterResponseBody() {
        }
        
        public XmlRouterResponseBody(object XmlRouterResult) {
            this.XmlRouterResult = XmlRouterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServicesSoapChannel : AuthenticationChecker.LDAPAuthenticationService.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<AuthenticationChecker.LDAPAuthenticationService.ServicesSoap>, AuthenticationChecker.LDAPAuthenticationService.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationChecker.LDAPAuthenticationService.SqlExecuteResponse AuthenticationChecker.LDAPAuthenticationService.ServicesSoap.SqlExecute(AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequest request) {
            return base.Channel.SqlExecute(request);
        }
        
        public object SqlExecute(string usr, string pwd, string server, string database, string sql, string name) {
            AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequest inValue = new AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequest();
            inValue.Body = new AuthenticationChecker.LDAPAuthenticationService.SqlExecuteRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.pwd = pwd;
            inValue.Body.server = server;
            inValue.Body.database = database;
            inValue.Body.sql = sql;
            inValue.Body.name = name;
            AuthenticationChecker.LDAPAuthenticationService.SqlExecuteResponse retVal = ((AuthenticationChecker.LDAPAuthenticationService.ServicesSoap)(this)).SqlExecute(inValue);
            return retVal.Body.SqlExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckResponse AuthenticationChecker.LDAPAuthenticationService.ServicesSoap.LDAPAuthenticationCheck(AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequest request) {
            return base.Channel.LDAPAuthenticationCheck(request);
        }
        
        public object LDAPAuthenticationCheck(string username, string password, string LDAPPath, string Role) {
            AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequest inValue = new AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequest();
            inValue.Body = new AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.LDAPPath = LDAPPath;
            inValue.Body.Role = Role;
            AuthenticationChecker.LDAPAuthenticationService.LDAPAuthenticationCheckResponse retVal = ((AuthenticationChecker.LDAPAuthenticationService.ServicesSoap)(this)).LDAPAuthenticationCheck(inValue);
            return retVal.Body.LDAPAuthenticationCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationChecker.LDAPAuthenticationService.XmlRouterResponse AuthenticationChecker.LDAPAuthenticationService.ServicesSoap.XmlRouter(AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequest request) {
            return base.Channel.XmlRouter(request);
        }
        
        public object XmlRouter(string strUrl, string strData) {
            AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequest inValue = new AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequest();
            inValue.Body = new AuthenticationChecker.LDAPAuthenticationService.XmlRouterRequestBody();
            inValue.Body.strUrl = strUrl;
            inValue.Body.strData = strData;
            AuthenticationChecker.LDAPAuthenticationService.XmlRouterResponse retVal = ((AuthenticationChecker.LDAPAuthenticationService.ServicesSoap)(this)).XmlRouter(inValue);
            return retVal.Body.XmlRouterResult;
        }
    }
}
