use EPRTRweb
go
------------------------------------------------------------------------------------------
--	This script generates indexes on selected tables in the review database
------------------------------------------------------------------------------------------

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_MAINACTIVITY_INDEX')
   DROP INDEX FACILITYSEARCH_MAINACTIVITY.FACILITYSEARCH_MAINACTIVITY_INDEX
go
CREATE UNIQUE INDEX FACILITYSEARCH_MAINACTIVITY_INDEX
on	FACILITYSEARCH_MAINACTIVITY(
	ReportingYear desc, 
	LOV_CountryID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE_INDEX')
	DROP INDEX FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE_INDEX ON sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE
go
CREATE UNIQUE INDEX FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE_INDEX 
on	sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE(
	ReportingYear desc, 
	LOV_CountryID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_MAINACTIVITY_SP_INDEX')
	DROP INDEX FACILITYSEARCH_MAINACTIVITY_SP_INDEX ON sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE
go
CREATE SPATIAL INDEX FACILITYSEARCH_MAINACTIVITY_SP_INDEX
ON sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE(
	GeographicalCoordinate
	)
USING GEOMETRY_GRID
WITH (
	BOUNDING_BOX = (-63.1536409894401,-21.3898529982173,55.8367689986903,71.2021899785846),
	GRIDS = (medium, medium, medium, medium), CELLS_PER_OBJECT = 16
	)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_MAINACTIVITY_SPI')
   DROP INDEX FACILITYSEARCH_MAINACTIVITY_SPI on sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE
go
CREATE SPATIAL INDEX FACILITYSEARCH_MAINACTIVITY_SPI
ON	sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE(GeographicalCoordinate)
USING 
	GEOMETRY_GRID
WITH (
	BOUNDING_BOX = (-63.1536409894401,-21.3898529982173,55.8367689986903,71.2021899785846),
	GRIDS = (medium, medium, medium, medium), CELLS_PER_OBJECT = 16
	)
go
 
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_POLLUTANT_INDEX')
	DROP INDEX FACILITYSEARCH_POLLUTANT_INDEX ON FACILITYSEARCH_POLLUTANT
go
CREATE INDEX FACILITYSEARCH_POLLUTANT_INDEX 
on FACILITYSEARCH_POLLUTANT(
	LOV_MediumID,
	LOV_PollutantID,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_WASTETRANSFER_INDEX')
	DROP INDEX FACILITYSEARCH_WASTETRANSFER_INDEX ON FACILITYSEARCH_WASTETRANSFER
go
CREATE UNIQUE INDEX FACILITYSEARCH_WASTETRANSFER_INDEX 
on FACILITYSEARCH_WASTETRANSFER(
	LOV_WasteTypeID,
	LOV_WasteTreatmentID,
	FacilityReportID,
	WasteTransferID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_ALL_INDEX')
	DROP INDEX FACILITYSEARCH_ALL_INDEX ON FACILITYSEARCH_ALL
go
CREATE UNIQUE INDEX FACILITYSEARCH_ALL_INDEX 
on FACILITYSEARCH_ALL(
	ReportingYear,
	LOV_CountryID,
	LOV_MediumID,
	LOV_PollutantID,
	LOV_WasteTypeID,
	LOV_WasteTreatmentID,
	IDWaste,
	FacilityReportID
)

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_ALL_INDEX_CI_FPW')
	DROP INDEX FACILITYSEARCH_ALL_INDEX_CI_FPW ON FACILITYSEARCH_ALL
go
CREATE INDEX FACILITYSEARCH_ALL_INDEX_CI_FPW 
on FACILITYSEARCH_ALL(
	ReportingYear,
	ConfidentialIndicatorFacility,
	ConfidentialIndicatorPollutant,
	ConfidentialIndicatorWaste
)

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_ALL_INDEX_CI_FWP')
	DROP INDEX FACILITYSEARCH_ALL_INDEX_CI_FWP ON FACILITYSEARCH_ALL
go
CREATE INDEX FACILITYSEARCH_ALL_INDEX_CI_FWP 
on FACILITYSEARCH_ALL(
	ReportingYear,
	ConfidentialIndicatorFacility,
	ConfidentialIndicatorWaste,
	ConfidentialIndicatorPollutant
)

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE_INDEX')
	DROP INDEX FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE_INDEX ON sde.FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE
go
CREATE UNIQUE INDEX FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE_INDEX 
on sde.FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE(
	ReportingYear,
	LOV_CountryID,
	LOV_MediumID,
	LOV_PollutantID,
	LOV_WasteTypeID,
	LOV_WasteTreatmentID,
	IDWaste,
	FacilityReportID
)
go

--select * from EPRTRweb.dbo.FACILITYSEARCH_MAINACTIVITY
--select * from EPRTRweb.sde.FACILITYSEARCH_MAINACTIVITY_GEOGRAPHICALCOORDINATE
--select * from EPRTRweb.dbo.FACILITYSEARCH_POLLUTANT where FacilityReportID = 17116 and LOV_PollutantID = 27
--select * from EPRTRweb.dbo.FACILITYSEARCH_WASTETRANSFER
--select * from EPRTRweb.dbo.FACILITYSEARCH_ALL
--select * from EPRTRweb.sde.FACILITYSEARCH_ALL_GEOGRAPHICALCOORDINATE

----------------------------------------------------------


IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_DETAIL_INDEX')
	DROP INDEX FACILITYDETAIL_DETAIL_INDEX ON FACILITYDETAIL_DETAIL
go
CREATE UNIQUE INDEX FACILITYDETAIL_DETAIL_INDEX 
on FACILITYDETAIL_DETAIL(
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_COMPETENTAUTHORITYPARTY_INDEX')
	DROP INDEX FACILITYDETAIL_COMPETENTAUTHORITYPARTY_INDEX ON FACILITYDETAIL_COMPETENTAUTHORITYPARTY
go
CREATE UNIQUE INDEX FACILITYDETAIL_COMPETENTAUTHORITYPARTY_INDEX 
on FACILITYDETAIL_COMPETENTAUTHORITYPARTY(
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_ACTIVITY_INDEX')
	DROP INDEX FACILITYDETAIL_ACTIVITY_INDEX ON FACILITYDETAIL_ACTIVITY
go
CREATE UNIQUE INDEX FACILITYDETAIL_ACTIVITY_INDEX 
on FACILITYDETAIL_ACTIVITY(
	ActivityCode,
	FacilityReportID,
	RankingNumeric
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_POLLUTANTRELEASE_INDEX')
	DROP INDEX FACILITYDETAIL_POLLUTANTRELEASE_INDEX ON FACILITYDETAIL_POLLUTANTRELEASE
go
CREATE INDEX FACILITYDETAIL_POLLUTANTRELEASE_INDEX 
on FACILITYDETAIL_POLLUTANTRELEASE(
	LOV_MediumID,
	LOV_PollutantID,
	MethodTypeCode,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_POLLUTANTTRANSFER_INDEX')
	DROP INDEX FACILITYDETAIL_POLLUTANTTRANSFER_INDEX ON FACILITYDETAIL_POLLUTANTTRANSFER
go
CREATE INDEX FACILITYDETAIL_POLLUTANTTRANSFER_INDEX 
on FACILITYDETAIL_POLLUTANTTRANSFER(
	LOV_PollutantID,
	MethodTypeCode,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'FACILITYDETAIL_WASTETRANSFER_INDEX')
	DROP INDEX FACILITYDETAIL_WASTETRANSFER_INDEX ON FACILITYDETAIL_WASTETRANSFER
go
CREATE INDEX FACILITYDETAIL_WASTETRANSFER_INDEX 
on FACILITYDETAIL_WASTETRANSFER(
	LOV_WasteTypeID,
	LOV_WasteTreatmentID,
	LOV_MethodBasisID,
	FacilityReportID
)
go

--select * from EPRTRweb.dbo.FACILITYDETAIL_DETAIL
--select * from EPRTRweb.dbo.FACILITYDETAIL_COMPETENTAUTHORITYPARTY
--select * from EPRTRweb.dbo.FACILITYDETAIL_ACTIVITY
--select * from EPRTRweb.dbo.FACILITYDETAIL_POLLUTANTRELEASE
--select * from EPRTRweb.dbo.FACILITYDETAIL_POLLUTANTTRANSFER
--select * from EPRTRweb.dbo.FACILITYDETAIL_WASTETRANSFER

----------------------------------------------------------

--select * from EPRTRweb.dbo.ACTIVITYSEARCH_MAINACTIVITY
--select * from EPRTRweb.dbo.ACTIVITYSEARCH_POLLUTANTRELEASE
--select * from EPRTRweb.dbo.ACTIVITYSEARCH_POLLUTANTTRANSFER

----------------------------------------------------------

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTRELEASE_INDEX')
	DROP INDEX POLLUTANTRELEASE_INDEX ON POLLUTANTRELEASE
go
CREATE UNIQUE CLUSTERED INDEX POLLUTANTRELEASE_INDEX 
ON POLLUTANTRELEASE (
	ReportingYear desc, 
	LOV_CountryID, 
	LOV_PollutantID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTRELEASE_INDEX_CI')
	DROP INDEX POLLUTANTRELEASE_INDEX_CI ON POLLUTANTRELEASE
go
CREATE INDEX POLLUTANTRELEASE_INDEX_CI 
ON POLLUTANTRELEASE (
	ReportingYear desc, 
	ConfidentialIndicator,
	ConfidentialIndicatorFacility
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE_INDEX')
	DROP INDEX POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE_INDEX ON sde.POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE
go
CREATE UNIQUE INDEX POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE_INDEX 
ON sde.POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE (
	ReportingYear desc, 
	LOV_CountryID, 
	LOV_PollutantID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTRELEASE_SPI')
	DROP INDEX POLLUTANTRELEASE_SPI ON sde.POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE
go
CREATE SPATIAL INDEX POLLUTANTRELEASE_SPI
ON sde.POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE(GeographicalCoordinate)
USING GEOMETRY_GRID
WITH (
		BOUNDING_BOX = (-63.1536409894401,-21.3898529982173,55.8367689986903,71.2021899785846),
		GRIDS = (medium, medium, medium, medium), CELLS_PER_OBJECT = 16
	)

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTTRANSFER_INDEX')
	DROP INDEX POLLUTANTTRANSFER_INDEX ON POLLUTANTTRANSFER
go
CREATE UNIQUE CLUSTERED INDEX POLLUTANTTRANSFER_INDEX 
ON POLLUTANTTRANSFER (
	ReportingYear desc, 
	LOV_CountryID, 
	LOV_PollutantID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTTRANSFER_INDEX_CI')
	DROP INDEX POLLUTANTTRANSFER_INDEX_CI ON POLLUTANTTRANSFER
go
CREATE INDEX POLLUTANTTRANSFER_INDEX_CI 
ON POLLUTANTTRANSFER (
	ReportingYear desc, 
	ConfidentialIndicator,
	ConfidentialIndicatorFacility
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE_INDEX')
	DROP INDEX POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE_INDEX ON sde.POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE
go
CREATE UNIQUE INDEX POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE_INDEX 
ON sde.POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE (
	ReportingYear desc, 
	LOV_CountryID, 
	LOV_PollutantID, 
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'POLLUTANTTRANSFER_SPI')
	DROP INDEX POLLUTANTTRANSFER_SPI ON sde.POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE
go
CREATE SPATIAL INDEX POLLUTANTTRANSFER_SPI
ON	sde.POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE(GeographicalCoordinate)
USING GEOMETRY_GRID
WITH (
	BOUNDING_BOX = (-63.1536409894401,-21.3898529982173,55.8367689986903,71.2021899785846),
	GRIDS = (medium, medium, medium, medium), CELLS_PER_OBJECT = 16
	)

--select * from EPRTRweb.dbo.POLLUTANTRELEASE
--select * from EPRTRweb.dbo.POLLUTANTRELEASE_COMPAREYEAR
--select * from EPRTRweb.sde.POLLUTANTRELEASE_GEOGRAPHICALCOORDINATE
--select * from EPRTRweb.dbo.POLLUTANTTRANSFER
--select * from EPRTRweb.dbo.POLLUTANTTRANSFER_COMPAREYEAR
--select * from EPRTRweb.sde.POLLUTANTTRANSFER_GEOGRAPHICALCOORDINATE
----------------------------------------------------------

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_INDEX')
	DROP INDEX WASTETRANSFER_INDEX ON WASTETRANSFER
go
CREATE UNIQUE CLUSTERED INDEX WASTETRANSFER_INDEX 
on WASTETRANSFER(
	ReportingYear,
	LOV_CountryID,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_INDEX_CI')
	DROP INDEX WASTETRANSFER_INDEX_CI ON WASTETRANSFER
go
CREATE INDEX WASTETRANSFER_INDEX_CI 
on WASTETRANSFER(
	ReportingYear,
	ConfidentialIndicatorWaste,
	ConfidentialIndicatorFacility
)

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_TREATMENT_INDEX')
	DROP INDEX WASTETRANSFER_TREATMENT_INDEX ON WASTETRANSFER_TREATMENT
go
CREATE UNIQUE CLUSTERED INDEX WASTETRANSFER_TREATMENT_INDEX 
on WASTETRANSFER_TREATMENT(
	ReportingYear,
	LOV_CountryID,
	FacilityReportID,
	WasteTypeCode	
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_RECEIVINGCOUNTRY_INDEX')
	DROP INDEX WASTETRANSFER_RECEIVINGCOUNTRY_INDEX ON WASTETRANSFER_RECEIVINGCOUNTRY
go
CREATE CLUSTERED INDEX WASTETRANSFER_RECEIVINGCOUNTRY_INDEX 
on WASTETRANSFER_RECEIVINGCOUNTRY(
	ReportingYear,
	LOV_CountryID,
	ReceivingCountryCode,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_HAZARDOUSTREATERS_INDEX')
	DROP INDEX WASTETRANSFER_HAZARDOUSTREATERS_INDEX ON WASTETRANSFER_HAZARDOUSTREATERS
go
CREATE CLUSTERED INDEX WASTETRANSFER_HAZARDOUSTREATERS_INDEX 
on WASTETRANSFER_HAZARDOUSTREATERS(
	ReportingYear,
	LOV_CountryID,
	WHPPostalCode,
	FacilityReportID
)
go

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'WASTETRANSFER_CONFIDENTIAL_INDEX')
	DROP INDEX WASTETRANSFER_CONFIDENTIAL_INDEX ON WASTETRANSFER_CONFIDENTIAL
go
CREATE CLUSTERED INDEX WASTETRANSFER_CONFIDENTIAL_INDEX 
on WASTETRANSFER_CONFIDENTIAL(
	ReportingYear,
	LOV_CountryID,
	LOV_WasteTypeID,
	LOV_ConfidentialityID,
	FacilityReportID
)
go

--select * from EPRTRweb.dbo.WASTETRANSFER
--select * from EPRTRweb.dbo.WASTETRANSFER_TREATMENT
--select * from EPRTRweb.dbo.WASTETRANSFER_RECEIVINGCOUNTRY
--select * from EPRTRweb.dbo.WASTETRANSFER_HAZARDOUSTREATERS
--select * from EPRTRweb.dbo.WASTETRANSFER_CONFIDENTIAL
