--ALTER TABLE LOV_POLLUTANTTHRESHOLD drop CONSTRAINT FK_LOV_POLLUTANTTHRESHOLD_LOV_MEDIUM
ALTER TABLE LOV_POLLUTANTTHRESHOLD ADD CONSTRAINT FK_LOV_POLLUTANTTHRESHOLD_LOV_MEDIUM
FOREIGN KEY (LOV_MediumID)
REFERENCES LOV_MEDIUM(LOV_MediumID)

--ALTER TABLE LOV_POLLUTANTTHRESHOLD drop CONSTRAINT FK_LOV_POLLUTANTTHRESHOLD_LOV_POLLUTANT
ALTER TABLE LOV_POLLUTANTTHRESHOLD ADD CONSTRAINT FK_LOV_POLLUTANTTHRESHOLD_LOV_POLLUTANT
FOREIGN KEY (LOV_PollutantID)
REFERENCES LOV_POLLUTANT(LOV_PollutantID)

-------------------------------------------------------------------------------

--ALTER TABLE METHODUSED drop CONSTRAINT FK_METHODUSED_LOV_METHODTYPE
ALTER TABLE METHODUSED ADD CONSTRAINT FK_METHODUSED_LOV_METHODTYPE
FOREIGN KEY (LOV_MethodTypeID)
REFERENCES LOV_METHODTYPE(LOV_MethodTypeID)

--ALTER TABLE METHODUSED drop CONSTRAINT FK_METHODUSED_METHODLIST
ALTER TABLE METHODUSED ADD CONSTRAINT FK_METHODUSED_METHODLIST
FOREIGN KEY (MethodListID)
REFERENCES METHODLIST(MethodListID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_WASTETHRESHOLD drop CONSTRAINT FK_LOV_WASTETHRESHOLD_LOV_WASTETYPE
ALTER TABLE LOV_WASTETHRESHOLD ADD CONSTRAINT FK_LOV_WASTETHRESHOLD_LOV_WASTETYPE
FOREIGN KEY (LOV_WasteTypeID)
REFERENCES LOV_WASTETYPE(LOV_WasteTypeID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_WASTETYPE drop CONSTRAINT FK_LOV_WASTETYPE_LOV_WASTETYPE
ALTER TABLE LOV_WASTETYPE ADD CONSTRAINT FK_LOV_WASTETYPE_LOV_WASTETYPE
FOREIGN KEY (ParentID)
REFERENCES LOV_WASTETYPE(LOV_WasteTypeID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_POLLUTANT drop CONSTRAINT FK_LOV_POLLUTANT_LOV_POLLUTANT
ALTER TABLE LOV_POLLUTANT ADD CONSTRAINT FK_LOV_POLLUTANT_LOV_POLLUTANT
FOREIGN KEY (ParentID)
REFERENCES LOV_POLLUTANT(LOV_PollutantID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_ANNEXIACTIVITY drop CONSTRAINT FK_LOV_ANNEXIACTIVITY_LOV_ANNEXIACTIVITY
ALTER TABLE LOV_ANNEXIACTIVITY ADD CONSTRAINT FK_LOV_ANNEXIACTIVITY_LOV_ANNEXIACTIVITY 
FOREIGN KEY (ParentID)
REFERENCES LOV_ANNEXIACTIVITY(LOV_AnnexIActivityID)

-------------------------------------------------------------------------------

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_LOV_CONFIDENTIALITY
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_LOV_CONFIDENTIALITY
FOREIGN KEY (LOV_ConfidentialityID)
REFERENCES LOV_CONFIDENTIALITY(LOV_ConfidentialityID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_WASTEHANDLERPARTY
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_WASTEHANDLERPARTY
FOREIGN KEY (WasteHandlerPartyID)
REFERENCES WASTEHANDLERPARTY(WasteHandlerPartyID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_LOV_UNIT
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_LOV_UNIT
FOREIGN KEY (LOV_QuantityUnitID)
REFERENCES LOV_UNIT(LOV_UnitID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_LOV_METHODBASIS
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_LOV_METHODBASIS
FOREIGN KEY (LOV_MethodBasisID)
REFERENCES LOV_METHODBASIS(LOV_MethodBasisID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_METHODLIST
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_METHODLIST
FOREIGN KEY (MethodListID)
REFERENCES METHODLIST(MethodListID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_LOV_WASTETREATMENT
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_LOV_WASTETREATMENT
FOREIGN KEY (LOV_WasteTreatmentID)
REFERENCES LOV_WASTETREATMENT(LOV_WasteTreatmentID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_LOV_WASTETYPE
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_LOV_WASTETYPE
FOREIGN KEY (LOV_WasteTypeID)
REFERENCES LOV_WASTETYPE(LOV_WasteTypeID)

--ALTER TABLE WASTETRANSFER drop CONSTRAINT FK_WASTETRANSFER_FACILITYREPORT 
ALTER TABLE WASTETRANSFER ADD CONSTRAINT FK_WASTETRANSFER_FACILITYREPORT 
FOREIGN KEY (FacilityReportID)
REFERENCES FACILITYREPORT(FacilityReportID)

-------------------------------------------------------------------------------

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_LOV_CONFIDENTIALITY
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_LOV_CONFIDENTIALITY 
FOREIGN KEY (LOV_ConfidentialityID)
REFERENCES LOV_CONFIDENTIALITY(LOV_ConfidentialityID)

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_LOV_UNIT
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_LOV_UNIT 
FOREIGN KEY (LOV_QuantityUnitID)
REFERENCES LOV_UNIT(LOV_UnitID)

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_METHODLIST 
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_METHODLIST 
FOREIGN KEY (MethodListID)
REFERENCES METHODLIST(MethodListID)

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_LOV_METHODBASIS 
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_LOV_METHODBASIS 
FOREIGN KEY (LOV_MethodBasisID)
REFERENCES LOV_METHODBASIS(LOV_MethodBasisID)

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_LOV_POLLUTANT 
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_LOV_POLLUTANT 
FOREIGN KEY (LOV_PollutantID)
REFERENCES LOV_POLLUTANT(LOV_PollutantID)

--ALTER TABLE POLLUTANTTRANSFER drop CONSTRAINT FK_POLLUTANTTRANSFER_FACILITYREPORT 
ALTER TABLE POLLUTANTTRANSFER ADD CONSTRAINT FK_POLLUTANTTRANSFER_FACILITYREPORT 
FOREIGN KEY (FacilityReportID)
REFERENCES FACILITYREPORT(FacilityReportID)

-------------------------------------------------------------------------------

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_CONFIDENTIALITY
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_CONFIDENTIALITY
FOREIGN KEY (LOV_ConfidentialityID)
REFERENCES LOV_CONFIDENTIALITY(LOV_ConfidentialityID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_UNIT
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_UNIT
FOREIGN KEY (LOV_TotalQuantityUnitID)
REFERENCES LOV_UNIT(LOV_UnitID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_UNIT2
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_UNIT2
FOREIGN KEY (LOV_AccidentalQuantityUnitID)
REFERENCES LOV_UNIT(LOV_UnitID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_METHODLIST
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_METHODLIST
FOREIGN KEY (MethodListID)
REFERENCES METHODLIST(MethodListID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_POLLUTANT
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_POLLUTANT
FOREIGN KEY (LOV_PollutantID)
REFERENCES LOV_POLLUTANT(LOV_PollutantID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_MEDIUM
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_MEDIUM
FOREIGN KEY (LOV_MediumID)
REFERENCES LOV_MEDIUM(LOV_MediumID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_LOV_METHODBASIS
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_LOV_METHODBASIS
FOREIGN KEY (LOV_MethodBasisID)
REFERENCES LOV_METHODBASIS(LOV_MethodBasisID)

--ALTER TABLE POLLUTANTRELEASE drop CONSTRAINT FK_POLLUTANTRELEASE_FACILITYREPORT 
ALTER TABLE POLLUTANTRELEASE ADD CONSTRAINT FK_POLLUTANTRELEASE_FACILITYREPORT 
FOREIGN KEY (FacilityReportID)
REFERENCES FACILITYREPORT(FacilityReportID)

-------------------------------------------------------------------------------

--ALTER TABLE PRODUCTIONVOLUME drop CONSTRAINT FK_PRODUCTIONVOLUME_LOV_UNIT
ALTER TABLE PRODUCTIONVOLUME ADD CONSTRAINT FK_PRODUCTIONVOLUME_LOV_UNIT
FOREIGN KEY (LOV_UnitID)
REFERENCES LOV_UNIT(LOV_UnitID)

-------------------------------------------------------------------------------

--ALTER TABLE ACTIVITY drop CONSTRAINT FK_ACTIVITY_FACILITYREPORT 
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_FACILITYREPORT 
FOREIGN KEY (FacilityReportID)
REFERENCES FACILITYREPORT(FacilityReportID)

--ALTER TABLE ACTIVITY drop CONSTRAINT FK_ACTIVITY_LOV_ANNEXIACTIVITY 
ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_LOV_ANNEXIACTIVITY 
FOREIGN KEY (LOV_AnnexIActivityID)
REFERENCES LOV_ANNEXIACTIVITY(LOV_AnnexIActivityID)

-------------------------------------------------------------------------------

--ALTER TABLE POLLUTANTRELEASEANDTRANSFERREPORT drop CONSTRAINT FK_POLLUTANTRELEASEANDTRANSFERREPORT_LOV_COORDINATESYSTEM 
ALTER TABLE POLLUTANTRELEASEANDTRANSFERREPORT ADD CONSTRAINT FK_POLLUTANTRELEASEANDTRANSFERREPORT_LOV_COORDINATESYSTEM 
FOREIGN KEY (LOV_CoordinateSystemID)
REFERENCES LOV_COORDINATESYSTEM(LOV_CoordinateSystemID)

--ALTER TABLE POLLUTANTRELEASEANDTRANSFERREPORT drop CONSTRAINT FK_POLLUTANTRELEASEANDTRANSFERREPORT_LOV_COUNTRY 
ALTER TABLE POLLUTANTRELEASEANDTRANSFERREPORT ADD CONSTRAINT FK_POLLUTANTRELEASEANDTRANSFERREPORT_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_NACEACTIVITY drop CONSTRAINT FK_LOV_NACEACTIVITY_LOV_NACEACTIVITY
ALTER TABLE LOV_NACEACTIVITY ADD CONSTRAINT FK_LOV_NACEACTIVITY_LOV_NACEACTIVITY 
FOREIGN KEY (ParentID)
REFERENCES LOV_NACEACTIVITY(LOV_NACEActivityID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_NUTSREGION drop CONSTRAINT FK_LOV_NUTSREGION_LOV_NUTSREGION 
ALTER TABLE LOV_NUTSREGION ADD CONSTRAINT FK_LOV_NUTSREGION_LOV_NUTSREGION 
FOREIGN KEY (ParentID)
REFERENCES LOV_NUTSREGION(LOV_NUTSRegionID)

--ALTER TABLE LOV_NUTSREGION drop CONSTRAINT FK_LOV_NUTSREGION_LOV_COUNTRY 
ALTER TABLE LOV_NUTSREGION ADD CONSTRAINT FK_LOV_NUTSREGION_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_RIVERBASINDISTRICT drop CONSTRAINT FK_LOV_RIVERBASINDISTRICT_LOV_COUNTRY 
ALTER TABLE LOV_RIVERBASINDISTRICT ADD CONSTRAINT FK_LOV_RIVERBASINDISTRICT_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

-------------------------------------------------------------------------------

--ALTER TABLE LOV_COUNTRYAREAGROUP drop CONSTRAINT FK_LOV_COUNTRYAREAGROUP_LOV_AREAGROUP
ALTER TABLE LOV_COUNTRYAREAGROUP ADD CONSTRAINT FK_LOV_COUNTRYAREAGROUP_LOV_AREAGROUP
FOREIGN KEY (LOV_AreaGroupID)
REFERENCES LOV_AREAGROUP(LOV_AreaGroupID)

--ALTER TABLE LOV_COUNTRYAREAGROUP drop CONSTRAINT FK_LOV_COUNTRYAREAGROUP_LOV_COUNTRY 
ALTER TABLE LOV_COUNTRYAREAGROUP ADD CONSTRAINT FK_LOV_COUNTRYAREAGROUP_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

-------------------------------------------------------------------------------

--ALTER TABLE WASTEHANDLERPARTY drop CONSTRAINT FK_WASTEHANDLERPARTY_ADDRESS 
ALTER TABLE WASTEHANDLERPARTY ADD CONSTRAINT FK_WASTEHANDLERPARTY_ADDRESS 
FOREIGN KEY (AddressID)
REFERENCES ADDRESS(AddressID)

--ALTER TABLE WASTEHANDLERPARTY drop CONSTRAINT FK_WASTEHANDLERPARTY_ADDRESS2 
ALTER TABLE WASTEHANDLERPARTY ADD CONSTRAINT FK_WASTEHANDLERPARTY_ADDRESS2 
FOREIGN KEY (SiteAddressID)
REFERENCES ADDRESS(AddressID)

-------------------------------------------------------------------------------

--ALTER TABLE COMPETENTAUTHORITYPARTY drop CONSTRAINT FK_COMPETENTAUTHORITYPARTY_LOV_COUNTRY 
ALTER TABLE COMPETENTAUTHORITYPARTY ADD CONSTRAINT FK_COMPETENTAUTHORITYPARTY_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

--ALTER TABLE COMPETENTAUTHORITYPARTY drop CONSTRAINT FK_COMPETENTAUTHORITYPARTY_ADDRESS 
ALTER TABLE COMPETENTAUTHORITYPARTY ADD CONSTRAINT FK_COMPETENTAUTHORITYPARTY_ADDRESS 
FOREIGN KEY (AddressID)
REFERENCES ADDRESS(AddressID)

-------------------------------------------------------------------------------

--ALTER TABLE ADDRESS drop CONSTRAINT FK_ADDRESS_LOV_COUNTRY 
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_LOV_COUNTRY 
FOREIGN KEY (LOV_CountryID)
REFERENCES LOV_COUNTRY(LOV_CountryID)

-------------------------------------------------------------------------------

--ALTER TABLE FACILITYLOG drop CONSTRAINT FK_FACILITYLOG_FACILITY 
ALTER TABLE FACILITYLOG ADD CONSTRAINT FK_FACILITYLOG_FACILITY 
FOREIGN KEY (FacilityID)
REFERENCES FACILITY(FacilityID)

-------------------------------------------------------------------------------

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_FACILITY 
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_FACILITY 
FOREIGN KEY (FacilityID)
REFERENCES FACILITY(FacilityID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_LOV_NUTSREGION 
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_LOV_NUTSREGION
FOREIGN KEY (LOV_NUTSRegionID)
REFERENCES LOV_NUTSREGION(LOV_NUTSRegionID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_ADDRESS
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_ADDRESS
FOREIGN KEY (AddressID)
REFERENCES ADDRESS(AddressID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_LOV_RIVERBASINDISTRICT
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_LOV_RIVERBASINDISTRICT
FOREIGN KEY (LOV_RiverBasinDistrictID)
REFERENCES LOV_RIVERBASINDISTRICT(LOV_RiverBasinDistrictID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_LOV_NACEACTIVITY
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_LOV_NACEACTIVITY
FOREIGN KEY (LOV_NACEMainEconomicActivityID)
REFERENCES LOV_NACEACTIVITY(LOV_NACEActivityID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_COMPETENTAUTHORITYPARTY
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_COMPETENTAUTHORITYPARTY
FOREIGN KEY (CompetentAuthorityPartyID)
REFERENCES COMPETENTAUTHORITYPARTY(CompetentAuthorityPartyID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_PRODUCTIONVOLUME
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_PRODUCTIONVOLUME
FOREIGN KEY (ProductionVolumeID)
REFERENCES PRODUCTIONVOLUME(ProductionVolumeID)

--ALTER TABLE FACILITYREPORT drop CONSTRAINT FK_FACILITYREPORT_LOV_CONFIDENTIALITY
ALTER TABLE FACILITYREPORT ADD CONSTRAINT FK_FACILITYREPORT_LOV_CONFIDENTIALITY
FOREIGN KEY (LOV_ConfidentialityID)
REFERENCES LOV_CONFIDENTIALITY(LOV_ConfidentialityID)
