<?xml version="1.0" encoding="utf-8"?>
<Database Name="EPRTRweb" Class="DataClassesLOVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SDKCGA6332;Initial Catalog=EPRTRpublic;User ID=sa;" SettingsObjectName="QueryLayer.Properties.Settings" SettingsPropertyName="EPRTRwebConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LOV_ANNEXIACTIVITY" Member="LOV_ANNEXIACTIVITies">
    <Type Name="LOV_ANNEXIACTIVITY">
      <Column Name="LOV_AnnexIActivityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPPCCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="eperAnnex3_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_AREAGROUP" Member="LOV_AREAGROUPs">
    <Type Name="LOV_AREAGROUP">
      <Column Name="LOV_AreaGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_CONFIDENTIALITY" Member="LOV_CONFIDENTIALITies">
    <Type Name="LOV_CONFIDENTIALITY">
      <Column Name="LOV_ConfidentialityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_COUNTRY" Member="LOV_COUNTRies">
    <Type Name="LOV_COUNTRY">
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_COUNTRYAREAGROUP" Member="LOV_COUNTRYAREAGROUPs">
    <Type Name="LOV_COUNTRYAREAGROUP">
      <Column Name="LOV_AreaGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_NUTSREGION" Member="LOV_NUTSREGIONs">
    <Type Name="LOV_NUTSREGION">
      <Column Name="LOV_NUTSRegionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_RIVERBASINDISTRICT" Member="LOV_RIVERBASINDISTRICTs">
    <Type Name="LOV_RIVERBASINDISTRICT">
      <Column Name="LOV_RiverBasinDistrictID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.REPORTINGCOUNTRY" Member="REPORTINGCOUNTRies">
    <Type Name="REPORTINGCOUNTRY">
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.REPORTINGYEAR" Member="REPORTINGYEARs">
    <Type Name="REPORTINGYEAR">
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Countries" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIVINGCOUNTRY" Member="RECEIVINGCOUNTRies">
    <Type Name="RECEIVINGCOUNTRY">
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_NACEACTIVITY" Member="LOV_NACEACTIVITies">
    <Type Name="LOV_NACEACTIVITY">
      <Column Name="LOV_NACEActivityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LATEST_DATAIMPORT" Member="LATEST_DATAIMPORTs">
    <Type Name="LATEST_DATAIMPORT">
      <Column Name="ReportingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForReview" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Published" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_POLLUTANT" Member="LOV_POLLUTANTs">
    <Type Name="LOV_POLLUTANT">
      <Column Name="LOV_PollutantID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="eperPollutant_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeEPER" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>