cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_facilitydetails.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_facilitylevels_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_facilitylevels_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_industrialactivity_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_industrialactivity_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_mapsearch.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_mapsearch_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\testconfig.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_REVIEW"

rem update of review maps regarding search
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Air/" "PRTR_REVIEW/"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRreview\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Internal/" "PRTR_REVIEW/"


cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_facilitydetails.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_facilitylevels_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_facilitylevels_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_industrialactivity_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_industrialactivity_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_mapsearch.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_mapsearch_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\testconfig.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_wastetransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_wastetransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_pollutanttransfer_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_pollutanttransfer_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_pollutantrelease_ex.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\config_ts_pollutantrelease_result.xml" "http://sdkcga6307/ArcGIS/rest/services/Air" "http://sdkcga6307/ArcGIS/rest/services/PRTR_PUBLIC"

rem update of review maps regarding search - only in review
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Air/" "PRTR_PUBLIC/"
cscript replace.vbs "C:\Inetpub\wwwroot\EPRTRpublic\EPRTRweb\Map\com\esri\solutions\flexviewer\widgets\SearchWidget.xml" "Internal/" "PRTR_PUBLIC/"


