CLASSPATH=bin;bin/jtds-1.2.5.jar

extract: compile
	del *.rdf *.zip /f
	java -cp $(CLASSPATH) GenerateRDF  {LookupTables} > lookuptables.rdf
	{rdfExportTables}
	zip -r rdf_export . -i \*.rdf
	del *.rdf /f

compile: GenerateRDF.class

GenerateRDF.class: GenerateRDF.java
	javac -cp $(CLASSPATH) GenerateRDF.java -d bin


