#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRTR.ResourceProviders
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="EPRTRcms")]
	public partial class DBResourceDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReviseResourceKey(ReviseResourceKey instance);
    partial void UpdateReviseResourceKey(ReviseResourceKey instance);
    partial void DeleteReviseResourceKey(ReviseResourceKey instance);
    partial void InsertReviseResourceValue(ReviseResourceValue instance);
    partial void UpdateReviseResourceValue(ReviseResourceValue instance);
    partial void DeleteReviseResourceValue(ReviseResourceValue instance);
    #endregion
		
        //public DBResourceDataClassesDataContext() : 
        //        base(global::EPRTR.ResourceProviders.Properties.Settings.Default.EPRTRcmsConnectionString, mappingSource)
        //{
        //    OnCreated();
        //}
		
		public DBResourceDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBResourceDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBResourceDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBResourceDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StringResource> StringResources
		{
			get
			{
				return this.GetTable<StringResource>();
			}
		}
		
		public System.Data.Linq.Table<ReviseResourceKey> ReviseResourceKeys
		{
			get
			{
				return this.GetTable<ReviseResourceKey>();
			}
		}
		
		public System.Data.Linq.Table<ReviseResourceValue> ReviseResourceValues
		{
			get
			{
				return this.GetTable<ReviseResourceValue>();
			}
		}
	}
	
	[Table(Name="dbo.StringResource")]
	public partial class StringResource
	{
		
		private string _ResourceType;
		
		private string _ResourceKey;
		
		private string _CultureCode;
		
		private string _ResourceValue;
		
		public StringResource()
		{
		}
		
		[Column(Storage="_ResourceType", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ResourceType
		{
			get
			{
				return this._ResourceType;
			}
			set
			{
				if ((this._ResourceType != value))
				{
					this._ResourceType = value;
				}
			}
		}
		
		[Column(Storage="_ResourceKey", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ResourceKey
		{
			get
			{
				return this._ResourceKey;
			}
			set
			{
				if ((this._ResourceKey != value))
				{
					this._ResourceKey = value;
				}
			}
		}
		
		[Column(Storage="_CultureCode", DbType="NVarChar(10)")]
		public string CultureCode
		{
			get
			{
				return this._CultureCode;
			}
			set
			{
				if ((this._CultureCode != value))
				{
					this._CultureCode = value;
				}
			}
		}
		
		[Column(Storage="_ResourceValue", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ResourceValue
		{
			get
			{
				return this._ResourceValue;
			}
			set
			{
				if ((this._ResourceValue != value))
				{
					this._ResourceValue = value;
				}
			}
		}
	}
	
	
}
#pragma warning restore 1591
