<?xml version="1.0" encoding="utf-8"?>
<Database Name="EPRTRweb" Class="DataClassesFacilityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.FACILITYDETAIL_ACTIVITY" Member="FACILITYDETAIL_ACTIVITies">
    <Type Name="FACILITYDETAIL_ACTIVITY">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MainActivityIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RankingNumeric" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IAReportedActivityCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IPPCReportedActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ActivityIPPCCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubActivityIPPCCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYDETAIL_COMPETENTAUTHORITYPARTY" Member="FACILITYDETAIL_COMPETENTAUTHORITYPARTies">
    <Type Name="FACILITYDETAIL_COMPETENTAUTHORITYPARTY">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CAName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CAAddress" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="CACity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAPostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CATelephoneCommunication" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAFaxCommunication" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAEmailCommunication" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CAContactPersonName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAReportingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CALastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYDETAIL_DETAIL" Member="FACILITYDETAIL_DETAILs">
    <Type Name="FACILITYDETAIL_DETAIL">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FacilityName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NationalID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ReportingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ParentCompanyName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Coordinates" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CoordinateStatusCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NUTSRegionLevel1Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NUTSRegionLevel2Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NUTSRegionLevel3Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NUTSRegionSourceCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RiverBasinDistrictCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RiverBasinDistrictSourceCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACESectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACEActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACESubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IASectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IAActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IASubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductionVolumeProductName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductionVolumeQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProductionVolumeUnitCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TotalIPPCInstallationQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalEmployeeQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatingHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebsiteCommunication" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PublicInformation" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConfidentialIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialIndicatorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConfidentialIndicatorWaste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfidentialIndicatorPollutantRelease" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfidentialIndicatorPollutantTransfer" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYDETAIL_POLLUTANTRELEASE" Member="FACILITYDETAIL_POLLUTANTRELEASEs">
    <Type Name="FACILITYDETAIL_POLLUTANTRELEASE">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PollutantTo" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PollutantCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CAS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MethodCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MethodDesignation" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodTypeCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalQuantityUnitCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AccidentalQuantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AccidentalQuantityUnitCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConfidentialIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_MediumID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MethodListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_PollutantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_PollutantGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_MethodBasisID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_ConfidentialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYDETAIL_POLLUTANTTRANSFER" Member="FACILITYDETAIL_POLLUTANTTRANSFERs">
    <Type Name="FACILITYDETAIL_POLLUTANTTRANSFER">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PollutantCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CAS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MethodCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MethodDesignation" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodTypeCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UnitCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_PollutantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_PollutantGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_MethodBasisID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_ConfidentialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYDETAIL_WASTETRANSFER" Member="FACILITYDETAIL_WASTETRANSFERs">
    <Type Name="FACILITYDETAIL_WASTETRANSFER">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WasteTransferID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WasteTypeCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WasteTreatmentCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodDesignation" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MethodTypeCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WHPName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPAddress" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="WHPCity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPPostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WHPCountryCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPSiteAddress" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="WHPSiteCity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPSitePostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WHPSiteCountryCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConfidentialIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_WasteTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_WasteTreatmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_MethodBasisID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_ConfidentialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYSEARCH_ALL" Member="FACILITYSEARCH_ALLs">
    <Type Name="FACILITYSEARCH_ALL">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOV_PollutantGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PollutantGroupCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_PollutantID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PollutantCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MediumCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConfidentialIndicatorPollutant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LOV_MediumID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_ConfidentialityIDPollutant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfidentialCodePollutant" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IDWaste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_WasteTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WasteTypeCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_WasteTreatmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WasteTreatmentCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPCountryCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WHPCountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfidentialIndicatorWaste" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LOV_ConfidentialityIDWaste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfidentialCodeWaste" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FacilityName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NationalID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCompanyName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReportingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RiverBasinDistrictCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LOV_RiverBasinDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NUTSLevel2RegionCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel1ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel2ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel3ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IASectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IAActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IASubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCSectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCSubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_IASectorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_IAActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_IASubActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NACESectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACEActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACESubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_NACESectorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NACEActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NACESubActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IAReportedActivityCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IPPCReportedActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACEReportedActivityCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialIndicatorFacility" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialCodeFacility" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_ConfidentialityIDFacility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistinctID" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FacilitySearchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CitySearchName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ParentCompanySearchName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FACILITYSEARCH_MAINACTIVITY" Member="FACILITYSEARCH_MAINACTIVITies">
    <Type Name="FACILITYSEARCH_MAINACTIVITY">
      <Column Name="FacilityReportID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FacilityName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NationalID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCompanyName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReportingYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RiverBasinDistrictCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LOV_RiverBasinDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NUTSLevel2RegionCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel1ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel2ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NUTSRLevel3ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IASectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IAActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IASubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCSectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPPCSubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_IASectorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_IAActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_IASubActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NACESectorCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACEActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACESubActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_NACESectorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NACEActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOV_NACESubActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IAReportedActivityCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IPPCReportedActivityCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NACEReportedActivityCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialIndicator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConfidentialCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LOV_ConfidentialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>