<?xml version="1.0" encoding="utf-8"?>
<Database Name="EPRTRcms" Class="DataClassesCmsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ReviseResourceValue" Member="ReviseResourceValues">
    <Type Name="ReviseResourceValue">
      <Column Name="ResourceValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ResourceKeyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CultureCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ResourceValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ReviseResourceKey_ReviseResourceValue" Member="ReviseResourceKey" ThisKey="ResourceKeyID" OtherKey="ResourceKeyID" Type="ReviseResourceKey" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReviseResourceKey" Member="ReviseResourceKeys">
    <Type Name="ReviseResourceKey">
      <Column Name="ResourceKeyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ResourceKey" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ResourceType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AllowHTML" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KeyDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ContentsGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ReviseResourceKey_ReviseResourceValue" Member="ReviseResourceValues" ThisKey="ResourceKeyID" OtherKey="ResourceKeyID" Type="ReviseResourceValue" />
      <Association Name="LOV_ContentsGroup_ReviseResourceKey" Member="LOV_ContentsGroup" ThisKey="ContentsGroupID" OtherKey="LOV_ContentsGroupID" Type="LOV_ContentsGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOV_ContentsGroup" Member="LOV_ContentsGroups">
    <Type Name="LOV_ContentsGroup">
      <Column Name="LOV_ContentsGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOV_ContentsGroup_ReviseResourceKey" Member="ReviseResourceKeys" ThisKey="LOV_ContentsGroupID" OtherKey="ContentsGroupID" Type="ReviseResourceKey" />
    </Type>
  </Table>
</Database>