insert into Common_OtherGasesType ( [value] ) values ('Blast furnace gas');
insert into Common_OtherGasesType ( [value] ) values ('Products of gasification');
insert into Common_OtherGasesType ( [value] ) values ('Other');

insert into Common_OtherSolidFuels ( [value] ) values ('Peat');
insert into Common_OtherSolidFuels ( [value] ) values ('Lignite');
insert into Common_OtherSolidFuels ( [value] ) values ('Sub-bituminous coal');
insert into Common_OtherSolidFuels ( [value] ) values ('Bituminous coal');
insert into Common_OtherSolidFuels ( [value] ) values ('Anthracite');
insert into Common_OtherSolidFuels ( [value] ) values ('Other');

insert into Common_MethodBasisCodeType ( [value] ) values ('C - Calculated');
insert into Common_MethodBasisCodeType ( [value] ) values ('E - Estimated');
insert into Common_MethodBasisCodeType ( [value] ) values ('M - Measured');

insert into Common_MethodTypeCodeType ( [value] ) values ('ALT - Alternative measurement methodology in accordance with existing CEN/ISO measurements standards');
insert into Common_MethodTypeCodeType ( [value] ) values ('CEN/ISO - Internationally approved measurement standard');
insert into Common_MethodTypeCodeType ( [value] ) values ('CRM - Measurement methodology for the performance of which is demonstrated by means of certified reference materials and accepted by competent authority.');
insert into Common_MethodTypeCodeType ( [value] ) values ('ETS - Guidelines for the monitoring and reporting of greenhouse gas emissions under the Emission Trading Scheme');
insert into Common_MethodTypeCodeType ( [value] ) values ('IPCC - IPCC Guidelines');
insert into Common_MethodTypeCodeType ( [value] ) values ('MAB - Mass balance method which is accepted by the competent authority');
insert into Common_MethodTypeCodeType ( [value] ) values ('NRB - National or regional binding measurement/calculation methodology prescribed by legal act for the pollutant and facility concerned');
insert into Common_MethodTypeCodeType ( [value] ) values ('OTH - Other measurement/calculation methodology');
insert into Common_MethodTypeCodeType ( [value] ) values ('PER - Measurement/Calculation Methodology already prescribed by the competent authority in a licence or an operating permit for the facility');
insert into Common_MethodTypeCodeType ( [value] ) values ('SSC - European-wide sector specific calculation method');
insert into Common_MethodTypeCodeType ( [value] ) values ('UNECE/EMEP - UNECE/EMEP EMEP/CORINAIR Emission Inventory Guidebook');
insert into Common_MethodTypeCodeType ( [value] ) values ('WEIGH - Weighing');

insert into Common_StatusOfThePlantType ( [value] ) values ('Art 30(2) - existing plants under IED');
insert into Common_StatusOfThePlantType ( [value] ) values ('Art 30(3) - new plants under IED');

insert into Common_CombustionType ( [value] ) values ('Boiler');
insert into Common_CombustionType ( [value] ) values ('DieselEngine');
insert into Common_CombustionType ( [value] ) values ('GasEngine');
insert into Common_CombustionType ( [value] ) values ('GasTurbine');
insert into Common_CombustionType ( [value] ) values ('Others');

insert into Common_EnergyInputType ( [value] ) values ('Biomass');
insert into Common_EnergyInputType ( [value] ) values ('HardCoal');
insert into Common_EnergyInputType ( [value] ) values ('Lignite');
insert into Common_EnergyInputType ( [value] ) values ('LiquidFuels');
insert into Common_EnergyInputType ( [value] ) values ('NaturalGas');
insert into Common_EnergyInputType ( [value] ) values ('Peat');
insert into Common_EnergyInputType ( [value] ) values ('OtherGases');
insert into Common_EnergyInputType ( [value] ) values ('OtherSolidFuels');

insert into Common_ConfidentialCodeType ( [value] ) values ('A42a - Article 4(2)(a) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42b - Article 4(2)(b) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42c - Article 4(2)(c) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42d - Article 4(2)(d) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42e - Article 4(2)(e) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42f - Article 4(2)(f) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42g - Article 4(2)(g) of Directive 2003/4/EC');
insert into Common_ConfidentialCodeType ( [value] ) values ('A42h - Article 4(2)(h) of Directive 2003/4/EC');

insert into Common_WasteTypeCodeType ( [value] ) values ('HW - Hazardous waste');
insert into Common_WasteTypeCodeType ( [value] ) values ('HWIC - Hazardous waste within country');
insert into Common_WasteTypeCodeType ( [value] ) values ('HWOC - Harzodous waste outside country');
insert into Common_WasteTypeCodeType ( [value] ) values ('NON-HW - Non-hazardous waste');

insert into Common_WasteTreatmentCodeType ( [value] ) values ('D - Destined for disposal');
insert into Common_WasteTreatmentCodeType ( [value] ) values ('R - Destined for recovery');

insert into Common_PollutantType ( [value] ) values ('GRHGAS');
insert into Common_PollutantType ( [value] ) values ('CH4');
insert into Common_PollutantType ( [value] ) values ('CO');
insert into Common_PollutantType ( [value] ) values ('CO2 EXCL BIOMASS');
insert into Common_PollutantType ( [value] ) values ('HCFCS');
insert into Common_PollutantType ( [value] ) values ('N2O');
insert into Common_PollutantType ( [value] ) values ('PFCS');
insert into Common_PollutantType ( [value] ) values ('SF6');
insert into Common_PollutantType ( [value] ) values ('OTHGAS');
insert into Common_PollutantType ( [value] ) values ('CO');
insert into Common_PollutantType ( [value] ) values ('NH3');
insert into Common_PollutantType ( [value] ) values ('NMVOC');
insert into Common_PollutantType ( [value] ) values ('NOX');
insert into Common_PollutantType ( [value] ) values ('SOX');
insert into Common_PollutantType ( [value] ) values ('H');
insert into Common_PollutantType ( [value] ) values ('HALOGENATED ORGANIC COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('HALONS');
insert into Common_PollutantType ( [value] ) values ('HCN');
insert into Common_PollutantType ( [value] ) values ('HEPTACHLOR');
insert into Common_PollutantType ( [value] ) values ('HEVMET');
insert into Common_PollutantType ( [value] ) values ('HEXABROMOBIPHENYL');
insert into Common_PollutantType ( [value] ) values ('HEXACHLOROBENZENE (HCB)');
insert into Common_PollutantType ( [value] ) values ('HEXACHLOROBUTADIENE (HCBD)');
insert into Common_PollutantType ( [value] ) values ('CR AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('HEXACHLOROCYCLOHEXANE(HCH)');
insert into Common_PollutantType ( [value] ) values ('CU AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('HFCS');
insert into Common_PollutantType ( [value] ) values ('CYANIDES');
insert into Common_PollutantType ( [value] ) values ('HG AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('DDT');
insert into Common_PollutantType ( [value] ) values ('I)PERYLENE');
insert into Common_PollutantType ( [value] ) values ('DEHP');
insert into Common_PollutantType ( [value] ) values ('INORG');
insert into Common_PollutantType ( [value] ) values ('DICHLOROETHANE (DCE)');
insert into Common_PollutantType ( [value] ) values ('ISODRIN');
insert into Common_PollutantType ( [value] ) values ('DICHLOROMETHANE (DCM)');
insert into Common_PollutantType ( [value] ) values ('ISOPROTURON');
insert into Common_PollutantType ( [value] ) values ('DIELDRIN');
insert into Common_PollutantType ( [value] ) values ('LINDANE');
insert into Common_PollutantType ( [value] ) values ('DIURON');
insert into Common_PollutantType ( [value] ) values ('MIREX');
insert into Common_PollutantType ( [value] ) values ('ENDOSULPHAN');
insert into Common_PollutantType ( [value] ) values ('NAPHTHALENE');
insert into Common_PollutantType ( [value] ) values ('ENDRIN');
insert into Common_PollutantType ( [value] ) values ('NI AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('ETHYLBENZENE');
insert into Common_PollutantType ( [value] ) values ('NP/NPES');
insert into Common_PollutantType ( [value] ) values ('ETHYLENE OXIDE');
insert into Common_PollutantType ( [value] ) values ('OCTYLPHENOLS AND OCTYLPHENOL ETHOXYLATES');
insert into Common_PollutantType ( [value] ) values ('FLUORANTHENE');
insert into Common_PollutantType ( [value] ) values ('ORGANOTIN - COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('FLUORIDES');
insert into Common_PollutantType ( [value] ) values ('OTHORG');
insert into Common_PollutantType ( [value] ) values ('FLUORINE AND INORGANIC COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('PB AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('PCDD+PCDF (DIOXINS+FURANS)');
insert into Common_PollutantType ( [value] ) values ('PENTACHLOROBENZENE');
insert into Common_PollutantType ( [value] ) values ('PENTACHLOROPHENOL (PCP)');
insert into Common_PollutantType ( [value] ) values ('PEST');
insert into Common_PollutantType ( [value] ) values ('PHENOLS');
insert into Common_PollutantType ( [value] ) values ('PM10');
insert into Common_PollutantType ( [value] ) values ('POLYCHLORINATED BIPHENYLS (PCBS)');
insert into Common_PollutantType ( [value] ) values ('POLYCYCLIC AROMATIC HYDROCARBONS');
insert into Common_PollutantType ( [value] ) values ('SIMAZINE');
insert into Common_PollutantType ( [value] ) values ('TETRACHLOROETHANE');
insert into Common_PollutantType ( [value] ) values ('TETRACHLOROETHYLENE (PER)');
insert into Common_PollutantType ( [value] ) values ('TETRACHLOROMETHANE (TCM)');
insert into Common_PollutantType ( [value] ) values ('TOLUENE');
insert into Common_PollutantType ( [value] ) values ('TOTAL NITROGEN');
insert into Common_PollutantType ( [value] ) values ('TOTAL ORGANIC CARBON (TOC)');
insert into Common_PollutantType ( [value] ) values ('TOTAL PHOSPHORUS');
insert into Common_PollutantType ( [value] ) values ('TOXAPHENE');
insert into Common_PollutantType ( [value] ) values ('TRIBUTYLTIN AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('TRICHLOROBENZENES (TCB)');
insert into Common_PollutantType ( [value] ) values ('TRICHLOROETHANE (TCE)');
insert into Common_PollutantType ( [value] ) values ('TRICHLOROETHYLENE (TRI)');
insert into Common_PollutantType ( [value] ) values ('TRICHLOROMETHANE');
insert into Common_PollutantType ( [value] ) values ('TRIFLURALIN');
insert into Common_PollutantType ( [value] ) values ('TRIPHENYLTIN AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('VINYL CHLORIDE');
insert into Common_PollutantType ( [value] ) values ('XYLENES');
insert into Common_PollutantType ( [value] ) values ('ZN AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('ALACHLOR');
insert into Common_PollutantType ( [value] ) values ('ALDRIN');
insert into Common_PollutantType ( [value] ) values ('ANTHRACENE');
insert into Common_PollutantType ( [value] ) values ('AS AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('ASBESTOS');
insert into Common_PollutantType ( [value] ) values ('ATRAZINE');
insert into Common_PollutantType ( [value] ) values ('BENZENE');
insert into Common_PollutantType ( [value] ) values ('BENZO(G');
insert into Common_PollutantType ( [value] ) values ('BROMINATED DIPHENYLETHER');
insert into Common_PollutantType ( [value] ) values ('CD AND COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('CFCS');
insert into Common_PollutantType ( [value] ) values ('CHLORDECONE');
insert into Common_PollutantType ( [value] ) values ('CHLORFENVINPHOS');
insert into Common_PollutantType ( [value] ) values ('CHLORG');
insert into Common_PollutantType ( [value] ) values ('CHLORIDES');
insert into Common_PollutantType ( [value] ) values ('CHLORINE AND INORGANIC COMPOUNDS');
insert into Common_PollutantType ( [value] ) values ('CHLORO-ALKANES (C10-13)');
insert into Common_PollutantType ( [value] ) values ('CHLORPYRIFOS');
insert into Common_PollutantType ( [value] ) values ('CLORDANE');

insert into Common_UnitCodeType ( [value] ) values ('A90 - gigawatt');
insert into Common_UnitCodeType ( [value] ) values ('GV - gigajoule');
insert into Common_UnitCodeType ( [value] ) values ('GWH - gigawatt hour');
insert into Common_UnitCodeType ( [value] ) values ('HLT - hectolitre');
insert into Common_UnitCodeType ( [value] ) values ('KGM - kilogram');
insert into Common_UnitCodeType ( [value] ) values ('KWH - kilowatt hour');
insert into Common_UnitCodeType ( [value] ) values ('KWT - kilowatt');
insert into Common_UnitCodeType ( [value] ) values ('LTR - litre');
insert into Common_UnitCodeType ( [value] ) values ('MAW - megawatt');
insert into Common_UnitCodeType ( [value] ) values ('MTK - square metre');
insert into Common_UnitCodeType ( [value] ) values ('MTQ - cubic metre');
insert into Common_UnitCodeType ( [value] ) values ('MWH - megawatt hour');
insert into Common_UnitCodeType ( [value] ) values ('PCS - pieces');
insert into Common_UnitCodeType ( [value] ) values ('TNE - tonne (metric ton)');

insert into Common_MonthType ( [value] ) values ('January');
insert into Common_MonthType ( [value] ) values ('February');
insert into Common_MonthType ( [value] ) values ('March');
insert into Common_MonthType ( [value] ) values ('April');
insert into Common_MonthType ( [value] ) values ('May');
insert into Common_MonthType ( [value] ) values ('June');
insert into Common_MonthType ( [value] ) values ('July');
insert into Common_MonthType ( [value] ) values ('August');
insert into Common_MonthType ( [value] ) values ('September');
insert into Common_MonthType ( [value] ) values ('October');
insert into Common_MonthType ( [value] ) values ('November');
insert into Common_MonthType ( [value] ) values ('December');

insert into Common_CountryCodeType ( [value] ) values ('AT - Austria');
insert into Common_CountryCodeType ( [value] ) values ('BE - Belgium');
insert into Common_CountryCodeType ( [value] ) values ('BG - Bulgaria');
insert into Common_CountryCodeType ( [value] ) values ('CH - Switzerland');
insert into Common_CountryCodeType ( [value] ) values ('CY - Cyprus');
insert into Common_CountryCodeType ( [value] ) values ('CZ - Czech Republic');
insert into Common_CountryCodeType ( [value] ) values ('DE - Germany');
insert into Common_CountryCodeType ( [value] ) values ('DK - Denmark');
insert into Common_CountryCodeType ( [value] ) values ('EE - Estonia');
insert into Common_CountryCodeType ( [value] ) values ('EL - Greece');
insert into Common_CountryCodeType ( [value] ) values ('ES - Spain');
insert into Common_CountryCodeType ( [value] ) values ('FI - Finland');
insert into Common_CountryCodeType ( [value] ) values ('FR - France');
insert into Common_CountryCodeType ( [value] ) values ('HR - Croatia');
insert into Common_CountryCodeType ( [value] ) values ('GB - United Kingdom');
insert into Common_CountryCodeType ( [value] ) values ('HU - Hungary');
insert into Common_CountryCodeType ( [value] ) values ('IE - Ireland');
insert into Common_CountryCodeType ( [value] ) values ('IS - Iceland');
insert into Common_CountryCodeType ( [value] ) values ('IT - Italy');
insert into Common_CountryCodeType ( [value] ) values ('LT - Lithuania');
insert into Common_CountryCodeType ( [value] ) values ('LU - Luxembourg');
insert into Common_CountryCodeType ( [value] ) values ('LV - Latvia');
insert into Common_CountryCodeType ( [value] ) values ('MT - Malta');
insert into Common_CountryCodeType ( [value] ) values ('NL - Netherlands');
insert into Common_CountryCodeType ( [value] ) values ('NO - Norway');
insert into Common_CountryCodeType ( [value] ) values ('PL - Poland');
insert into Common_CountryCodeType ( [value] ) values ('PT - Portugal');
insert into Common_CountryCodeType ( [value] ) values ('RO - Romania');
insert into Common_CountryCodeType ( [value] ) values ('RS - Serbia');
insert into Common_CountryCodeType ( [value] ) values ('SE - Sweden');
insert into Common_CountryCodeType ( [value] ) values ('SI - Slovenia');
insert into Common_CountryCodeType ( [value] ) values ('SK - Slovakia');

insert into Common_TotalEmissionsToAirType ( [value] ) values ('Dust');
insert into Common_TotalEmissionsToAirType ( [value] ) values ('NOx');
insert into Common_TotalEmissionsToAirType ( [value] ) values ('SO2');

insert into Common_MediumCodeType ( [value] ) values ('AIR');
insert into Common_MediumCodeType ( [value] ) values ('LAND');
insert into Common_MediumCodeType ( [value] ) values ('WATER');