/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 16-dic-2015 12:54:48 				*/
/*  DBMS       : MSAccess 2007 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [AddressType]
(
	[StreetName] Text(255) NULL,
	[BuildingNumber] Text(255) NULL,
	[City] Text(255) NULL,
	[PostalCode] Text(255) NULL,
	[CountryID] Text(255) NULL,
	[addressTypeID] Short NOT NULL
)
;

CREATE TABLE [Common_CombustionType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_ConfidentialCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_CountryCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_EnergyInputType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_MediumCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_MethodBasisCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_MethodTypeCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_MonthType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_OtherGasesType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_OtherSolidFuels]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_PollutantType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_StatusOfThePlantType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_TotalEmissionsToAirType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_UnitCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_WasteTreatmentCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [Common_WasteTypeCodeType]
(
	[value] Text(255) NULL,
	[id] Short NOT NULL
)
;

CREATE TABLE [DesulphurisationRate]
(
	[month] Short NULL,
	[quantity] Double NULL,
	[desulphurisationRateID] Short NOT NULL,
	[iEDArt72ID] Short NULL
)
;

CREATE TABLE [EnergyInput]
(
	[type] Short NULL,
	[otherGases] Short NULL,
	[otherSolidFuels] Short NULL,
	[quantity] Double NULL,
	[energyInputID] Short NOT NULL,
	[plantReportID] Short NOT NULL
)
;

CREATE TABLE [FacilityReport]
(
	[dBFacitilyID] Text(255) NULL,
	[operationHours] Short NULL,
	[protectVoluntaryData] YesNo NULL,
	[publicInformation] Memo NULL,
	[totalEmployeeQuantity] Short NULL,
	[confidentialIndicator] YesNo NULL,
	[confidentialCode] Short NULL,
	[remarkText] Memo NULL,
	[facilityReportID] Short NOT NULL,
	[facilityReportsID] Short NULL
)
;

CREATE TABLE [FacilityReports]
(
	[facilityReportsID] Short NOT NULL,
	[reportID] Short NOT NULL
)
;

CREATE TABLE [IEDArt72]
(
	[iEDArt72_4a] YesNo NULL,
	[iEDArt72_4b] YesNo NULL,
	[remarkText] Memo NULL,
	[iEDArt72ID] Short NOT NULL,
	[plantReportID] Short NULL
)
;

CREATE TABLE [LCPDerogations]
(
	[art32TNP] YesNo NULL,
	[art33LLD] YesNo NULL,
	[art34SIS] YesNo NULL,
	[art35DHP] YesNo NULL,
	[usefulHeatProductionRollingAverage5Years] Double NULL,
	[lCPDerogationsID] Short NOT NULL,
	[plantReportID] Short NULL
)
;

CREATE TABLE [MethodUsedType]
(
	[MethodTypeCode] Short NULL,
	[Designation] Text(255) NULL,
	[methodUsedTypeID] Short NOT NULL
)
;

CREATE TABLE [PlantReport]
(
	[dBPlantId] Text(255) NULL,
	[statusOfThePlant] Short NULL,
	[mWth] Short NULL,
	[extensionBy50MWOrMore] YesNo NULL,
	[capacityAddedMW] Short NULL,
	[substantialChange] YesNo NULL,
	[capacityAffectedMW] Short NULL,
	[dateOfStartOperation] DateTime NULL,
	[refineries] YesNo NULL,
	[operationHours] Double NULL,
	[remarkText] Memo NULL,
	[plantReportID] Short NOT NULL,
	[plantReportsID] Short NULL
)
;

CREATE TABLE [PlantReports]
(
	[plantReportsID] Short NOT NULL,
	[reportID] Short NOT NULL
)
;

CREATE TABLE [PlantType]
(
	[combustionPlantType] Short NULL,
	[thermalInput] Short NULL,
	[plantTypeID] Short NOT NULL,
	[plantReportID] Short NOT NULL
)
;

CREATE TABLE [PollutantRelease]
(
	[mediumCode] Short NULL,
	[pollutantCode] Short NULL,
	[methodBasisCode] Short NULL,
	[methodUsed] Short NULL,
	[totalQuantity] Double NULL,
	[accidentalQuantity] Double NULL,
	[confidentialIndicator] YesNo NULL,
	[confidentialCode] Short NULL,
	[remarkText] Memo NULL,
	[pollutantReleaseID] Short NOT NULL,
	[facilityReportID] Short NULL
)
;

CREATE TABLE [PollutantTransfer]
(
	[pollutantCode] Short NULL,
	[methodBasisCode] Short NULL,
	[methodUsed] Short NULL,
	[quantity] Double NULL,
	[confidentialIndicator] YesNo NULL,
	[confidentialCode] Short NULL,
	[remarkText] Memo NULL,
	[pollutantTransferID] Short NOT NULL,
	[facilityReportID] Short NULL
)
;

CREATE TABLE [ProductionVolume]
(
	[productName] Text(255) NULL,
	[quantity] Short NULL,
	[productionVolumeID] Short NOT NULL,
	[facilityReportID] Short NULL
)
;

CREATE TABLE [QuantityType]
(
	[Quantity] Double NULL,
	[UnitCode] Short NULL,
	[quantityTypeID] Short NOT NULL
)
;

CREATE TABLE [Report]
(
	[countryID] Short NULL,
	[remarkText] Memo NULL,
	[reportingYear] Short NULL,
	[reportID] Short NOT NULL
)
;

CREATE TABLE [SO2]
(
	[month] Short NULL,
	[quantity] Double NULL,
	[sO2ID] Short NOT NULL,
	[iEDArt72ID] Short NULL
)
;

CREATE TABLE [TotalEmissionsToAir]
(
	[type] Short NULL,
	[quantity] Double NULL,
	[totalEmissionsToAirID] Short NOT NULL,
	[plantReportID] Short NOT NULL
)
;

CREATE TABLE [WasteHandlerParty]
(
	[name] Text(255) NULL,
	[address] Short NULL,
	[siteAddress] Short NULL,
	[wasteHandlerPartyID] Short NOT NULL,
	[wasteTransferID] Short NULL
)
;

CREATE TABLE [WasteTransfer]
(
	[wasteTypeCode] Short NULL,
	[wasteTreatmentCode] Short NULL,
	[quantity] Double NULL,
	[methodBasisCode] Short NULL,
	[methodUsed] Short NULL,
	[confidentialIndicator] YesNo NULL,
	[confidentialCode] Short NULL,
	[remarkText] Memo NULL,
	[wasteTransferID] Short NOT NULL,
	[facilityReportID] Short NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [AddressType] ADD CONSTRAINT [PK_AddressType]
	PRIMARY KEY ([addressTypeID])
;

ALTER TABLE [Common_CombustionType] ADD CONSTRAINT [PK_Common_CombustionType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_ConfidentialCodeType] ADD CONSTRAINT [PK_Common_ConfidentialCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_CountryCodeType] ADD CONSTRAINT [PK_Common_CountryCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_EnergyInputType] ADD CONSTRAINT [PK_Common_EnergyInputType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_MediumCodeType] ADD CONSTRAINT [PK_Common_MediumCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_MethodBasisCodeType] ADD CONSTRAINT [PK_Common_MethodBasisCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_MethodTypeCodeType] ADD CONSTRAINT [PK_Common_MethodTypeCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_MonthType] ADD CONSTRAINT [PK_Common_MonthType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_OtherGasesType] ADD CONSTRAINT [PK_Common_OtherGasesType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_OtherSolidFuels] ADD CONSTRAINT [PK_Common_OtherSolidFuels]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_PollutantType] ADD CONSTRAINT [PK_Common_PollutantType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_StatusOfThePlantType] ADD CONSTRAINT [PK_Common_StatusOfThePlantType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_TotalEmissionsToAirType] ADD CONSTRAINT [PK_Common_TotalEmissionsToAirType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_UnitCodeType] ADD CONSTRAINT [PK_Common_UnitCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_WasteTreatmentCodeType] ADD CONSTRAINT [PK_Common_WasteTreatmentCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [Common_WasteTypeCodeType] ADD CONSTRAINT [PK_Common_WasteTypeCodeType]
	PRIMARY KEY ([id])
;

ALTER TABLE [DesulphurisationRate] ADD CONSTRAINT [PK_DesulphurisationRate]
	PRIMARY KEY ([desulphurisationRateID])
;

ALTER TABLE [EnergyInput] ADD CONSTRAINT [PK_EnergyInput]
	PRIMARY KEY ([energyInputID])
;

ALTER TABLE [FacilityReport] ADD CONSTRAINT [PK_FacilityReport]
	PRIMARY KEY ([facilityReportID])
;

ALTER TABLE [FacilityReports] ADD CONSTRAINT [PK_FacilityReports]
	PRIMARY KEY ([facilityReportsID])
;

ALTER TABLE [IEDArt72] ADD CONSTRAINT [PK_IEDArt72]
	PRIMARY KEY ([iEDArt72ID])
;

ALTER TABLE [LCPDerogations] ADD CONSTRAINT [PK_LCPDerogations]
	PRIMARY KEY ([lCPDerogationsID])
;

ALTER TABLE [MethodUsedType] ADD CONSTRAINT [PK_MethodUsedType]
	PRIMARY KEY ([methodUsedTypeID])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [PK_PlantReport]
	PRIMARY KEY ([plantReportID])
;

ALTER TABLE [PlantReports] ADD CONSTRAINT [PK_PlantReports]
	PRIMARY KEY ([plantReportsID])
;

ALTER TABLE [PlantType] ADD CONSTRAINT [PK_PlantType]
	PRIMARY KEY ([plantTypeID])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [PK_PollutantRelease]
	PRIMARY KEY ([pollutantReleaseID])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [PK_PollutantTransfer]
	PRIMARY KEY ([pollutantTransferID])
;

ALTER TABLE [ProductionVolume] ADD CONSTRAINT [PK_ProductionVolume]
	PRIMARY KEY ([productionVolumeID])
;

ALTER TABLE [QuantityType] ADD CONSTRAINT [PK_QuantityType]
	PRIMARY KEY ([quantityTypeID])
;

ALTER TABLE [Report] ADD CONSTRAINT [PK_Report]
	PRIMARY KEY ([reportID])
;

ALTER TABLE [SO2] ADD CONSTRAINT [PK_SO2]
	PRIMARY KEY ([sO2ID])
;

ALTER TABLE [TotalEmissionsToAir] ADD CONSTRAINT [PK_TotalEmissionsToAir]
	PRIMARY KEY ([totalEmissionsToAirID])
;

ALTER TABLE [WasteHandlerParty] ADD CONSTRAINT [PK_WasteHandlerParty]
	PRIMARY KEY ([wasteHandlerPartyID])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [PK_WasteTransfer]
	PRIMARY KEY ([wasteTransferID])
;

/* Create Foreign Key Constraints */

ALTER TABLE [DesulphurisationRate] ADD CONSTRAINT [FK_DesulphurisationRate_Common_MonthType]
	FOREIGN KEY ([month]) REFERENCES [Common_MonthType] ([id])
;

ALTER TABLE [DesulphurisationRate] ADD CONSTRAINT [FK_DesulphurisationRate_IEDArt72]
	FOREIGN KEY ([iEDArt72ID]) REFERENCES [IEDArt72] ([iEDArt72ID])
;

ALTER TABLE [EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_EnergyInputType]
	FOREIGN KEY ([type]) REFERENCES [Common_EnergyInputType] ([id])
;

ALTER TABLE [EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_OtherGasesType]
	FOREIGN KEY ([otherGases]) REFERENCES [Common_OtherGasesType] ([id])
;

ALTER TABLE [EnergyInput] ADD CONSTRAINT [FK_EnergyInput_Common_OtherSolidFuels]
	FOREIGN KEY ([otherSolidFuels]) REFERENCES [Common_OtherSolidFuels] ([id])
;

ALTER TABLE [EnergyInput] ADD CONSTRAINT [FK_EnergyInput_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [PlantReport] ([plantReportID])
;

ALTER TABLE [FacilityReport] ADD CONSTRAINT [FK_FacilityReport_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [Common_ConfidentialCodeType] ([id])
;

ALTER TABLE [FacilityReport] ADD CONSTRAINT [FK_FacilityReport_FacilityReports]
	FOREIGN KEY ([facilityReportsID]) REFERENCES [FacilityReports] ([facilityReportsID])
;

ALTER TABLE [FacilityReports] ADD CONSTRAINT [FK_FacilityReports_Report]
	FOREIGN KEY ([reportID]) REFERENCES [Report] ([reportID])
;

ALTER TABLE [IEDArt72] ADD CONSTRAINT [FK_IEDArt72_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [PlantReport] ([plantReportID])
;

ALTER TABLE [LCPDerogations] ADD CONSTRAINT [FK_LCPDerogations_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [PlantReport] ([plantReportID])
;

ALTER TABLE [MethodUsedType] ADD CONSTRAINT [FK_MethodUsedType_Common_MethodTypeCodeType]
	FOREIGN KEY ([MethodTypeCode]) REFERENCES [Common_MethodTypeCodeType] ([id])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [FK_PlantReport_Common_StatusOfThePlantType]
	FOREIGN KEY ([statusOfThePlant]) REFERENCES [Common_StatusOfThePlantType] ([id])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [FK_PlantReport_PlantReports]
	FOREIGN KEY ([plantReportsID]) REFERENCES [PlantReports] ([plantReportsID])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType]
	FOREIGN KEY ([mWth]) REFERENCES [QuantityType] ([quantityTypeID])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType_02]
	FOREIGN KEY ([capacityAffectedMW]) REFERENCES [QuantityType] ([quantityTypeID])
;

ALTER TABLE [PlantReport] ADD CONSTRAINT [FK_PlantReport_QuantityType_03]
	FOREIGN KEY ([capacityAddedMW]) REFERENCES [QuantityType] ([quantityTypeID])
;

ALTER TABLE [PlantReports] ADD CONSTRAINT [FK_PlantReports_Report]
	FOREIGN KEY ([reportID]) REFERENCES [Report] ([reportID])
;

ALTER TABLE [PlantType] ADD CONSTRAINT [FK_PlantType_Common_CombustionType]
	FOREIGN KEY ([combustionPlantType]) REFERENCES [Common_CombustionType] ([id])
;

ALTER TABLE [PlantType] ADD CONSTRAINT [FK_PlantType_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [PlantReport] ([plantReportID])
;

ALTER TABLE [PlantType] ADD CONSTRAINT [FK_PlantType_QuantityType]
	FOREIGN KEY ([thermalInput]) REFERENCES [QuantityType] ([quantityTypeID])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [Common_ConfidentialCodeType] ([id])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_MediumCodeType]
	FOREIGN KEY ([mediumCode]) REFERENCES [Common_MediumCodeType] ([id])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [Common_MethodBasisCodeType] ([id])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_Common_PollutantType]
	FOREIGN KEY ([pollutantCode]) REFERENCES [Common_PollutantType] ([id])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [FacilityReport] ([facilityReportID])
;

ALTER TABLE [PollutantRelease] ADD CONSTRAINT [FK_PollutantRelease_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [MethodUsedType] ([methodUsedTypeID])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [Common_ConfidentialCodeType] ([id])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [Common_MethodBasisCodeType] ([id])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_Common_PollutantType]
	FOREIGN KEY ([pollutantCode]) REFERENCES [Common_PollutantType] ([id])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [FacilityReport] ([facilityReportID])
;

ALTER TABLE [PollutantTransfer] ADD CONSTRAINT [FK_PollutantTransfer_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [MethodUsedType] ([methodUsedTypeID])
;

ALTER TABLE [ProductionVolume] ADD CONSTRAINT [FK_ProductionVolume_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [FacilityReport] ([facilityReportID])
;

ALTER TABLE [ProductionVolume] ADD CONSTRAINT [FK_ProductionVolume_QuantityType]
	FOREIGN KEY ([quantity]) REFERENCES [QuantityType] ([quantityTypeID])
;

ALTER TABLE [QuantityType] ADD CONSTRAINT [FK_QuantityType_Common_UnitCodeType]
	FOREIGN KEY ([UnitCode]) REFERENCES [Common_UnitCodeType] ([id])
;

ALTER TABLE [Report] ADD CONSTRAINT [FK_Report_Common_CountryCodeType]
	FOREIGN KEY ([countryID]) REFERENCES [Common_CountryCodeType] ([id])
;

ALTER TABLE [SO2] ADD CONSTRAINT [FK_SO2_Common_MonthType]
	FOREIGN KEY ([month]) REFERENCES [Common_MonthType] ([id])
;

ALTER TABLE [SO2] ADD CONSTRAINT [FK_SO2_IEDArt72]
	FOREIGN KEY ([iEDArt72ID]) REFERENCES [IEDArt72] ([iEDArt72ID])
;

ALTER TABLE [TotalEmissionsToAir] ADD CONSTRAINT [FK_TotalEmissionsToAir_Common_TotalEmissionsToAirType]
	FOREIGN KEY ([type]) REFERENCES [Common_TotalEmissionsToAirType] ([id])
;

ALTER TABLE [TotalEmissionsToAir] ADD CONSTRAINT [FK_TotalEmissionsToAir_PlantReport]
	FOREIGN KEY ([plantReportID]) REFERENCES [PlantReport] ([plantReportID])
;

ALTER TABLE [WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_AddressType]
	FOREIGN KEY ([address]) REFERENCES [AddressType] ([addressTypeID])
;

ALTER TABLE [WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_AddressType_02]
	FOREIGN KEY ([siteAddress]) REFERENCES [AddressType] ([addressTypeID])
;

ALTER TABLE [WasteHandlerParty] ADD CONSTRAINT [FK_WasteHandlerParty_WasteTransfer]
	FOREIGN KEY ([wasteTransferID]) REFERENCES [WasteTransfer] ([wasteTransferID])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_ConfidentialCodeType]
	FOREIGN KEY ([confidentialCode]) REFERENCES [Common_ConfidentialCodeType] ([id])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_MethodBasisCodeType]
	FOREIGN KEY ([methodBasisCode]) REFERENCES [Common_MethodBasisCodeType] ([id])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_WasteTreatmentCodeType]
	FOREIGN KEY ([wasteTreatmentCode]) REFERENCES [Common_WasteTreatmentCodeType] ([id])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_Common_WasteTypeCodeType]
	FOREIGN KEY ([wasteTypeCode]) REFERENCES [Common_WasteTypeCodeType] ([id])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_FacilityReport]
	FOREIGN KEY ([facilityReportID]) REFERENCES [FacilityReport] ([facilityReportID])
;

ALTER TABLE [WasteTransfer] ADD CONSTRAINT [FK_WasteTransfer_MethodUsedType]
	FOREIGN KEY ([methodUsed]) REFERENCES [MethodUsedType] ([methodUsedTypeID])
;
