DECLARE @EPRTR INT, @EPER INT, @EU15 INT, @EU25 INT, @EU27 INT
SELECT @EPRTR=[LOV_AreaGroupID] FROM [dbo].[LOV_AREAGROUP] WHERE [Code]='E-PRTR'
SELECT @EU15=[LOV_AreaGroupID] FROM [dbo].[LOV_AREAGROUP] WHERE [Code]='EU15'
SELECT @EU25=[LOV_AreaGroupID] FROM [dbo].[LOV_AREAGROUP] WHERE [Code]='EU25'
SELECT @EU27=[LOV_AreaGroupID] FROM [dbo].[LOV_AREAGROUP] WHERE [Code]='EU27'

DECLARE @AT INT
SELECT @AT=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='AT'
DECLARE @BE INT
SELECT @BE=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='BE'
DECLARE @BG INT
SELECT @BG=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='BG'
DECLARE @CH INT
SELECT @CH=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='CH'
DECLARE @CY INT
SELECT @CY=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='CY'
DECLARE @CZ INT
SELECT @CZ=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='CZ'
DECLARE @DE INT
SELECT @DE=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='DE'
DECLARE @DK INT
SELECT @DK=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='DK'
DECLARE @EE INT
SELECT @EE=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='EE'
DECLARE @ES INT
SELECT @ES=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='ES'
DECLARE @FI INT
SELECT @FI=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='FI'
DECLARE @FR INT
SELECT @FR=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='FR'
DECLARE @GR INT
SELECT @GR=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='EL'
DECLARE @HU INT
SELECT @HU=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='HU'
DECLARE @IE INT
SELECT @IE=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='IE'
DECLARE @IS INT
SELECT @IS=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='IS'
DECLARE @IT INT
SELECT @IT=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='IT'
DECLARE @LI INT
SELECT @LI=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='LI'
DECLARE @LT INT
SELECT @LT=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='LT'
DECLARE @LU INT
SELECT @LU=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='LU'
DECLARE @LV INT
SELECT @LV=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='LV'
DECLARE @MT INT
SELECT @MT=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='MT'
DECLARE @NL INT
SELECT @NL=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='NL'
DECLARE @NO INT
SELECT @NO=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='NO'
DECLARE @PL INT
SELECT @PL=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='PL'
DECLARE @PT INT
SELECT @PT=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='PT'
DECLARE @RO INT
SELECT @RO=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='RO'
DECLARE @SE INT
SELECT @SE=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='SE'
DECLARE @SI INT
SELECT @SI=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='SI'
DECLARE @SK INT
SELECT @SK=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='SK'
DECLARE @UK INT
SELECT @UK=[LOV_CountryID] FROM [dbo].[LOV_COUNTRY] WHERE [Code]='UK'

INSERT INTO [dbo].[LOV_COUNTRYAREAGROUP] ([LOV_AreaGroupID], [LOV_CountryID])
 SELECT @EPRTR, @AT
  UNION ALL
 SELECT @EPRTR, @BE
  UNION ALL
 SELECT @EPRTR, @BG
  UNION ALL
 SELECT @EPRTR, @CH
  UNION ALL
 SELECT @EPRTR, @CY
  UNION ALL
 SELECT @EPRTR, @CZ
  UNION ALL
 SELECT @EPRTR, @DE
  UNION ALL
 SELECT @EPRTR, @DK
  UNION ALL
 SELECT @EPRTR, @EE
  UNION ALL
 SELECT @EPRTR, @ES
  UNION ALL
 SELECT @EPRTR, @FI
  UNION ALL
 SELECT @EPRTR, @FR
  UNION ALL
 SELECT @EPRTR, @GR
  UNION ALL
 SELECT @EPRTR, @HU
  UNION ALL
 SELECT @EPRTR, @IE
  UNION ALL
 SELECT @EPRTR, @IS
  UNION ALL
 SELECT @EPRTR, @IT
  UNION ALL
 SELECT @EPRTR, @LI
  UNION ALL
 SELECT @EPRTR, @LT
  UNION ALL
 SELECT @EPRTR, @LU
  UNION ALL
 SELECT @EPRTR, @LV
  UNION ALL
 SELECT @EPRTR, @MT
  UNION ALL
 SELECT @EPRTR, @NL
  UNION ALL
 SELECT @EPRTR, @NO
  UNION ALL
 SELECT @EPRTR, @PL
  UNION ALL
 SELECT @EPRTR, @PT
  UNION ALL
 SELECT @EPRTR, @RO
  UNION ALL
 SELECT @EPRTR, @SE
  UNION ALL
 SELECT @EPRTR, @SI
  UNION ALL
 SELECT @EPRTR, @SK
  UNION ALL
 SELECT @EPRTR, @UK

--INSERT INTO [dbo].[LOV_COUNTRYAREAGROUP] ([LOV_AreaGroupID], [LOV_CountryID])
-- SELECT @EPER, @AT
--  UNION ALL
-- SELECT @EPER, @BE
--  UNION ALL
-- SELECT @EPER, @CY
--  UNION ALL
-- SELECT @EPER, @CZ
--  UNION ALL
-- SELECT @EPER, @DE
--  UNION ALL
-- SELECT @EPER, @DK
--  UNION ALL
-- SELECT @EPER, @EE
--  UNION ALL
-- SELECT @EPER, @ES
--  UNION ALL
-- SELECT @EPER, @FI
--  UNION ALL
-- SELECT @EPER, @FR
--  UNION ALL
-- SELECT @EPER, @GR
--  UNION ALL
-- SELECT @EPER, @HU
--  UNION ALL
-- SELECT @EPER, @IE
--  UNION ALL
-- SELECT @EPER, @IT
--  UNION ALL
-- SELECT @EPER, @LT
--  UNION ALL
-- SELECT @EPER, @LU
--  UNION ALL
-- SELECT @EPER, @LV
--  UNION ALL
-- SELECT @EPER, @MT
--  UNION ALL
-- SELECT @EPER, @NL
--  UNION ALL
-- SELECT @EPER, @NO
--  UNION ALL
-- SELECT @EPER, @PL
--  UNION ALL
-- SELECT @EPER, @PT
--  UNION ALL
-- SELECT @EPER, @SE
--  UNION ALL
-- SELECT @EPER, @SI
--  UNION ALL
-- SELECT @EPER, @SK
--  UNION ALL
-- SELECT @EPER, @UK

INSERT INTO [dbo].[LOV_COUNTRYAREAGROUP] ([LOV_AreaGroupID], [LOV_CountryID])
 SELECT @EU15, @AT
  UNION ALL
 SELECT @EU15, @BE
  UNION ALL
 SELECT @EU15, @DE
  UNION ALL
 SELECT @EU15, @DK
  UNION ALL
 SELECT @EU15, @ES
  UNION ALL
 SELECT @EU15, @FI
  UNION ALL
 SELECT @EU15, @FR
  UNION ALL
 SELECT @EU15, @GR
  UNION ALL
 SELECT @EU15, @IE
  UNION ALL
 SELECT @EU15, @IT
  UNION ALL
 SELECT @EU15, @LU
  UNION ALL
 SELECT @EU15, @NL
  UNION ALL
 SELECT @EU15, @PT
  UNION ALL
 SELECT @EU15, @SE
  UNION ALL
 SELECT @EU15, @UK

INSERT INTO [dbo].[LOV_COUNTRYAREAGROUP] ([LOV_AreaGroupID], [LOV_CountryID])
 SELECT @EU25, @AT
  UNION ALL
 SELECT @EU25, @BE
  UNION ALL
 SELECT @EU25, @CY
  UNION ALL
 SELECT @EU25, @CZ
  UNION ALL
 SELECT @EU25, @DE
  UNION ALL
 SELECT @EU25, @DK
  UNION ALL
 SELECT @EU25, @EE
  UNION ALL
 SELECT @EU25, @ES
  UNION ALL
 SELECT @EU25, @FI
  UNION ALL
 SELECT @EU25, @FR
  UNION ALL
 SELECT @EU25, @GR
  UNION ALL
 SELECT @EU25, @HU
  UNION ALL
 SELECT @EU25, @IE
  UNION ALL
 SELECT @EU25, @IT
  UNION ALL
 SELECT @EU25, @LT
  UNION ALL
 SELECT @EU25, @LU
  UNION ALL
 SELECT @EU25, @LV
  UNION ALL
 SELECT @EU25, @MT
  UNION ALL
 SELECT @EU25, @NL
  UNION ALL
 SELECT @EU25, @PL
  UNION ALL
 SELECT @EU25, @PT
  UNION ALL
 SELECT @EU25, @SE
  UNION ALL
 SELECT @EU25, @SI
  UNION ALL
 SELECT @EU25, @SK
  UNION ALL
 SELECT @EU25, @UK

INSERT INTO [dbo].[LOV_COUNTRYAREAGROUP] ([LOV_AreaGroupID], [LOV_CountryID])
 SELECT @EU27, @AT
  UNION ALL
 SELECT @EU27, @BE
  UNION ALL
 SELECT @EU27, @BG
  UNION ALL
 SELECT @EU27, @CY
  UNION ALL
 SELECT @EU27, @CZ
  UNION ALL
 SELECT @EU27, @DE
  UNION ALL
 SELECT @EU27, @DK
  UNION ALL
 SELECT @EU27, @EE
  UNION ALL
 SELECT @EU27, @ES
  UNION ALL
 SELECT @EU27, @FI
  UNION ALL
 SELECT @EU27, @FR
  UNION ALL
 SELECT @EU27, @GR
  UNION ALL
 SELECT @EU27, @HU
  UNION ALL
 SELECT @EU27, @IE
  UNION ALL
 SELECT @EU27, @IT
  UNION ALL
 SELECT @EU27, @LT
  UNION ALL
 SELECT @EU27, @LU
  UNION ALL
 SELECT @EU27, @LV
  UNION ALL
 SELECT @EU27, @MT
  UNION ALL
 SELECT @EU27, @NL
  UNION ALL
 SELECT @EU27, @PL
  UNION ALL
 SELECT @EU27, @PT
  UNION ALL
 SELECT @EU27, @RO
  UNION ALL
 SELECT @EU27, @SE
  UNION ALL
 SELECT @EU27, @SI
  UNION ALL
 SELECT @EU27, @SK
  UNION ALL
 SELECT @EU27, @UK

GO

